### ISSUE TITLE
How could I open a creat calendar event page instead of save it directly?

### ISSUE THREAD

**Issue by ilovelll** [wmcmahan/react-native-calendar-events#10]
After I call RNCalendarEvents.saveEvent this function, I found it had added the canlendar event directly, could I open the confirm page like below instead of adding the event backend?
![](http://ww3.sinaimg.cn/mw690/5e06b5b0jw1f5tk733htpj20a80fkjs2.jpg)

**Comment by wmcmahan** [comment]
Sorry @ilovelll, I'm not sure I understand. Do you wish to only show an event's details but not save the event?

**Comment by ilovelll** [comment]
Yes, I want to show a details page to let user to confirm it. I'm a front-end programmer, not familiar with iOS native develop.
Thanks for your reply.

**Comment by wmcmahan** [comment]
Cool. It should be fairly easy to create a custom UI for this with React Native components, if you don't want to mess with the native IOS code. Otherwise, this package will only help in persisting and retrieving the events.

**Comment by TomMahle** [comment]
@wmcmahan would you be open to a PR that adds in this functionality? Possibly in the form of a new method with the same signature as saveEvent called openSaveEventUI. I believe we could accomplish this using similar methods to what [react-native-add-calendar-event](https://github.com/vonovak/react-native-add-calendar-event) is doing.

**Comment by TomMahle** [comment]
Actually, developers should be able to simply create the event with this library, then open it using the resulting event id with react-native-add-calendar-event if they want to give their users a comparable experience to what was requested in this issue. I'll probably do that for my use case in lieu of submitting a PR, though I think there could be some value in adding a method like what is described above.
