### ISSUE TITLE
SDK Version too low throwing error

### ISSUE THREAD

**Issue by s2jesbak** [wmcmahan/react-native-calendar-events#102]
`> The SDK Build Tools revision (23.0.1) is too low for project ':react-native-calendar-events'. Minimum required`

I had to edit the package in node_modules to '25.0.0' in order to get it to build, maybe this should be a note in the readme?

**Comment by sibelius** [comment]
check this https://github.com/react-native-community/react-native-camera/pull/1380

**Comment by MoOx** [comment]
Closing old issue. Please reopen if still relevant.
