### ISSUE TITLE
iOS - C++ Exception in 'nativeFlushQueueImmediate'

### ISSUE THREAD

**Issue by martincarrera** [wmcmahan/react-native-calendar-events#108]
I'm using this component on iOS 11.0.1 (simulator - all models).

The first time I try to create an event, I get the following error:

![simulator screen shot - iphone 6 - 2017-11-02 at 12 55 07](https://user-images.githubusercontent.com/6719062/32341401-246b603a-bfdc-11e7-92f6-e365a8ef29ad.png)

After dismissing the error, the library works as expected with no problem.

When testing on a device (iPhone 7 plus), the error is the following:

```
EVENT ERROR: Error: C++ exception in 'nativeFlushQueueImmediate'
Malformed calls from JS: field sizes are different.
```

and the behaviour is the same as before.

**Comment by xmarianox** [comment]
I'm having the same issue  

my package.json:

```json
"react": "16.0.0",
"react-native": "0.49.5",
"react-native-calendar-events": "^1.4.3",
```

**Comment by martincarrera** [comment]
My `package.json`:

```
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.0",
    "react-native-calendar-events": "^1.4.2"
```

**Comment by sibelius** [comment]
any progress on this?

**Comment by wmcmahan** [comment]
Similar issue #128 - RN might be having issues parsing the date field(s).
