### ISSUE TITLE
authorizationStatus result "Reference error: Can't find variable: record"

### ISSUE THREAD

**Issue by lbosnyak** [wmcmahan/react-native-calendar-events#109]
Hello Everybody!

I'm a newbie in react-native, so I am sorry if my question is too stupid. ;)
I have created a new very simple test for handling calendar events. When I tried to run it on my device (Android 6.0.1 / MIUI 8.5 Global) I have got the reference error message.

`import RNCalendarEvents from 'react-native-calendar-events'
constructor ....

componentWillMount(){
  RNCalendarEvents.authorizationStatus()
    .then ( status => {this.setState({auth: status})
    .catch ( error => {this.setState({auth: 'Error: '+error});

}`

I have installed the module and linked it properly.

Versions:
  react-native-cli: 2.0.1
  react-native: 0.50.1

Could you help me where is my mistake? I think it works for all, so I made something wrong.
Thanks,
lbosnyak

**Comment by wmcmahan** [comment]
@lbosnyak, could you please provide the error message?
