### ISSUE TITLE
Use promises instead of events.

### ISSUE THREAD

**Issue by quadrupleslap** [wmcmahan/react-native-calendar-events#11]
Using promises instead of events to return the ID after calendar event creation would make for a much nicer interface.

**Comment by wmcmahan** [comment]
I agree, that would be nice. I will see about trying to get that in.

**Comment by bondanherumurti** [comment]
so it is possible now to use a promise now?

**Comment by wmcmahan** [comment]
Very soon, but not yet. I will update this issue when promises are implemented.

**Comment by wmcmahan** [comment]
I've created a branch [1.0.0](https://github.com/wmcmahan/react-native-calendar-events/tree/1.0.0) that contains some changes for moving off callbacks to promises. Still needs a some cleanup, but its there if anyone is interested in testing it out and giving feedback on any issues or improvements.
