### ISSUE TITLE
Recurrence Rule

### ISSUE THREAD

**Issue by gHashTag** [wmcmahan/react-native-calendar-events#115]
## How to get the days of the custom detail? 
https://github.com/wmcmahan/react-native-calendar-events#recurrence-rule-properties

![simulator screen shot - iphone se - 2017-12-27 at 23 44 10](https://user-images.githubusercontent.com/6774813/34392925-340fc09e-eb60-11e7-8e44-5c1bc7f5c5dd.png)![simulator screen shot - iphone se - 2017-12-27 at 23 44 23](https://user-images.githubusercontent.com/6774813/34392948-488e3eb0-eb60-11e7-8b3e-8dc316318dfc.png)![simulator screen shot - iphone se - 2017-12-27 at 23 44 38](https://user-images.githubusercontent.com/6774813/34392951-4b9fe2d4-eb60-11e7-9ba4-22a323b5bc77.png)

Now I can not get the details

![2017-12-27 23 49 33](https://user-images.githubusercontent.com/6774813/34393019-a553be68-eb60-11e7-8058-02c07dce8f49.png)

**Comment by wmcmahan** [comment]
This currently not a part of the package, but I think it would be a nice addition to the recurrence settings. I will mark as future feature. Thanks

**Comment by fukemy** [comment]
hi, did this feature available now?
