### ISSUE TITLE
Android Configuration Error

### ISSUE THREAD

**Issue by ivancheng1214** [wmcmahan/react-native-calendar-events#118]
Following is part of Build.gradle 
defaultConfig {
        applicationId "com.gplans"
        minSdkVersion 23
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        renderscriptTargetApi 23
        renderscriptSupportModeEnabled true
        multiDexEnabled true
    }

targetSdkVersion >= 23
so I add following code to MainActivity.java as guide described
@Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
      CalendarEventsPackage.onRequestPermissionsResult(requestCode, permissions, grantResults);
      super.onRequestPermissionsResult(requestCode, permissions, grantResults);
   }

But only got the following error

![image](https://user-images.githubusercontent.com/25155293/34827696-fd125d06-f715-11e7-9abe-3b4cc4941f41.png)

**Comment by wmcmahan** [comment]
@ivancheng1214 Did you `import com.calendarevents.CalendarEventsPackage;` ?
