### ISSUE TITLE
remove repeating event

### ISSUE THREAD

**Issue by blackPeanut** [wmcmahan/react-native-calendar-events#12]
Hi! I've found that it's impossible to remove event with recurrence. 
Also, I can't update recurrence status to none for existing event (the second one maybe is not an issue, I've just tried to hack someway to remove existing recurrence events);

**Comment by wmcmahan** [comment]
Good call, i think its currently setup to remove a single instance of an event. I could create an extra argument for removing all future instances or a single instance.

**Comment by blackPeanut** [comment]
@wmcmahan Thank's, looks that it works (it removes actually event, I can see it after reload) but before that I've got an error: 
![screen shot 2016-08-18 at 12 11 10 am](https://cloud.githubusercontent.com/assets/12514390/17755120/681de038-64d8-11e6-9777-67d2189584f5.png)

**Comment by wmcmahan** [comment]
I'm not certain, but doing this may effect eventstore events serialization. I will have to try and repro it myself.

**Comment by wmcmahan** [comment]
I've added another method `removeFutureEvents` to handle removing recurring events. I hope it helps. I was also seeing the error above when trying to remove non-existent events. Usually because they were already removed or using an incorrect ID.

**Comment by blackPeanut** [comment]
Thanks, I will try and post a feedback

**Comment by blackPeanut** [comment]
works great, thanks

**Comment by ivancheng1214** [comment]
Hey, can you kindly add removeFutureEvents function for Android?
If no, how can I delete future events in android platform.
Thanks

**Comment by wmcmahan** [comment]
@ivancheng1214 Currently, the `removeEvent` removes all instances of a recurring event in Android. The difficulty is when trying to remove one instance from a recurring event. Although, I hope to have a update for this soon for Android.

**Comment by ivancheng1214** [comment]
Thank you

**Comment by gilons** [comment]
> @ivancheng1214 Currently, the `removeEvent` removes all instances of a recurring event in Android. The difficulty is when trying to remove one instance from a recurring event. Although, I hope to have an update for this soon for Android.

hello . Have you fixed that on android? I want to be able to delete a single event in a recurrence series
