### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by burtek** [wmcmahan/react-native-calendar-events#121]
On Android, when using `authorizeEventStore`, if calendar permissions are not granted at the beginning (i.e. user has not yet granted calendar permission), user is asked for permission (it works correctly), but Promise is neither resolved nor rejected with the result.

**Comment by wmcmahan** [comment]
Make sure you have setup the permissions handler - its the last part in the [Android setup](https://github.com/wmcmahan/react-native-calendar-events#android).

**Comment by burtek** [comment]
Thanks, I missed that.
