### ISSUE TITLE
Is it possible to fetch the events from google calendar or some other calendars and to register the event to google calendar?

### ISSUE THREAD

**Issue by yonislarsson** [wmcmahan/react-native-calendar-events#122]
Hi,

I am going to fetch the events from google calendar(, or some other calendars) and show those events on my app.
Also, I would like to register the event to google calendar.
Is it possible to do that?
If so, please let me know how can I do it.

**Comment by wmcmahan** [comment]
Hi, @yonislarsson. You can retrieve and save events from external calendars, but they will need to be synced with the device. I'm currently working to allow sync adaptors on Android.

**Comment by AnkitKumarRathi** [comment]
any update in this
