### ISSUE TITLE
iOS - authorizeEventStore() crashes even with addition to info.plist

### ISSUE THREAD

**Issue by JulianHinsch** [wmcmahan/react-native-calendar-events#124]
react-native-calendar-events: 1.4.3
react-native: 0.51.0

I added
" <key>NSCalendarsUsageDescription</key>
    <string>This app requires access to the calendar</string>"
to info.plist in my text editor.

try {
      //app works when this line is removed
      RNCalendarEvents.authorizeEventStore().then(status => console.log(status)).catch(err => console.log(err));
    } catch(err) {
         console.log(err)
  }

I'm running react-native run-ios directly in terminal (only using XCode simulators, not editor).
App opens but crashes and exits as soon as the app reaches that line.  
 RNCalendarEvents.authorizationStatus() works.

I'm interested in using your module for an application at work.  Any steps to resolve this issue would be appreciated.
Julian

**Comment by alexgurr** [comment]
I'm getting this issue and have the frameworks linked.

https://puu.sh/A38Nt/2c7f19fd53.png

Any ideas?
