### ISSUE TITLE
Cannot read property 'getCalendarPermissions' of undefined

### ISSUE THREAD

**Issue by TungUyenDo** [wmcmahan/react-native-calendar-events#126]
![capture](https://user-images.githubusercontent.com/34643360/36524087-31e2da06-17d7-11e8-8214-517b69bc57b8.PNG)

i have this issue, hope you help me!

**Comment by wmcmahan** [comment]
@TungUyenDo, ensure you have properly setup your application -[ Android setup](https://github.com/wmcmahan/react-native-calendar-events#android) - otherwise you won't have reference to the calendar events package.

**Comment by TungUyenDo** [comment]
thanks add@@

**Comment by gaurigarg97** [comment]
hey,
I am facing the same issue and would really appreciate if someone can give a solution to this please
