### ISSUE TITLE
Date on calendar events 

### ISSUE THREAD

**Issue by TungUyenDo** [wmcmahan/react-native-calendar-events#127]
- when i set date, startdate and finishdate the same only diffirent hour, but date alway next date.
Hope you help me!!
![capture](https://user-images.githubusercontent.com/34643360/36578408-9769a78e-188f-11e8-81a4-9f03ae8f5f0f.PNG)

**Comment by TungUyenDo** [comment]
@

**Comment by wmcmahan** [comment]
@TungUyenDo, I'm not sure I understand. Is the calendar event successfully saving?

**Comment by TungUyenDo** [comment]
i'm save successful, but will hide in few minute after. but is problem
I have new issue, hope you help me!
![capture](https://user-images.githubusercontent.com/34643360/36659015-9c9401d2-1b05-11e8-8830-d4abc6fefde4.PNG)
In the picture. Left is param reponse data, where x is title for event(ex: birthate, contact... you can see right picture.)

I want to ask you, how many type for title calendar(param canlendar.title) and how each type??
can you help me!

**Comment by wmcmahan** [comment]
The calendar `title` is currently read-only with this package. It will be the name (string) of a calendar you have on your device. Also, this calendar does not allow editing or creating events, see `allowsModifications: false`. You can use the method `findCalendars` to see all of calendars on the device and create an event for one that allows for modifications.
