### ISSUE TITLE
Various Simulators break with this library. (11.1, 10.3.1, 11.0,)

### ISSUE THREAD

**Issue by MrNagoo** [wmcmahan/react-native-calendar-events#128]
I grab a calendar event by id and get a " C++ Malformed Request: JS fields don't match" only on certain ones.

Does this happen to anyone else.

**Comment by wmcmahan** [comment]
@MrNagoo, could you please show the code that is causing this error?

**Comment by MrNagoo** [comment]
```
loadData() {
		let store, iOScalendars;
		AsyncStorage.getItem('AppointmentsStore')
			.then((storeResult) => {
				store = storeResult
				RNCalendarEvents.findCalendars()
		      .then(calendars => {
		        iOScalendars = calendars.sort((a, b) => b.title.toLowerCase() < a.title.toLowerCase());
		        this.setState({iOScalendars}, () => {
							if (store !== null) {
								const checkedLinks = this.checkLinks(JSON.parse(store).linkedCalendars);
								if (checkedLinks[0]) {
									this.setState({linkedCalendars: checkedLinks}, () => {
										this.createTodayList()
										this.createNextList()
										this.createPastList()
										this.setState({ dataLoaded: true})
										})
								} else {
									this.setState({ dataLoaded: true})
								}

							} else {
								console.log("no linked calendar", store);
								this.setState({dataLoaded: true});
							}
		        })
		      })
		      .catch(error => {
		        console.log("err in findCalendars", error);
		      });

			})
      .catch(error => {
        console.log("err in Async get store", error);
      });
	}
```
Tested on 10.0, 10.1, 10.2, 11.2 <- They all work. 

Here is the error I'm receiving .
```
app[5113:112755] 'err in findCalendars', { [Error: Error: C++ exception in 'nativeFlushQueueImmediate'

Malformed calls from JS: field sizes are different.

[[17,72,29],[2,3,0],[[[["AppointmentsStore","{\"linkedCalendars\":[{\"title\":\"Calendar\",\"id\":\"1CFEAAAB-91F7-4BA5-877B-FB447CE06B97\"}]}"]],1575],[24,100,1521059752609,false]],787]
```

I will be testing on a physical device (10.3.1) later today.

Thanks for the response! I hope I just have $%&T code... :)

**Comment by wmcmahan** [comment]
Thanks, I think that the error might be from something in the logic within the resolved `findCalendars` promise, rather than an error returned from the calendar. Maybe related to `AsyncStorage`?

**Comment by MrNagoo** [comment]
It is not this library.

**Comment by MrNagoo** [comment]
The date seems like it must be formatted with fractional seconds to work...
`moment.utc().format("YYYY-MM-DD[T]kk:mm:ss.SSS[Z]")`

**Comment by wmcmahan** [comment]
Interesting, iOS has been pretty good at parsing dates over the bridge. You can also use milliseconds instead of formatting to a string.

**Comment by MrNagoo** [comment]
Awesome, well... to anyone else having " C++ Malformed Request: JS fields don't match" We fixed all of our iOS errors by converting moment.js objects to strings/milliseconds. Thanks for the help!
