### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by bondanherumurti** [wmcmahan/react-native-calendar-events#13]
hi, i'm quite new on installing nativeModules, so could you please explain this section 
"Then add RNCalendarEvents, as well as EventKit.framework to project libraries.

For iOS 8 compatibility, you may need to link your project with CoreFoundation.framework (status = Optional) under Link Binary With Libraries on the Build Phases page of your project settings."

into a steps?

Thank You

**Comment by blackPeanut** [comment]
Just type `react-native link react native-calendar-events` in terminal and for better understanding what's going on read about [libraries linking in React-Native documentation](https://facebook.github.io/react-native/releases/0.24/docs/linking-libraries-ios.html#content).

**Comment by bondanherumurti** [comment]
thank you @blackPeanut !

**Comment by blackPeanut** [comment]
@bondanherumurti btw, if you will stuck with searching for eventKit & coreFoundation just add them in build phases tab, there is no need and actually possibility to add them to the project files as you will do with react-native-calendar-events in first step.

**Comment by bondanherumurti** [comment]
@blackPeanut 

i tried to test the plugin using this code

```
import React, { Component } from 'react';
import RNCalendarEvents from 'react-native-calendar-events';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableOpacity
} from 'react-native';

const {NativeAppEventEmitter} = React;

class rncalendar extends Component {

  _putOnCalendar(){
    console.log("put on calendar ya")

    RNCalendarEvents.saveEvent('title', {
      location: 'location',
      notes: 'notes',
      startDate: '2016-10-01T09:45:00.000UTC',
      endDate: '2016-10-02T09:45:00.000UTC'
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={this._putOnCalendar}>
          <Text>Put On Calendar</Text>
        </TouchableOpacity>
      </View>
    );
  }
}
}
....

//styles go here
```

but nothing happened when i hit the button, did i miss something? or wrong implementation?

**Comment by wmcmahan** [comment]
@bondanherumurti You will need to request authorization to the calendar before being able  to write/read from the calendar.

**Comment by RemeJuan** [comment]
I am also experiencing the same lack of anything happening and I am requesting/checking for permission.

`function checkPermissions(event, reminder) {
  RNCalendarEvents.authorizeEventStore(({status}) => {
    if(status.toLowerCase() === 'authorized') {
      return _addToCalendar(event, reminder);
    }

    return AlertIOS.alert(
     'Unable to create event',
     'We need permissiont o access your calendar in order to create an event.'
    );
  });
}

function _addToCalendar(event, reminder) {
  const calDate = reminder ? moment(event.sortDate).subtract(1, 'month') : event.sortDate;
  const reminderDate = moment(calDate).hour(8).minute(0).toISOString();
  const eventDate = moment(calDate).hour(0).minute(0).toISOString();

  if(reminder) {
    RNCalendarEvents.saveEvent(`Reminder: enter ${event.title}`, {
      location: 'location',
      notes: 'notes',
      startDate: reminderDate,
      endDate: reminderDate,
    });
  } else {
    RNCalendarEvents.saveEvent('title', {
      location: event.location,
      notes: 'notes',
      startDate: eventDate,
      endDate: eventDate,
      alarms: [{
        date: -60
      }]
    });
  }
}`

**Comment by bondanherumurti** [comment]
@wmcmahan thank you for your answer

```
   RNCalendarEvents.authorizeEventStore(({status}) => {
      if(status === 'authorized'){
        RNCalendarEvents.saveEvent(this.props.data.post_title, {
          location: `PVJ ${this.props.data.custom_fields.tenant.post_title}`,
          notes: 'notes',
          startDate: date.format("YYYY-MM-DDTHH:mm:ss.sssZ"),
          endDate: date.format("YYYY-MM-DDTHH:mm:ss.sssZ")
        });
      }
    })
```

this is working now

**Comment by philohelp** [comment]
I get a "cannot read property 'authorizeEventStore' of undefined' too, although I think I've linked the libraries properly. Is there anything else that could provoke that 

<img width="694" alt="capture d ecran 2016-10-07 23 55 12" src="https://cloud.githubusercontent.com/assets/12623963/19206513/c355985e-8ce9-11e6-8607-4217555f20e7.png">
<img width="237" alt="capture d ecran 2016-10-07 23 56 23" src="https://cloud.githubusercontent.com/assets/12623963/19206516/c806cf8a-8ce9-11e6-90a2-7472cbbb04fb.png">
?

**Comment by wmcmahan** [comment]
@philohelp you will also need to add RNCalendarEvents under "Link Binary With Libraries" if you haven't already.

**Comment by philohelp** [comment]
Thanks, it works great now.
