### ISSUE TITLE
Add automatic changelog

### ISSUE THREAD

**Issue by sibelius** [wmcmahan/react-native-calendar-events#133]
What do u think of adding an automatically changelog?

You could follow our work on react-native-camera

check this https://github.com/react-native-community/react-native-camera/blob/master/package.json#L63

this https://github.com/react-native-community/react-native-camera/blob/master/changelog.js

the result here https://github.com/react-native-community/react-native-camera/blob/master/CHANGELOG.md

You need to setup a commitlint rule as well (https://github.com/react-native-community/react-native-camera/blob/master/package.json#L17)

**Comment by wmcmahan** [comment]
Thanks @sibelius, i think a better (or any) changelog is needed. I will take a look and add to list of additional todo items #165. Thanks!
