### ISSUE TITLE
IOS App crashes when running authorizationStatus

### ISSUE THREAD

**Issue by alexgurr** [wmcmahan/react-native-calendar-events#136]
When running  RNCalendarEvents.authorizationStatus() the app crashes (IOS). I've added the calendar line to the info.plist and the two libraries to 'Link binary with libraries'.

### Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.10.0
  Yarn: 1.5.1
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

https://puu.sh/A39qs/8510dd7d13.png
https://puu.sh/A39rf/7dbc3e47c0.png

**Comment by pzatorski** [comment]
Any luck? If not please provide more information..

**Comment by alexgurr** [comment]
Nope, same problem. What kind of information do you want?

**Comment by pzatorski** [comment]
Try to use this function:

`  componentWillMount() {
    RNCalendarEvents.authorizationStatus()
      .then((status) => {
        this.setState({ auth: status });
        if (status === 'undetermined') {
          RNCalendarEvents.authorizeEventStore().then((out) => {
            if (out == 'authorized') {
              this.setState({ auth: out });
            }
          });
        }
      })
      .catch(error => console.warn('Auth Error: ', error));
}`

**Comment by alexgurr** [comment]
I'm already doing something similar:

```
const AUTHORISED = 'authorized';
  
componentWillMount() {
    RNCalendarEvents.authorizationStatus()
      .then((status) => {
        if (status !== AUTHORISED) {
          return RNCalendarEvents.authorizeEventStore();
        }

        return Promise.resolve(AUTHORISED);
      })
      .then((status) => {
        this.setState({ authorised: status === AUTHORISED });
      });
  }
```

```return RNCalendarEvents.authorizeEventStore();``` - as soon as this line is hit, the application crashes.

**Comment by pzatorski** [comment]
It looks like you define a `const AUTHORISED = 'authorized';` before `componentWillMount` and I think you should not define variable with capital letters.

**Comment by wmcmahan** [comment]
@alexgurr Could you show the error iOS is displaying? Also, try catching the error.

**Comment by alexgurr** [comment]
When I went on to my build target -> info, some privacy keys were listed, but calendar was **not**. When I added it in here, it now **works**.

**Comment by wmcmahan** [comment]
Ah yes, ok. I will make a note this in the readme. Thanks for helping work through this issue!
