### ISSUE TITLE
android.database.sqlite.SQLiteException

### ISSUE THREAD

**Issue by zbettenbuk** [wmcmahan/react-native-calendar-events#138]
We receive the following exception on Android 4.1.2:

Fatal Exception: android.database.sqlite.SQLiteException: no such column: isPrimary (code 1): , while compiling: SELECT _id, calendar_displayName, account_name, isPrimary, calendar_access_level, allowedAvailability, account_type FROM Calendars WHERE (_id=?)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:366)
       at android.content.ContentResolver.query(ContentResolver.java:425)
       at android.content.ContentResolver.query(ContentResolver.java:367)
       at com.calendarevents.CalendarEvents.findCalendarById(CalendarEvents.java:124)
       at com.calendarevents.CalendarEvents.serializeEvent(CalendarEvents.java:857)
       at com.calendarevents.CalendarEvents.serializeEvents(CalendarEvents.java:786)
       at com.calendarevents.CalendarEvents.findEvents(CalendarEvents.java:215)
       at com.calendarevents.CalendarEvents.access$200(CalendarEvents.java:38)
       at com.calendarevents.CalendarEvents$3.run(CalendarEvents.java:1011)
       at java.lang.Thread.run(Thread.java:856)

### Environment
Fabric info see attached.

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.3
  Yarn: Not Found
  npm: 5.7.1
  Watchman: Not Found
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.51.0 => 0.51.0

### Steps to Reproduce
Request a calendar event list on Android 4.1.2 version devices

### Expected Behavior
Get a list of events

### Actual Behavior
Native crash, see above

![image](https://user-images.githubusercontent.com/9974975/39129737-885fd394-470b-11e8-8226-6f5476972696.png)

**Comment by wmcmahan** [comment]
Thanks @zbettenbuk - API 16 and below do not have a `isPrimary` column. I will add a check for that.

**Comment by wmcmahan** [comment]
closing  #168

**Comment by ParthJadav** [comment]
Recently, I also faced same issue. Finally, I found the solution.

First of all, you have to find all logged in gmail id from the device and then select any one gmail account and find its calendar id. After that you have to pass that id to the event query like this....

 `values.put(Events.CALENDAR_ID, calendarId);`

**at last call you function**

**See below method for finding email id's...**

**public static Hashtable listCalendarId(Context c) {
        try {
            if (haveCalendarReadWritePermissions((Activity) c)) {

                String projection[] = {"_id", "calendar_displayName"};
                Uri calendars;
                calendars = Uri.parse("content://com.android.calendar/calendars");

                ContentResolver contentResolver = c.getContentResolver();
                Cursor managedCursor = contentResolver.query(calendars, projection, null, null, null);

                if (managedCursor.moveToFirst()) {
                    String calName;
                    String calID;
                    int cont = 0;
                    int nameCol = managedCursor.getColumnIndex(projection[1]);
                    int idCol = managedCursor.getColumnIndex(projection[0]);
                    Hashtable<String, String> calendarIdTable = new Hashtable<>();

                    do {
                        calName = managedCursor.getString(nameCol);
                        calID = managedCursor.getString(idCol);
                        Log.v("****", "CalendarName:" + calName + " ,id:" + calID);
                        calendarIdTable.put(calName, calID);
                        cont++;
                    } while (managedCursor.moveToNext());
                    managedCursor.close();

                    return calendarIdTable;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }**

**Comment by Fashad-Ahmed** [comment]
I am having the same issue in my android pixel device.
