### ISSUE TITLE
addListener of undefined on NativeAppEventEmitter

### ISSUE THREAD

**Issue by bondanherumurti** [wmcmahan/react-native-calendar-events#14]
```
const {NativeAppEventEmitter} = React;

       this.eventEmitter = NativeAppEventEmitter.addListener('calendarEventsChanged', () => {
          RNCalendarEvents.saveEvent(this.props.data.post_title, {
            location: `PVJ ${this.props.data.custom_fields.tenant.post_title}`,
            notes: 'notes',
            startDate: date.format("YYYY-MM-DDTHH:mm:ss.sssZ"),
            endDate: date.format("YYYY-MM-DDTHH:mm:ss.sssZ")
          }, events => {
            console.log("RNCalendarEvents saveEvent:", events)
          });
        });
```

i keep getting error "addListener of undefined", did i do wrong?

**Comment by wmcmahan** [comment]
`const {NativeAppEventEmitter} = React;` should be `const {NativeAppEventEmitter} from 'react-native';`. My fault, that was an error in the readme.

The method call looks fine. A couple things to note, you may not want to call `saveEvent` inside the event handler for `calendarEventsChanged` you may end up creating more events than wanted. Also, try attaching the event listener early in the component life cycle, such as `componentWillMount` and then removing when `componentWillUnmount`.

**Comment by wmcmahan** [comment]
Also, I will be moving off of events in favor of promises, so hopefully attaching listeners won't be needed soon.
