### ISSUE TITLE
How get all calendar events from phone if event added from App (using react-native-calendar-events)

### ISSUE THREAD

**Issue by habeebrahmanpt** [wmcmahan/react-native-calendar-events#141]
can we add a calendar event including special metadata for filtering event for specific app ?
 
Environment:
  OS: Linux 4.4
  Node: 9.2.0
  Yarn: 1.3.2
  npm: 5.8.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: ^0.50.4 => 0.50.4

**Comment by wmcmahan** [comment]
Hi @habeebrahmanpt, there is currently not a way add meta data to the events store. Would creating calendars for a specific app and filtering off those work?
