### ISSUE TITLE
Error java.lang.Double cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by Convict3d** [wmcmahan/react-native-calendar-events#143]
### Environment
React Native 0.55.2
Android

### Steps to Reproduce
Use findEventById and fetchAllEvents

### Expected Behavior
Should return Event or an array of Events

### Actual Behavior
fetchAllEvents is causing the whole application to crash on android printing:
```
 java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
05-04 10:50:47.124 32462 32572 E AndroidRuntime:        at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:134)
05-04 10:50:47.124 32462 32572 E AndroidRuntime:        at com.calendarevents.CalendarEvents.findEvents(CalendarEvents.java:186)
05-04 10:50:47.124 32462 32572 E AndroidRuntime:        at com.calendarevents.CalendarEvents.access$200(CalendarEvents.java:38)
05-04 10:50:47.124 32462 32572 E AndroidRuntime:        at com.calendarevents.CalendarEvents$3.run(CalendarEvents.java:967)
05-04 10:50:47.124 32462 32572 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
```
in adb logs,

findEventById  showing error screen:
`java.lang.Double cannot be cast to java.lang.String`

**Comment by wmcmahan** [comment]
Hi @Convict3d, the calendar IDs should strings; ex:
```javascript
RNCalendarEvents.fetchAllEvents(startDate, endDate, ['2', '3'])
```

**Comment by Convict3d** [comment]
Hi @wmcmahan thank you, it is working for `fetchAllEvents`, is it the same issue for `findEventById `?

**Comment by wmcmahan** [comment]
Yes,`findEventById` also expects the ID to be a string.

**Comment by Convict3d** [comment]
@wmcmahan Thank you, it's working.
