### ISSUE TITLE
Run the app on Expo

### ISSUE THREAD

**Issue by abdallahchebaro** [wmcmahan/react-native-calendar-events#144]
Hello,

I followed the steps:
 
1.Installed the package
2. Linked the library

I am trying to run this app on expo using 'npm start', but I am receiving 'no server found'.

Any help regarding this issue? Or how should I make the app run on Expo?

Thank you,
Best Regards

**Comment by wmcmahan** [comment]
Hi @abdallahchebaro, Expo has a very similar [Calendar API](https://docs.expo.io/versions/v25.0.0/sdk/calendar.html#content).

**Comment by abdallahchebaro** [comment]
Hello @wmcmahan. I am not limiting myself to expo. I am using expo for simplicity. 

I am using a mac. So your project should work if I configure either xcode or android studio with react native, right?

**Comment by wmcmahan** [comment]
@abdallahchebaro, Yes, you will still need to setup a React Native project and you can use Xcode or Android Studio, if you like. I'm not too familiar with using Expo, but iOS and Android can be run via the React Native commans `react-native run-ios` or `react-native android`.
