### ISSUE TITLE
Is there a way to repeat the alarm from x to x minutes / hours?

### ISSUE THREAD

**Issue by rodrigofbm** [wmcmahan/react-native-calendar-events#145]
### Environment
  OS: Linux 4.13
  Node: 9.10.1
  Yarn: 1.6.0  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

### Steps to Reproduce
Just a question.

### Expected Behavior
repeat the alarm from x to x minutes / hours

### Actual Behavior
Just a question.

Is there a way to repeat the alarm from x to x minutes / hours?

**Comment by wmcmahan** [comment]
Hi @rodrigofbm, the individual alarms will not repeat, but you could add multiple alarms for a span of time. Ex:
```javascript
RNCalendarEvents.saveEvent('Event', {
  startDate: '2016-08-19T19:26:00.000Z',
  endDate: '2017-08-19T19:26:00.000Z',
  alarms: [{date: '2016-08-19T19:21:00.000Z'}]
})
```
