### ISSUE TITLE
after saving event it disappear form calendar ios

### ISSUE THREAD

**Issue by jigaryadav** [wmcmahan/react-native-calendar-events#148]
**Description** 
first have created an event with the title, end time and start time and when I save the event it got saved in the calendar but after a few mins it got removed from the calendar and  this happen only in ios. android is working perfectly 

**current version**

    "react": "^16.2.0",
    "react-native": "^0.52.0",
    "react-native-calendar-events": "^1.5.0"

i have called `RNCalendarEvents.authorizeEventStore()` before saving event 

```
RNCalendarEvents.saveEvent(eventConfig.title,eventConfig).then((e,f)=>{
         ...
 }).catch((e)=>{
      alert(e)
  })
```

**observation** 
event added successfully and removed after a while

**Comment by victormolema** [comment]
Noticed a similar issue on android (will provide specs soon) and also appearing as a birthday on google calander? (or maybe it's just me...)

**Comment by jigaryadav** [comment]
@wmcmahan  actually it was my mistake i guess, i am adding an event of the previous date so may b calender remove those events 

but after i added future events it accepted and not removed from calendar now i don't know its a bug or it meant to be like this

**Comment by jonWilsonCopart** [comment]
@victormolema My QA team is reporting the same thing, event is disappearing after a few minutes and it's showing up as a birthday.

**Comment by abhichourasia** [comment]
I am facing the same issue, on Android the event is shown as Birthday and it disappears from Calendar in few seconds.

**Comment by abhichourasia** [comment]
@jonWilsonCopart were you able tk find solution for the event turned into bday and later disappearing from calendar?

**Comment by jonWilsonCopart** [comment]
@abhichourasia Unfortunately, not yet. I tried adding the calendarId as suggested above, but no joy. Here is my code. Using React Native 0.34 and calendar events is 1.3.6. Any suggestions are appreciated!

`const setCalendarEvent = () => {
    const email = Locale.translate("contact.calendarEmail")
    RNCalendarEvents.authorizationStatus()
      .then((status) => {
        cal_auth = status
        if (status === 'undetermined') {
          RNCalendarEvents.authorizeEventStore()
              .then((check) => {
                if (check === 'authorized' && startDate && endDate) {
                  cal_auth = check
                    RNCalendarEvents.saveEvent(lotDescription, {
                      calendarId: '1',
                      location: `${props.externalLinks.webURL}`,
                      notes: `${Locale.translate("contact.pleaseJoinUs")}\n\n${lotDescription}\n${props.externalLinks.webURL}\n\n\n${Locale.translate('contact.calendarAuction').replace("{1}", email)}\n\n ${Locale.translate("contact.calendarFooter")}`,
                      description: `${Locale.translate("contact.pleaseJoinUs")}\n\n${lotDescription}\n${props.externalLinks.webURL}\n\n\n${Locale.translate('contact.calendarAuction').replace("{1}", email)}\n\n ${Locale.translate("contact.calendarFooter")}`,
                      startDate: startDate,
                      endDate: endDate,
                      calendar: ['Auctions'],
                      alarms: [{
                        date: eventReminder
                      }]
                    }).then(() => alert(Locale.translate('calendar.eventAdded')))
                      .catch((e) => console.log(e, "CREATE_EVENT_ERROR"))
                }
              })
        }
      }
      ).then(() => {
        if (cal_auth === 'authorized' && startDate && endDate) {
          RNCalendarEvents.saveEvent(lotDescription, {
            calendarId: '1',
            location: `${props.externalLinks.webURL}`,
            notes: `${Locale.translate("contact.pleaseJoinUs")}\n\n${lotDescription}\n${props.externalLinks.webURL}\n\n\n${Locale.translate('contact.calendarAuction').replace("{1}", email)}\n\n ${Locale.translate("contact.calendarFooter")}`,
            description: `${Locale.translate("contact.pleaseJoinUs")}\n\n${lotDescription}\n${props.externalLinks.webURL}\n\n\n${Locale.translate('contact.calendarAuction').replace("{1}", email)}\n\n ${Locale.translate("contact.calendarFooter")}`,
            startDate: startDate,
            endDate: endDate,
            calendar: ['Auctions'],
            alarms: [{
              date: eventReminder
            }]
          }).then(() => alert(Locale.translate('calendar.eventAdded')))
            .catch((e) => console.log(e, "CREATE_EVENT_ERROR"))
        }
      })

  }
`

**Comment by abhichourasia** [comment]
@jonWilsonCopart I got a solution for this issue. I did below and it worked fine for me on Android. I am checking for primary calendar. See below:

`const calendars = await RNCalendarEvents.findCalendars();
const primaryCalendar = calendars.find(c => c.isPrimary && c.allowsModifications);

if (!primaryCalendar) { return; }

RNCalendarEvents.saveEvent('Call User', {
    calendarId: primaryCalendar.id
    notes: 'Test Note',
    description: 'Test Note',
    startDate: <start date>,
    endDate: <end date>,
    alarms: [ { date: 5 } ]
});`

**Comment by jonWilsonCopart** [comment]
@abhichourasia Thank you my friend. I will test and let you know how it works!

**Comment by apppro123** [comment]
Hi 

I have the same problems on android (does not tested on ios) that it shows the events only for some minutes and it shows them as birthdays. 
Does anybody already found a solution.

Thank you!

**Comment by abhichourasia** [comment]
@apppro123 Were you able to try with the code in my above comment. I had same issue and that solved for me.

Let me know if it works for you.

**Comment by apppro123** [comment]
No, unfortunately, not. And its also "mysterious" that, when i call 

RNCalendarEvents.fetchAllEvents("2015-01-01T00:00:00.000Z", "2020-01-01T00:00:000Z")
      .then((events) =>{
        console.log(events);
      }).catch((error) => {
        console.error(error);
      });
    }

it just shows the dates until today but no more. And if i want to save some that later than today it deletes all other events (from me) in the google calendar. 

Thank you for any response!

**Comment by apppro123** [comment]
Does everyboday who downloaded this package has that problem????? Or have i missed a solution?
Or how do you save an event (that it doesnt disappear after)?

**Comment by apppro123** [comment]
Is it possible that there are mistakes in the native code of android? Or do i need another API for Google Calendar? When i need another API for Google Calendar , does i need different API's for different calendar's on the device?

Thank you for the response!

apppro123

**Comment by wmcmahan** [comment]
@apppro123, first make sure that the the calendar that you are writing to allows modifications.

```javascript
RNCalendarEvents.findCalendars().then(calendars => {
  console.log(calendars.filter(calendar => calendar.allowsModifications))
})
```
When creating an event, make sure to write to the calendar you wish. Otherwise it will be `calendarId = 1` for Android and the default calendar for iOS. I noticed in your example, the key for `calendarId` is incorrect, but might just be a typo.

```javascript
RNCalendarEvents.saveEvent('title', {
  calendarId: '3', // <- the calendar id `3` must allow modifications, i.e. write to / edit
  startDate: <startDate>,
  endDate: <endDate>
})
.then(eventId => {
  return RNCalendarEvents.findEventById(eventId)
})
.then(event => {
  console.log(event)
})
.catch(error => {
  console.log(error)
})
```

When requesting stored events, you also have the option to filter by calendars. I would also suggest maybe narrowing the window of time.

```javascript
RNCalendarEvents.fetchAllEvents(<startDate>, <endDate>, ['3'])
```

**Comment by apppro123** [comment]
Thank you very much!

Now it works with saving the events.
Unfortunately  I still dont get every event with fetchAllEvents() (i just get the events until (and with) today).

Thank you for further response.

**Comment by wmcmahan** [comment]
@apppro123, I'm not sure why its only returning events until today's date. My guess is that either there are no future events saved in the phone's storage (not synced with Google Cal), or the query end date is off. I have not been able to reproduce this myself.

There is no way to create calendars from this api yet, but it is a consideration for being added in.

**Comment by apppro123** [comment]
Thank you for your response!

**Comment by coderdave** [comment]
Can you not save past events, beyond about a month ago on iOS?

**Comment by MoOx** [comment]
So I understand this issue just need some documentation?

**Comment by wmcmahan** [comment]
This is a setting on the iOS device: **settings** -> **calendar** -> **Sync** -> "All Events". Might be worth mentioning in docs to avoid confusion.
