### ISSUE TITLE
Forbidden to add events to Android Calendar...

### ISSUE THREAD

**Issue by ftier-tech** [wmcmahan/react-native-calendar-events#150]
With iOS, things seems to just work peachy as expected.  However, under Android, I keep getting a 403 Forbidden when I go to create an event.  My settings.gradle and build.gradle have the correct
settings and access.  I am targeting v23 or higher and do have the appropriate authorization methods (see below).  I'm just stumped...could this have anything to do with Google moving their calendar api to v3?   I can add an event through the Calendar directly so I've verified that.

This is a terrific package, better than anything else, (from what I see on iOS), just need to get it working under Android.  Thank you for any and all help.  I can't make any promises, but their may be
naming rights for my next born for such help!  :)

### Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.7.0
  Yarn: 1.6.0
  npm: 6.0.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.4 => 0.55.4

### Steps to Reproduce
        this.title = 'BBQ';

        this.event = {
            notes: 'This is the sample event provided as an example only',
            location: 'Boca Raton, FL',
            startDate: '2018-06-06T12:00:00.000Z',
            endDate: '2018-06-06T17:00:00.000Z'
        };

        RNCalendarEvents.authorizationStatus().then(fulfilled=>{
            console.log("Fulfilled: " + fulfilled);
            if (fulfilled !== 'authorized') {
                RNCalendarEvents.authorizeEventStore().then(fulfilled=>{
                    if (fulfilled === 'authorized') {

                        console.log('Saving event');
                        RNCalendarEvents.saveEvent(this.title, this.event).then(id => { console.log("saved")},
                            error => {
                                console.log({error: error});
                            }).catch(error => {
                                console.warn(error);
                        });
                    }
                });
            }
            else {
                RNCalendarEvents.saveEvent(this.title, this.event).then(id => { console.log("saved")},
                    error => {
                        console.log({error: error});
                    }).catch(error => {
                    console.warn(error);
                });
            }
        });
### Expected Behavior
Expect to see the event in my calendar.

### Actual Behavior
This is a copy of the logcat....
05-25 07:54:38.189 14502 14530 I ReactNativeJS: Fulfilled: authorized
05-25 07:54:38.225 14502 14530 I ReactNativeJS: saved
05-25 07:54:38.458  7955 14586 E SyncLog : Can't insert event: Forbidden Entity[ id=138 calendar_id=1 calendar_sync_id=-899202677 ] 
05-25 07:54:38.458  7955 14586 E SyncLog : com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
05-25 07:54:38.458  7955 14586 E SyncLog : {
05-25 07:54:38.458  7955 14586 E SyncLog :   "errors": [
05-25 07:54:38.458  7955 14586 E SyncLog :     {
05-25 07:54:38.458  7955 14586 E SyncLog :       "reason": "forbidden",
05-25 07:54:38.458  7955 14586 E SyncLog :       "domain": "global",
05-25 07:54:38.458  7955 14586 E SyncLog :       "message": "Forbidden"
05-25 07:54:38.458  7955 14586 E SyncLog :     }
05-25 07:54:38.458  7955 14586 E SyncLog :   ],
05-25 07:54:38.458  7955 14586 E SyncLog :   "message": "Forbidden",
05-25 07:54:38.458  7955 14586 E SyncLog :   "code": 403
05-25 07:54:38.458  7955 14586 E SyncLog : }
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.android.syncadapters.calendar.CalendarRequestExecutor.executeInternal(CalendarRequestExecutor.java:133)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.android.syncadapters.calendar.CalendarRequestExecutor.execute(CalendarRequestExecutor.java:108)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.android.syncadapters.calendar.EventHandler.sendEntityToServer(EventHandler.java:453)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.android.syncadapters.calendar.CalendarSyncAdapterApiary.sendEntityToServer(CalendarSyncAdapterApiary.java:4110)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.android.syncadapters.calendar.CalendarSyncAdapterApiary.processLocalChanges(CalendarSyncAdapterApiary.java:4036)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.android.syncadapters.calendar.CalendarSyncAdapterApiary.processLocalChangesForHandler(CalendarSyncAdapterApiary.java:3934)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.android.syncadapters.calendar.CalendarSyncAdapterApiary.performSync(CalendarSyncAdapterApiary.java:792)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.google.android.syncadapters.calendar.CalendarSyncAdapterApiary.onPerformLoggedSync(CalendarSyncAdapterApiary.java:561)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at com.android.emailcommon.syncadapter.LoggingThreadedSyncAdapter.onPerformSync(LoggingThreadedSyncAdapter.java:50)
05-25 07:54:38.458  7955 14586 E SyncLog : 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
05-25 07:54:38.473  7955 14586 I CalendarSyncAdapter: Found no pending settings

**Comment by wmcmahan** [comment]
Hey @ftier-tech, thats quite the bounty reward! 😅

This is new to me, so I'm not sure why its failing to sync with google calendars on Android. I've not tested much with google calendars, but here's what I would try first.

For a quick sanity check, I would look at is the calendar writable and find the calendar you wish to save:
```javascript
RNCalendarEvents.findCalendars().then(calendars => {
  console.log(calendars)
})
```
Then, try requesting a sync when saving the event:
```javascript
RNCalendarEvents.saveEvent(title, details, {sync: true})
```
Also, are you able to read events from the google calendar? This might help clarify if its a permissions issue.

**Comment by ArthurInTheShell** [comment]
First, thanks @wmcmahan !
I tried to use the fetch all event method in an Android device that has google calendar as its default calendar. And It turns out great. Even though you are saying the save event isn't working, you could try fetch event first and see if fetch is working. @ftier-tech

**Comment by ArthurInTheShell** [comment]
It's quite weird that I can only fetch but not add event. 
I have tried it out and I get the same 403 error.
If I have any progress on this I will come back and make comment.

**Comment by ArthurInTheShell** [comment]
>     this.title = 'BBQ';

    this.event = {
      notes: 'This is the sample event provided as an example only',
      location: 'Boca Raton, FL',
      startDate: '2018-07-22T12:00:00.000Z',
      endDate: '2018-07-23T17:00:00.000Z',
      calendarId:'4'
    };
    RNCalendarEvents.saveEvent(this.title, this.event, {sync: true}).then(id => { console.log("saved") },
      error => {
        console.log({ error: error });
      }).catch(error => {
        console.warn(error);
      });

The code here works for me. The main point is to set the calendarId to any calendar that can be modify.

RNCalendarEvents.findCalendars()
          .then(calendars => {
            console.log(calendars);
            
          })
          .catch(error => {
            console.log("err in findCalendars", error);
          });

Find all calendar and only add event to those which have `allowsModifications
:
true`

**Comment by jmasaki24** [comment]
findCalendars(); gives me an empty array. I using an AVD. What does this mean?

**Comment by wmcmahan** [comment]
@jmasaki24 It means that you don't have any calendars on the device. You will need to setup a test calendar on your AVD.

**Comment by jmasaki24** [comment]
Can't believe I glossed over this. Thanks for the feedback!

**Comment by wmcmahan** [comment]
This will only save the event. UI events and actions are not handled from this library.
