### ISSUE TITLE
How can I list users (emails) that are invited for the event?

### ISSUE THREAD

**Issue by rturk** [wmcmahan/react-native-calendar-events#151]
How can I get a list of emails and or users invited for this event?

### Environment
IOS/Android 0.55

### Steps to Reproduce
Get an event.

### Expected Behavior
List of the names, emails invited for this meeting

### Actual Behavior
Invitee information is not available

**Comment by wmcmahan** [comment]
Hi @rturk, getting attendees from an event has not been created yet, but I plan on working to get this out very soon.

**Comment by hariks789** [comment]
Hi @wmcmahan @rturk For iOS this is already implemented in #132 . For android I have raised a pull request #154 . Let me know if it helps :)

**Comment by wmcmahan** [comment]
Great! Thanks, for helping with Android side @hariks789.

**Comment by hariks789** [comment]
No problems mate. Here are the android changes #155. I don't have much expertise in Java, let me know if there are any issues.

**Comment by rturk** [comment]
Nice! Reading both PRs. I'll be happy to test

**Comment by wmcmahan** [comment]
Thanks, I did some testing as well and published a minor release with the attendees list as part of the event values. Note, the attendee object in the list includes `name` and `email` although more values can be added in the future if needed. Thanks again for the help!

**Comment by rturk** [comment]
@wmcmahan nice! 

@jaburcodes & @lXSPandora FYI
