### ISSUE TITLE
Auth error empty

### ISSUE THREAD

**Issue by mikeumus** [wmcmahan/react-native-calendar-events#152]
<img width="836" alt="screen shot 2018-05-29 at 5 38 45 am" src="https://user-images.githubusercontent.com/57934/40651130-f2e0312e-6302-11e8-87f5-9dac4d9bbc8c.png">

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.2.1
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.9.1
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617
```

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.2.tar.gz => 0.55.2

### Steps to Reproduce

`exp start`

### Expected Behavior

Auth catches some error, not empty error message.

### Actual Behavior

Auth catches empty error message :/

Here's my repo:
- https://github.com/mikeumus/lucid-timer/tree/master

I'm using a detached/ejected Expo app on the lastest versions. Latest verion of Yarn. Latest Android Studio. I followed @3DEsprit's quick intro article and have spent many hours getting this to work on Android SDK 27 and Expo. I hope the issue is just something small and silly that someone might spot right away.

**Comment by wmcmahan** [comment]
Hi @mikeumus, a few thoughts. First, its not necessary to check authorization before requesting permission; `authorizeEventStore` will do this already. Also, catching the error from the request.

```javascript
componentWillMount() {
  RNCalendarEvents.authorizeEventStore()
    .then((out) => {
      if (out === 'authorized') {
        this.setState({ cal_auth: out })
      }
     })
     .catch(error => console.warn('Auth Error: ', error));
  }
```

You will also need [this line](https://github.com/mikeumus/lucid-timer/blob/b7fa99499696bfc121456cd8d601b616f4c78c9b/android/app/src/main/java/host/exp/exponent/MainApplication.java#L36) when requesting permissions.

**Comment by mikeumus** [comment]
I apply these changes but even so, the `AuthStore` and `saveEvent` call both give empty error objects:

<img width="836" alt="screen shot 2018-05-29 at 10 59 07 pm" src="https://user-images.githubusercontent.com/57934/40699686-c95ff70c-63a3-11e8-896b-9cd169b0208e.png">

I have to comment out the `Override` and `super.getPermission()` calls in `MainApplication.java` for it to build otherwise I get the error: 

```
error: method does not override or implement a method from a supertype
```

<img width="1095" alt="screen shot 2018-05-30 at 12 51 42 am" src="https://user-images.githubusercontent.com/57934/40699697-e365a390-63a3-11e8-9d46-83502bb945ed.png">

Maybe this is why it's having problems?

**Comment by wmcmahan** [comment]
Maybe, I have not used Expo so unfortunately I'm not sure how to integrate external packages with it. But it does appear that they have a `Permissions` object - [Expo docs](https://docs.expo.io/versions/v27.0.0/sdk/permissions) - that handles basically does the same as `authorizeEventStore`.

**Comment by mikeumus** [comment]
Alright, thanks for the direction. If this doesn't work I'll try it without the Expo.

**Comment by mikeumus** [comment]
It's working as an Expo app with SDK 29.
