### ISSUE TITLE
Feature Request: Multiple day of week recurrence

### ISSUE THREAD

**Issue by TomMahle** [wmcmahan/react-native-calendar-events#153]
Hello,

I have a use case for having a single event recur on multiple weekdays, e.g. 9 AM to 5 PM every Monday, Tuesday, Wednesday, Thursday, and Friday for the foreseeable future.

While this is presently possible by creating multiple events, this creates an undesirable user experience if the user has to edit those events, as each of the days of the week must be edited separately.

Both Android (see RRULE Examples [here](https://www.grokkingandroid.com/recurrence-rule-and-duration-formats/)) and [iOS](https://developer.apple.com/documentation/eventkit/ekrecurrencerule/1507320-init) support this functionality at the native level, so it should be possible to build out in principle.

As an interface suggestion, recurrenceRule could have an additional optional property daysOfWeek which is an array of strings 'sunday', ... 'monday' (with case insensitivity as sugar) or an object with keys of those same strings, and booleans for whether the event occurs on this day (defaulted to false).

Would the maintainers be willing to build out this functionality or open to a pull request? If so, any comments on the signature?

Thanks for making such a great and useful library! I look forward to any feedback on this request.

**Comment by wmcmahan** [comment]
Hi @TomMahle, yes that is a great suggestion and pull requests are always welcomed :) This is definitely something that has been wanted in this library.

**Comment by TomMahle** [comment]
@wmcmahan (or anyone else that might be interested in picking this up) I'm going with a different implementation on my project (downloading an iCal and opening it). So I won't be implementing this feature in the near term. Just wanted to make that known so that no one that wants this is waiting on me.

**Comment by wmcmahan** [comment]
Thanks @TomMahle, no worries! I have added it to a running list of futures features. Appreciate the idea!

**Comment by sinapcs** [comment]
Hi @wmcmahan. thanks for your support on this great module. Did you add this feature? because I can't find a way to do this.

**Comment by gilons** [comment]
https://github.com/wmcmahan/react-native-calendar-events/commit/caf2dd33fe6fd5f48e0535695fb5fedd8c8ab17a#diff-5fc4edde3ff9c49bbf7160523a7542ad

**Comment by gilons** [comment]
above is the commit of that feature
