### ISSUE TITLE
How can i find the event by using the API??

### ISSUE THREAD

**Issue by ycman0307** [wmcmahan/react-native-calendar-events#157]
I can success to save the event to calendar but i cannot find this event by "findEventById" and "fetchAllEvents".

  componentDidMount() {
    const s = moment.utc(new Date()).format('YYYY-MM-DDTHH:mm:ss.SSS[Z]');

    RNCalendarEvents.authorizationStatus();
    RNCalendarEvents.saveEvent('TEST event', {
      calendarId: '141',
      startDate: s,
      endDate: s,
      location: 'ABC',
      notes: 'Bring sunglasses'
    });

    console.warn(RNCalendarEvents.findEventById('141')); 
    console.warn(fetchAllEvents(s, s, [])); 
}

The result:
using findEventById: {_40":0,"_65":0,"_55:null,"_72":null}

**Comment by wmcmahan** [comment]
Hi @ycman0307, you will need to wait for the promise to resolve:

From data range:
```javascript
const s = moment.utc(new Date()).format('YYYY-MM-DDTHH:mm:ss.SSS[Z]');

RNCalendarEvents. fetchAllEvents(s, s)
  .then(events => {
    console.log(events)
  })
  .catch(err => {
    console.log(err)
  })
```

From known event id:
```javascript
RNCalendarEvents.findEventById(id)
  .then(event => {
    console.log(event)
  })
  .catch(err => {
    console.log(err)
  })
```

After saving event:
```javascript
RNCalendarEvents.saveEvent('TEST event', {
    calendarId: '141',
    startDate: s,
    endDate: s,
    location: 'ABC',
    notes: 'Bring sunglasses'
  })
  .then(id => {
    console.log(id)
    return RNCalendarEvents.findEventById(id)
  })
  .then(event => {
    console.log(event)
  })
  .catch(err => {
    console.log(err)
  })
```

**Comment by ycman0307** [comment]
I tried to use these code but it return null. 

    RNCalendarEvents.saveEvent('TEST event', {
      calendarId: '141',
      startDate: s,
      endDate: s,
      location: 'HONG KONG',
      notes: 'Bring sunglasses'
    });

    RNCalendarEvents.findEventById('141')
    .then(event => {
      console.warn(event);
    })
    .catch(err => {
      console.warn(err);
    });

**Comment by ArthurInTheShell** [comment]
@wmcmahan Thanks! Your help is appreciated!
