### ISSUE TITLE
Add extended properties to event

### ISSUE THREAD

**Issue by NewOldMax** [wmcmahan/react-native-calendar-events#158]
Hi,
thanks for your work with this library, it really helps 👍 

But I wonder if it possible to add [extended properties](https://developers.google.com/calendar/extended-properties) to calendar event. I don't see it in docs but you can point me if I missed it. Or maybe you plan to implement it someday

Thanks

**Comment by wmcmahan** [comment]
That could be cool! I think it could only work for Android, but maybe worth adding even if there is no parity between OS. Adding this to the list #165
