### ISSUE TITLE
Works on iOS simulator, but does not on real iOS device

### ISSUE THREAD

**Issue by sirwoetang** [wmcmahan/react-native-calendar-events#16]
Hi, 

So the calendar event creation works perfectly in the iOS simulator, but has not worked once when installing to a physical device.

Any ideas?

**Comment by wmcmahan** [comment]
Hi @sirwoetang, are you seeing any errors? Also, make sure that your application has permission to access the calendar.

**Comment by sirwoetang** [comment]
When using a time string of format : 
`"YYYY-MM-DDTHH:mm:ss.sssZ"`
 by moment it works on both simulator and phone. 
Using 
`"YYYY-MM-DD'T'HH:mm:ss.sssZ"`
It only works on the emulator.
