### ISSUE TITLE
Crash on android - 1.6.0

### ISSUE THREAD

**Issue by jeveloper** [wmcmahan/react-native-calendar-events#161]
### Environment
RN 55
lib: 1.6.0

### Steps to Reproduce
Saving details to an existing calendar event

### Actual Behavior
com.calendarevents.CalendarEvents.serializeEvent
CalendarEvents.java - line 892
java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.
android.database.CursorWindow.nativeGetString CursorWindow.java
android.database.CursorWindow.getString CursorWindow.java:451
android.database.AbstractWindowedCursor.getString AbstractWindowedCursor.java:51
android.database.CursorWrapper.getString CursorWrapper.java:137
com.calendarevents.CalendarEvents.serializeEvent CalendarEvents.java:892
com.calendarevents.CalendarEvents.findEventById CalendarEvents.java:273
com.calendarevents.CalendarEvents.access$300 CalendarEvents.java:39
com.calendarevents.CalendarEvents$4.run CalendarEvents.java:1078
java.lang.Thread.run Thread.java:764

**Comment by jeveloper** [comment]
@wmcmahan  Hey Will

Its crashing on RNCalendarEvents.findEventById(id)

Due to your recent changes using attendees.

**Comment by wmcmahan** [comment]
Thanks @jeveloper - working on getting a patch out for that soon.

**Comment by wmcmahan** [comment]
Published a fix for this in `1.6.1` - looks like there was a missing field on the cursor. Thanks for the help!
