### ISSUE TITLE
Event created in Android device shown as Birthday on Calendar and after sometime it disappears

### ISSUE THREAD

**Issue by abhichourasia** [wmcmahan/react-native-calendar-events#162]
I am creating event in Android device but the title always shown as Birthday and no notes and other fields appear like alarm or startdate and enddate on Gmail calendar.

Also the created event disappears from calendar in some seconds. This was not happening until yesterday.

`RNCalendarEvents.saveEvent('Call User', { notes: 'Test Note', description: 'Test Note', startDate: <start date>, endDate: <end date>, alarms: [ { date: 5 } ] });`

**Comment by HGendron** [comment]
You need to set the calendar id on Android or it will fallback to the default calendar which can be the birthday calendar.

This is some pseudo code:

```
const calendars = await RNCalendarEvents.findCalendars();
const primaryCalendar = calendars.find(c => c.isPrimary && c.allowsModifications);

if (!primaryCalendar) { return; }

RNCalendarEvents.saveEvent('Call User', {
    calendarId: primaryCalendar.id
    notes: 'Test Note',
    description: 'Test Note',
    startDate: <start date>,
    endDate: <end date>,
    alarms: [ { date: 5 } ]
});
```

**Comment by abhichourasia** [comment]
Yes thank you! This solves the issue for me. I was putting calendarId: 1.
