### ISSUE TITLE
Multiple crashes suddenly.

### ISSUE THREAD

**Issue by nativix** [wmcmahan/react-native-calendar-events#163]
### Environment
 OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 6.0.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 2.3 AI-162.4069837->

Hi, I've been using the module for a couple of weeks and everything was working fine until two days ago when it started crashing all over in this line:

RNCalendarEvents.m line 449
-[RNCalendarEvents serializeCalendarEvent:]

Do you have any info about what is happening?

**Comment by eladgel** [comment]
I am getting this too,
It happens in this line of code
![image](https://user-images.githubusercontent.com/412137/41219552-4c7f0908-6d67-11e8-8d14-1a52f810efe4.png)
Apparently this has been happening lately b/c the 
`event.calendar.title` is nil

**Comment by jpaas** [comment]
I have this too. It seems to have started when I upgraded to Xcode 9.4

**Comment by jpaas** [comment]
The simulator seems to have an untitled calendar. But even if I skip the ones without titles I still get a crash with the same title but a different call stack that makes it hard to track down.

**Comment by jpaas** [comment]
I did an "Erase All Content and Settings..." on my simulator and the crash no longer occurs. I also tested on a physical device and it did not occur.

**Comment by nativix** [comment]
I made a pull request in the project which would allow having an empty calendar title. 🧐

**Comment by wmcmahan** [comment]
@nativix @jpaas - Could you post the error that gets logged? It might be from recent `attendees` changes.

**Comment by jpaas** [comment]
This is not just a simulator issue. We've now seen it happen to some of our TestFlight users...
```
RCTFatalException: Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object f...
Application threw exception RCTFatalException: Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]' was thrown while invoking findCalendars on target RNCalendarEvents with params (
    3678,
    3679
)
callstack: (
	0   CoreFoundation                      0x000000018237eda4 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001815385ec objc_exception_throw + 56
	2   CoreFoundation                      0x0000000182317750 _CFArgv + 0
	3   CoreFoundation                      0x00000001822500cc <redacted> + 352
	4   CoreFoundation                      0x000000018224ff48 <redacted> + 64
	5   KarmaWorkerApp                      0x0000000100535c30 GMSx_AbslInternalSpinLockWake + 21316
	6   CoreFoundation                      0x0000000182386580 <redacted> + 144
	7   CoreFoundation                      0x0000000182265748 <redacted> + 284
	8   CoreFoundation                      0x000000018226a56c <redacted> + 60
	9   KarmaWorkerApp                      0x000000010018d7b0 _ZN5folly6detail15str_to_integralIxEENS_8ExpectedIT_NS_14ConversionCodeEEEPNS_5RangeIPKcEE + 311524
	10  KarmaWorkerApp                      0x00000001001d1b80 RCTFBQuickPerformanceLoggerConfigureHooks + 107804
	11  KarmaWorkerApp                      0x00000001001d18e0 RCTFBQuickPerformanceLoggerConfigureHooks + 107132
	12  libdispatch.dylib                   0x0000000181c70b24 <redacted> + 24
	13  libdispatch.dylib                   0x0000000181c70ae4 <redacted> + 16
	14  libdispatch.dylib                   0x0000000181c7aa38 <redacted> + 608
	15  libdispatch.dylib                   0x0000000181c7b380 <redacted> + 336
	16  libdispatch.dylib                   0x0000000181c7bd4c <redacted> + 340
	17  libdispatch.dylib                   0x0000000181c8411c <redacted> + 668
	18  libsystem_pthread.dylib             0x0000000181fa3e70 _pthread_wqthread + 860
	19  libsystem_pthread.dylib             0x0000000181fa3b08 start_wqthread + 4
): Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]:...
Originated at or in a subcall of folly::Expected<long long, folly::ConversionCode> folly::detail::str_to_integral<long long>(folly::Range<char const*>*)
mechanism
generic
mach exception
EXC_CRASH
signal
SIGABRT (code 0)
```

**Comment by wmcmahan** [comment]
Thanks @jpaas. Seems to be the same issue with nil calendar titles while calling `findCalendars`. I will push a fix out for this soon!

**Comment by wmcmahan** [comment]
A new patch is now published - `1.6.1` - please reopen if there are still issues. Thanks for the help!

**Comment by jpaas** [comment]
@wmcmahan I can confirm this did fix the problem for our beta tester. Thanks for the quick turnaround!

**Comment by TikiTDO** [comment]
@wmcmahan This issue seems to have returned, now with `objects[3]'` instead of `objects[1]'`

This appears to be the following like:

`@"source": calendar.source.title,`

I figure a similar solution to the above might work.

**Comment by qmegas** [comment]
Suddenly I started receiving similar crashes:

```
RNCalendarEvents.m line 660
attempt to insert nil object from objects[0]
```

I'm using latest version of library (1.7.3)

**Comment by tik27** [comment]
> Suddenly I started receiving similar crashes:
> 
> ```
> RNCalendarEvents.m line 660
> attempt to insert nil object from objects[0]
> ```
> 
> I'm using latest version of library (1.7.3)

I get this too, seems to be the structure location serialization when i do a fetchAll
```
 [structuredLocation addEntriesFromDictionary: @{
                                                        @"title": event.structuredLocation.title,
                                                        @"radius": @(event.structuredLocation.radius)
                                                        }];
```
