### ISSUE TITLE
Feature requests: WIP

### ISSUE THREAD

**Issue by wmcmahan** [wmcmahan/react-native-calendar-events#165]
Putting this here as a running list of desired feature requests. Always happy to hear of any others.

- [ ] Better changelog and release notes
- [x] Create calendars
- [ ] Allow recurrence rules to include weekdays
- [ ] Extended properties in Android
- [ ] Subscribe to ICS calendar
- [ ] Demo / Examples
- [ ] Create authorization status constants

**Comment by yfuks** [comment]
Hello !

Any roadmap ? :)
PR are welcome ?

**Comment by JayantJoseph** [comment]
1) Option to pass array of dates(with all the options) for creating and deleting events, so we can create/delete multiple dates without having to call it through a loop.
2) Option to pass array of exception dates, as there is no way to give more than 1 exception date now.
3) Option to pass the rrule string directly, without having to divide it into several values and passing it to several attributes.

These features would be very helpful!

**Comment by elan00** [comment]
Would it be possible to mark the event's organizer in the list of event attendees?

Thanks in advance,
Elan Benor

**Comment by elan00** [comment]
Would it be possible to mark the event's organizer in the list of event attendees?

Thanks in advance,
Elan Benor

**Comment by MoOx** [comment]
I have been added as a maintainer and I am doing some cleanup so closing this one.
Please open specific issue for feature request. Thanks.
