### ISSUE TITLE
[Question] Difference betwen this and react-native-calendar-reminders?

### ISSUE THREAD

**Issue by hegelstad** [wmcmahan/react-native-calendar-events#169]
Is this library simply an extension of react-native-calendar-reminders which adds Android support or does react-native-calendar-reminders use another underlying API only available on IOS?

I am interested in making reminders which triggers one hour before an event and counts down/stays until the event has been. Preferably the reminder should not be added to the calendar app.

Is this possible with either solution?

Best regards,
Nikolai

**Comment by wmcmahan** [comment]
The `react-native-calendar-reminders` package uses the reminders api. They are similar in design, although reminders are more like a "todo" list with the ability to set alarms.

Either one can attach an alarm to a specific time.

**Comment by ntanwir10** [comment]
Is reminder's library compatible with [react-native-calendars library](https://github.com/wix/react-native-calendars) ? What I meant is, would it possible to bind reminders from here to agenda in their ? 

thanks and regards,
Nauman.
