### ISSUE TITLE
weird RN.findCalendars() error on certain devices

### ISSUE THREAD

**Issue by MrNagoo** [wmcmahan/react-native-calendar-events#170]
Receiving Feedback about app crashes on the page using RNCE. Appears to have started in iOS 11.3.1 and 11.4 on iPhone 7 and up. Can't reproduce in simulators consistently. When the error happened it was within findCalendars(). Has anyone else experienced this?
### Steps to Reproduce

```
loadData() {
    let store, iOScalendars;
        RNCalendarEvents.findCalendars()
          .then(calendars => {
            do stuff
          })
          .catch(error => {
            console.log("err in findCalendars", error);
          });
      })
  }
```
findCalendar breaks with a null error

```attempt to insert nil object from objects[1]' was thrown while invoking findCalendars on target RNCalendarEvents with params```

### Expected Behavior

Loads phone calendars
### Actual Behavior

Crashes

**Comment by MrNagoo** [comment]
All confirmed issues (10+) of this bug are now working overnight. I did not push or change any code to the app store. This leads me to believe Apple can send hotfixes without software updates?! Is that possible?

**Comment by wmcmahan** [comment]
A patch in `1.6.1` fixed an issue with null calendar titles. Seems like maybe it got pulled in?
