### ISSUE TITLE
Attendees not added when create event

### ISSUE THREAD

**Issue by reactnative133** [wmcmahan/react-native-calendar-events#171]
RNCalendarEvents.saveEvent('eventname', {
                  calendarId: calendarId,
                  startDate: '2018-06-22T00:00:00.000Z',
                  endDate: '2018-06-23T00:00:00.000Z',
                  location: 'Los Angeles, CA',
                  notes: 'Bring sunglasses',
                  attendees: [{ "email": "test1@gmail.com", "name": "test1" }, { "email": "test2@gmail.con", "name": "test2" }],                  
                }).then((eventResponse) => {
                  console.log(eventResponse);                  
                }).catch((e) => {
                  console.log(e);              
                });

Here i passed attendees with organizer, it gives me success but attendees not added in google calendar.

**Comment by wmcmahan** [comment]
For iOS this will not be possible depending on the OS version. Adding attendees through their api is not allowed - [iOS docs](https://developer.apple.com/documentation/eventkit/ekcalendaritem/1507140-attendees?language=objc), although it has been possible in the past via a hack. I would not expect reliable results from adding attendees this way.

**Comment by gkasireddy202** [comment]
@wmcmahan - How to add the attendees for both iOS and Android?

**Comment by Jigar1308** [comment]
Hello @wmcmahan @gkasireddy202 Any solution to add attendees?
