### ISSUE TITLE
fetchAllEvents outputs [object Object]

### ISSUE THREAD

**Issue by apppro123** [wmcmahan/react-native-calendar-events#172]
Environment:
  OS: Windows 10
  Node: 8.11.2
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

I just get [object Object] for every event:

RNCalendarEvents.fetchAllEvents("2015-01-01T00:00:00.000Z", "2019-01-01T00:00:000Z")
      .then((events) =>{
        alert(events);
      });

Instead of expected array. I have already read that it returns a promise but i dont know how to convert that to an array with the information. 
I want to get the different events to to mark them in my calendar from react-native-calendars.

Thanks for every (useful :) ) response!

**Comment by wmcmahan** [comment]
Hi @apppro123, instead of using `alert`, use something like `console.log` to be able to view the array content.

**Comment by apppro123** [comment]
Hello wmcmahan

Thank you for your fast response, now it works fine.

apppro123
