### ISSUE TITLE
Native Code

### ISSUE THREAD

**Issue by apppro123** [wmcmahan/react-native-calendar-events#174]
It is more a question than an issiue but i dont know where to ask it.

So i would like to change native code of this library.
I would like to add under node-modules, react-native-calendar-events, android, src, main, com, calendarevents, CalendarEvents.java
"CalendarContract.Instances.DISPLAY_COLOR" 
in line 227 to get the color of the event.
Later i would have done that to save the event color in createEvent methode too.

With that i cannot load the app anymore.
My questions are, is it possible for me to change the code of an library at all?
and if yes does i have to consider sth in doing this? 
and if no what have i done wrong?

Thank you for Your response.
?

**Comment by apppro123** [comment]
Is there anybody who knows how i can integrate my own native code?
Or a tipp where i can find some help??

Thank you!

**Comment by wmcmahan** [comment]
Hi @apppro123, if you want to add your own code, you can fork this repo and add any code you wish. It's all open and free to use and update. If you make changes and the application will not run, there is probably an error in the code. I would recommend using an IDE that give proper compile errors when editing the Java or Objective-C code.

**Comment by apppro123** [comment]
Ok, thank you for your answer.
