### ISSUE TITLE
[iOS] Calling saveEvent with no calendarId no longer falls back to default calendar if there is more than one modifiable calendar

### ISSUE THREAD

**Issue by dkoo** [wmcmahan/react-native-calendar-events#176]
Hello,

Thanks for the library—we have been using it in a production app for some time with few issues. However, since updating to version 1.6.1 we've noticed that calling `saveEvent` without a `calendarId` can't seem to find a default calendar if the device has more than one modifiable calendar set up. The function completes without error, but also without saving the event.

### Environment
```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 7.9.0
  Yarn: 0.17.9
  npm: 4.2.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.4 => 0.48.4
```

### Steps to Reproduce
On an iOS 11.4+ device with multiple calendars set up (e.g. a Google account with multiple modifiable calendars) and v1.6.1 of this library, call `saveEvent` without any `calendarId` property.

### Expected Behavior
The event should be saved to the default calendar of the device.

### Actual Behavior
No event is saved.

**Comment by dkoo** [comment]
@ldco2016 We are still on v1.6.1, so your results may differ. But here's what we did to resolve things on our end:

1. On Android only, we found that since using SDK 23+ you need to explicitly authorize RNCalendarEvents to be able to access events with `RNCalendarEvents.authorizeEventStore()`. Hopefully this resolves the error you see on Android: https://github.com/wmcmahan/react-native-calendar-events/blob/master/README.md#authorizeeventstore
2. You should not *need* to pass a `calendarId` to the `saveEvent` method, but as outlined here, if you do and the ID is for a valid, modifiable calendar, the library will save to it: https://github.com/wmcmahan/react-native-calendar-events/blob/master/README.md#event-fields

In our issue, we found that when not passing any `calendarId` the library would sometimes silently fail, as if it couldn't determine which calendar was primary. So we added an additional check to try to determine the primary calendar manually by calling `RNCalendarEvents.findCalendars()`, then looping through all found calendars and looking for the `isPrimary` property as indicated here: https://github.com/wmcmahan/react-native-calendar-events/blob/master/README.md#calendar

If we can find a calendar with `isPrimary`, we pass the `id` as `calendarId` in each `saveEvent` call. If we can't find one, then we call `saveEvent` without a `calendarId`. Then if `saveEvent` either returns an error OR resolves but without returning an event `id` string, we assume the event creation failed and respond accordingly.

This has worked for us—hope that info helps you with your issue as well.

**Comment by ldco2016** [comment]
@dkoo ,

We are using `RNCalendarEvents.authorizeEventStore()` inside our `createCalendarEvent(event)` async helper function here:

```
export async function createCalendarEvent(event) {
  const status = await RNCalendarEvents.authorizationStatus();
  console.log(status);
  if (status === "authorized") {
    addToCalendar(event);
  } else {
    RNCalendarEvents.authorizeEventStore()
      .then(auth => {
        // handle status
        if (auth === "authorized") {
          addToCalendar(event);
        }
      })
      .catch(() => {
        alert("This app needs calendar access");
      });
  }
}
```

For some reason the `authorizationStatus()` is always `undetermined` but despite this, it appears it does eventually fire the `addToCalendar(event)` async function:

```
async function addToCalendar(event) {
  try {
    const startDate =
      Platform.OS === "ios"
        ? format(parse(event.StartDateLocal))
        : parse(event.StartDateLocal);
    const endDate =
      Platform.OS === "ios"
        ? format(parse(event.EndDateLocal))
        : parse(event.EndDateLocal);
    const allEvents = await RNCalendarEvents.fetchAllEvents(startDate, endDate);

    const calendarEvent = allEvents.find(e => e.title === event.Title);
    if (calendarEvent) {
      alert("You have already added this event to your calendar.");
    } else {
      const title = event.Title;

      const {
        Location: {
          AddressLine1: address,
          City: city,
          StateAbbreviation: state,
          PostalCode: zip
        }
      } = event;

      const location = `${address}, ${city}, ${state}, ${zip}`;

      const settings = {
        location,
        startDate,
        endDate
      };
      RNCalendarEvents.saveEvent(title, settings)
        .then(() => {
          alert("Event Saved");
        })
        .catch(rejectionReason => {
          console.log(rejectionReason);
          alert("Oops! Something has gone wrong.");
        });
    }
  } catch (e) {
    alert(e.message);
  }
}
```

And this is where the problem lies, it always catches with `Oops! Something has gone wrong` with a `rejectionReason` of `calendar has not been set`. Any ideas based on your experience or anything that sticks out to you from what I have demonstrated here?

**Comment by dkoo** [comment]
You might want to try `authorizeEventStore` _before_ checking `authorizationStatus`. I can't guarantee that's your issue, but that's how we're doing it.

**Comment by ldco2016** [comment]
@dkoo , Your guess solved it for me, you're the best!
