### ISSUE TITLE
In android while adding event is automatically deleted after sometime(30 sec approx)

### ISSUE THREAD

**Issue by phanisai4u** [wmcmahan/react-native-calendar-events#178]
Hi @wmcmahan , 
Thanks for great work, 
In android while adding event it is added as birthday and automatically deleted after sometime(30 sec approx)
## Here my code
  ```
RNCalendarEvents.saveEvent(name, {
        calendarId: '141',
        startDate: '2018-08-01T17:00:00.000Z',
        endDate: '2018-08-01T17:10:00.000Z',
        location: 'Los Angeles, CA',
        notes: 'Bring sunglasses',
        description:'Bring sunglasses',
        alarms:[{date:20}]
      }).then( obj => {
          console.log(obj);
      }) 
    }
```
Above code working perfectly in iOS but not in android.
Plese let me know if i miss something.

### Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.1.0
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

**Comment by wmcmahan** [comment]
Hi @phanisai4u, I think you might find help in this issue thread #148

**Comment by phanisai4u** [comment]
Thank you so much @wmcmahan, it perfectly worked for me
