### ISSUE TITLE
Android - event not created in calendar

### ISSUE THREAD

**Issue by tylerjjyan** [wmcmahan/react-native-calendar-events#182]
Can't seem to create event in Calendar. I get this error

08-04 01:24:54.521 5960-6602/com.android.providers.calendar E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.RuntimeException: DTSTART field missing from event
        at com.android.providers.calendar.CalendarProvider2.insertInTransactionInner(CalendarProvider2.java:2191)
        at com.android.providers.calendar.CalendarProvider2.insertInTransaction(CalendarProvider2.java:2150)
        at com.android.providers.calendar.SQLiteContentProvider.insert(SQLiteContentProvider.java:100)
        at com.android.providers.calendar.CalendarProvider2.insert(CalendarProvider2.java:2123)
        at android.content.ContentProvider$Transport.insert(ContentProvider.java:265)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:152)
        at android.os.Binder.execTransact(Binder.java:731)
### Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 9.11.1
  Yarn: 0.27.5
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Not Found
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
### Steps to Reproduce

My code: 

> const formatEvent = async (options) => {
>   const start = moment(options.startDate)
>   const end = start.add(toInteger(options.duration), 'minutes').format()
>   const location = toString(' ', [
>     options.streetAddress,
>     toString(', ', [options.city, options.state, options.zip])
>   ])
> 
>   const calendars =
>     await RNCalendarEvents.findCalendars().catch(err => console.log(err))
>   const primaryCalendar =
>     calendars.find(c => c.isPrimary && c.allowsModifications)
>   if (!primaryCalendar) {
>     return null
>   }
> 
>   return ({
>     id: options.eventId || undefined,
>     calendarId: primaryCalendar.id,
>     location,
>     notes: options.notes,
>     startDate: moment(options.startDate, 'YYYY-MM-DD HH:mm:ss').toISOString(),
>     endDate: end.toISOString()
>   })
> }
> 
> const createEvent = options =>
>   new Promise(resolve =>
>     validateAuth(
>       () => RNCalendarEvents
>         .saveEvent(options.title, formatEvent(options))
>         .then((id) => {
>           resolve({ data: { calendarEventId: id } })
>         }),
>       status => resolve({ error: true, data: { message: status } })
>     )
>   )
> 
> export default createEvent

### Expected Behavior

Event should appear in calendar
### Actual Behavior

No event in Calendar

**Comment by wmcmahan** [comment]
Hi @tylerjjyan, the exception due to trying to save with a missing or invalid `startDate` value.
