### ISSUE TITLE
Please consider adding screenshot/gif of your component to README.md

### ISSUE THREAD

**Issue by nodkz** [wmcmahan/react-native-calendar-events#189]
Please consider adding screenshot/gif of your component to README.md

It helps to gather more users. It's very complicated to find any goods components. And many users are too lazy to install and look what inside of your package. 

Thanks.

**Comment by RafaelKr** [comment]
This is no component.
The first sentence in the README.md says:  
`A React Native module to help access and save events to iOS and Android calendars.`

**Comment by nodkz** [comment]
Oops, pardon my omission
