### ISSUE TITLE
Question: calendar

### ISSUE THREAD

**Issue by apppro123** [wmcmahan/react-native-calendar-events#192]
I dont get the calendar object. What can i do with it and is it only writeable or readable. Because it says that it is only writeable but some features are only readable (color, allowedAvailabilites)!? What can i "write" with them if i cannot get them afterward from the google calendar and i also see no change at the events in the google calendar. 
Is it now also possible to make new calendars (with color...)?

Thank you for the answer!

**Comment by wmcmahan** [comment]
Sorry @apppro123 - that was a typo in the readme. The calendar property is read-only.

**Comment by apppro123** [comment]
Perfect ty very much!
