### ISSUE TITLE
Use of Private APIs

### ISSUE THREAD

**Issue by gstuart-rai** [wmcmahan/react-native-calendar-events#194]
https://github.com/wmcmahan/react-native-calendar-events/blob/a0737fe7ac2e7e3c0cf4d968a58b4052b05c0cf2/RNCalendarEvents.m#L236

The above code is a private API and will cause Apple to reject apps that use this.  Perhaps this should include some compiler flag to conditionally include this if the app being developed is internal vs. planned for app store?  Or switch to EKParticipant and remove use of this from the `saveEvent` path?

For reference, "EventKit cannot add participants to an event nor change participant information. Use the properties in this class to get information about a participant." (source: https://developer.apple.com/documentation/eventkit/ekparticipant)

**Comment by wmcmahan** [comment]
I agree @gstuart-rai, this should just be removed from the code.

**Comment by wmcmahan** [comment]
Removed in patch 1.6.4
