### ISSUE TITLE
isPrimary property missing on iOS calendar objects returned by findCalendars

### ISSUE THREAD

**Issue by WasserEsser** [wmcmahan/react-native-calendar-events#195]
The calendar property isPrimary does not seem to work on iOS despite being documented as such.
Inspecting the calendars shows that there is no such property called isPrimary.
A temporary workaround would be to check the source property for the value of "Default".

### Environment

> Environment:
>   OS: macOS High Sierra 10.13.6
>   Node: 10.10.0
>   Yarn: 1.9.4
>   npm: 6.4.1
>   Watchman: 4.9.0
>   Xcode: Xcode 9.4.1 Build version 9F2000
>   Android Studio: Not Found
> 
> Packages: (wanted => installed)
>   react: 16.4.1 => 16.4.1
>   react-native: 0.55.4 => 0.55.4

### Steps to Reproduce
Log calendar objects (findCalendars) to the console and check their properties.

### Expected Behavior
Property isPrimary to be present and set.

### Actual Behavior
Property isPrimary is missing on iOS.

This was tested on an iPhone Simulator running iOS 11.4 as well as on an iPhone running iOS 11.4.1.

This issue could be related to #176 .

**Comment by wmcmahan** [comment]
Published in patch 1.6.4
