### ISSUE TITLE
Finding event by id crash app

### ISSUE THREAD

**Issue by usmansbk** [wmcmahan/react-native-calendar-events#197]
1. I call `saveEvent()` with an id generated with the `npm uuid` package
2. `saveEvent()` resolves with an id of the added event
3. Event successfully appears in calendar
4. I call `findEventById()` with the same id
5. App force closes

### Environment
```
 npm: 6.4.1 
 Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
"react": "^16.6.0-alpha.8af6728",
"react-native": "^0.57.3",
"react-native-calendar-events": "^1.6.3",
```

### Steps to Reproduce
- App crashes when 'AddToCalendarButton' is mounted

```
  state = { 
    isSet: false,
  }

  componentDidMount = () => {
    RNCalendarEvents.authorizationStatus()
      .then((status) => {
        if (status === 'authorized') {
          RNCalendarEvents.findEventById(this.props.id)
            .then((event) => {
              if (event) {
                this.setState({
                  isSet: true
                })
              }
            });
          }
        })
  }

  _toggleCalendar = () => {
    RNCalendarEvents.authorizationStatus()
      .then(this._saveEvent)
      .catch((e) => ToastAndroid.show(e.message, ToastAndroid.SHORT))
  }

  _saveEvent = async (status) => {
    if (status === 'authorized') {
      const calendars = await RNCalendarEvents.findCalendars();
      const primaryCalendar = calendars.find(c => c.isPrimary && c.allowsModifications);
  
      if (!primaryCalendar) Promise.reject('Unable to find primary calendar!');

      const {
        id,
        title,
        startDate,
        endDate,
        description,
        notes,
        recurrence,
        location,
      } = this.props;
      return RNCalendarEvents.saveEvent(title, {
        calendarId: primaryCalendar.id,
        id,
        title,
        description,
        startDate,
        endDate,
        location,
        notes,
        recurrence
      })
      .then((id) => {
        if (id) {
          ToastAndroid.show('Added to your calendar!', ToastAndroid.SHORT);
          this.setState({
            isSet: true,
          })
        } else {
          ToastAndroid.show('Failed to add to calendar!', ToastAndroid.SHORT);
        }
        return Promise.resolve()
      });
    } else if (status === 'undetermined') {
      return RNCalendarEvents.authorizeEventStore()
        .then(this._saveEvent);
    }
    return Promise.reject('You need allow access to calendar!');
  }

  render() {
    const { isSet } = this.state;

    return (
      <Button
        type="FontAwesome"
        name={ isSet ? 'calendar-check-o' : 'calendar-plus-o'}
        onPress={this._toggleCalendar}
      />
    )
  }
```

### Expected Behavior

> **findEventById**
> Find calendar event by id. Returns a promise with fulfilled found events.
> 
> RNCalendarEvents.findEventById(id)
> Arguments:
> 
> - id: String - The events unique id.
> - Returns: Promise
> - 
> - fulfilled: Object | null - Found event with unique id.
> - rejected: Error
> - 

### Actual Behavior

App force closes with a firebase crashlytics report
```
Fatal Exception: java.lang.NumberFormatException
For input string: "3b5edabd-af81-4f2f-8c39-c12b339dac26"
com.calendarevents.CalendarEvents.findEventById
```
According the the docs:
`RNCalendarEvents.saveEvent(title, {id: 'FE6B128F-C0D8-4FB8-8FC6-D1D6BA015CDE'})`

saveEvent doesn't require a number format ID but if i pass ID as a number format the event is not added to the calendar and method does not crash the app.

**Comment by usmansbk** [comment]
Closing issue since I've figured out that the 'id' returned after saving an event is different from the one passed to during creation...

saveEvent() accepts a uuid as id and resolves to a number format string that represents the event in the calendar. 😃

**Comment by ldco2016** [comment]
@usmansbk , sorry to bother you, but I am wondering, should the the data returned from this LOC: `const calendars = await RNCalendarEvents.findCalendars();` be an empty array as far as you know?

I ask because I get an `[]` and I was looking for confirmation whether this is what it should be returning.

**Comment by usmansbk** [comment]
@ldco2016 No. The array should contain a list of calendar apps on your phone. At least there should be the default calendar app in there.

**Comment by ldco2016** [comment]
@usmansbk , thank you for clearing that up. That helped me understand that my emulator did not have a calendar installed. I went ahead and installed Google calendar. The good news is I no longer get an empty array, I get an object containing the following:

```
2019-11-11 19:52:56.570 15316-15424/com.nfibengage.dv I/ReactNativeJS: 'this is from components-helper primaryCalendar var: ', { allowsModifications: true,
      isPrimary: true,
      type: 'com.google',
      allowedAvailabilities: [ 'busy', 'free' ],
      source: 'user@github.com',
      title: 'user@github.com',
      id: '3' }
```

The bad news is that its followed by this error:

```
2019-11-11 22:53:55.444 21302-21586/com.nfibengage.dv I/ReactNativeJS: { [Error: Unable to save event]
      framesToPop: 1,
      nativeStackAndroid: [],
      userInfo: null,
      code: 'add event error',
      line: 1740,
      column: 26,
      sourceURL: 'http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false' }
```

Is there anything you see there that explains why I am still getting an error on saving an event to the calendar?

**Comment by usmansbk** [comment]
Try adding the calendarId to the settings:
```
      const settings = {
       calendarId: primaryCalendar.id,
        location,
        startDate,
        endDate
      };
```

**Comment by ldco2016** [comment]
@usmansbk , I get an alert with the message: `Can't find variable: primaryCalendar`.

**Comment by usmansbk** [comment]
@ldco2016 you have to raise the scope of the primaryCalendar. So that it's accessible.

**Comment by ldco2016** [comment]
@usmansbk , good point, its tricky, I tried adding a `let idInfo;` outside of `if` conditional, I tried a `return` statement.
