### ISSUE TITLE
location doesn't work 

### ISSUE THREAD

**Issue by chalyi-andrei** [wmcmahan/react-native-calendar-events#200]
I need to add a location to the calendar. But it does not work. I add a string but the preview is not shown. If you take the same string to add yourself in the calendar, then there is a preview.

<img width="372" alt="1" src="https://user-images.githubusercontent.com/23151557/47569413-409b8800-d93c-11e8-928e-07833d76902a.png">

<img width="372" alt="3" src="https://user-images.githubusercontent.com/23151557/47569566-953f0300-d93c-11e8-9804-4858ffbf03eb.png">

### Environment
Macbooc Pro 2017, os x mojave.

### Steps to Reproduce
```javascript
   const settings = {
        ...
        location = "1 Stockton St San Francisco CA 94108 United States", 
   };

     RNCalendarEvents.saveEvent(title, settings)
```

### Expected Behavior
According to the documentation, the location accepts a string, and should add a preview.

### Actual Behavior
Adds a string without a preview.

**Comment by wmcmahan** [comment]
Ah yes, iOS will need structured location values (similar to the alarm settings). This is not currently supported, but it would be nice to add it in. I will work on a solution for this.

**Comment by wmcmahan** [comment]
Added in #221
