### ISSUE TITLE
Wrong buildToolsVersion, compileSdkVersion and targetSdkVersion

### ISSUE THREAD

**Issue by xander9112** [wmcmahan/react-native-calendar-events#202]
### Environment
 System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
      Memory: 3.64 GB / 15.91 GB
    Binaries:
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.4 - C:\Users\afurmanchuk\AppData\Local\Android\Sdk\watchman\watchman.EXE
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246

### Steps to Reproduce
I'm trying to build apk and getting an error:

> error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
C:\Users\afurmanchuk\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\63d1c290a65cf836cc54be9af23cc002\res\values-v26\values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.

> C:\Users\afurmanchuk\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\63d1c290a65cf836cc54be9af23cc002\res\values-v26\values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.

> C:\Users\afurmanchuk\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\63d1c290a65cf836cc54be9af23cc002\res\values-v26\values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.

> C:\Users\afurmanchuk\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\63d1c290a65cf836cc54be9af23cc002\res\values\values.xml:251:5-69: AAPT: error: resource android:attr/fontStyle not found.

> C:\Users\afurmanchuk\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\63d1c290a65cf836cc54be9af23cc002\res\values\values.xml:251:5-69: AAPT: error: resource android:attr/font not found.

> C:\Users\afurmanchuk\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\63d1c290a65cf836cc54be9af23cc002\res\values\values.xml:251:5-69: AAPT: error: resource android:attr/fontWeight not found.

> error: failed linking references.

> FAILURE: Build failed with an exception.

> * What went wrong:
Execution failed for task ':react-native-calendar-events:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

But when I change in node_modules/react-native-calendar-events/android/build.gradle
compileSdkVersion 23 to **27**
buildToolsVersion "23.0.1" to **"27.0.3"**
targetSdkVersion 22 to **26**

Everything build.

**Comment by ycman0307** [comment]
+1 , same issue

**Comment by mounlion** [comment]
+1

**Comment by shardick** [comment]
+1

**Comment by bluenex** [comment]
There is a [PR](https://github.com/wmcmahan/react-native-calendar-events/pull/183/files) since August, unfortunately it isn't merged yet :(

**Comment by wmcmahan** [comment]
Now published in patch 1.6.4
