### ISSUE TITLE
requiresMainQueueSetup possible outdate npm package

### ISSUE THREAD

**Issue by GavinThomas1192** [wmcmahan/react-native-calendar-events#203]
After installing this package with yarn from npm on IOS and doing a test run of the functionality I receive a yellow box console warning. 
"Module RNCalendarEvents requires main queue setup since it overrides 'init' but doesn't implement 'requiresMainQueueSetup'.
<img width="439" alt="screen shot 2018-11-19 at 6 45 55 am" src="https://user-images.githubusercontent.com/28162527/48714276-32e9c300-ebc7-11e8-92c2-5baa8c329950.png">

It would appear that this problem has been addressed as I see the fix within https://github.com/wmcmahan/react-native-calendar-events/blob/master/RNCalendarEvents.m .

Is it possible the package is out of date on npm? I can fix this issue by adding it to my RNCalendarEvents.m .

### Environment

 React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 81.20 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0
        API Levels: 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2
### Steps to Reproduce

Install package. 
RN Link
Manually add RNCalendarEvents.m to xcode. 

### Expected Behavior

I except no yellow box warnings.
### Actual Behavior

I see yellow box warnings.

**Comment by wmcmahan** [comment]
Now published in patch 1.6.4
