### ISSUE TITLE
Permission for a pull request: Add more options to the recurrenceRule object

### ISSUE THREAD

**Issue by rex-legorreta** [wmcmahan/react-native-calendar-events#208]
Hi, I want to be able to merge my changes to your library.

What I developed is this, regarding the **recurrenceRule** and is able for Android and iOS:

- Add an array with the days of the week (**daysOfWeek**): This is used for creating a weekly recurring event that is repeated on specific days of the week, also it's used for create a monthly custom recurring event that start on a specific day of the month along with the week position in month

- Add the start day of the week (only for android, **weekStart**): it's used to specify the start day of the week

- Add the week position in month (**weekPositionInMonth**): It's used for creating a monthly recurring event that starts on a specific week of the month

I hope I can get a quick response and know if I'm able to do it or if I can handle over to you the modified files in order to be merged.

At the end the new recurrenceRule object would look like this:

**`recurrenceRule = {
	"duration": null,    
	"frequency": "weekly",    
	"endDate": "<string>",
	"interval": 1,
	"weekStart": "MO",
	"daysOfWeek": ["MO", "TU", "WE", "TH", "FR", "SA", "SU"],
	"weekPositionInMonth": 3
}`**

Thank you for this amazing library!

**Comment by wmcmahan** [comment]
Yes, that would be a great addition. Pull requests are always welcome
