### ISSUE TITLE
RNCalendarEvents is undefined

### ISSUE THREAD

**Issue by paulwithap** [wmcmahan/react-native-calendar-events#21]
Using React-Native v0.33.0

After running `import RNCalendarEvents from 'react-native-calendar-events';`, RNCalendarEvents is undefined.

**Comment by wmcmahan** [comment]
Did you link the library? https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by paulwithap** [comment]
Working now. I'm not sure what fixed it, but I think it was a common React-Native issue, fixed by deleting and reinstalling npm modules.

**Comment by paulwithap** [comment]
I am seeing this now, though:

This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data.

I can open a new issue for that if you'd like.

**Comment by wmcmahan** [comment]
Yeah, looks like it might be specific to IOS 10? But yes, I will update the README about `Info.plist` key value would definitely help. Thanks

**Comment by vTrip** [comment]
Hi @paulwithap @wmcmahan I have that iOS10 specific issue with the app's info.plist - I went into Xcode and added 'Privacy - Calendars Usage Description' key with string value '$(PRODUCT_NAME)'

This was done after doing 'react-native link' after installing the module via npm.

I closed down all react-native processes and restarted them to ensure the module was present and linked but still couldn't get it working.

Any thoughts ?
