### ISSUE TITLE
 unable to open database file

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [wmcmahan/react-native-calendar-events#212]
native:android.database.sqlite.SQLiteException: unable to open database file (code 14) at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:181) at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137) at android.content.ContentProviderProxy.query(ContentProviderNative.java:421) at android.content.ContentResolver.query(ContentResolver.java:488) at android.content.ContentResolver.query(ContentResolver.java:428) at com.calendarevents.CalendarEvents.findAttendeesByEventId(Unknown Source) at com.calendarevents.CalendarEvents.serializeEvent(Unknown Source) at com.calendarevents.CalendarEvents.findEventById(Unknown Source) at com.calendarevents.CalendarEvents.addEvent(Unknown Source) at com.calendarevents.CalendarEvents.access$100(Unknown Source) at com.calendarevents.CalendarEvents$2.run(Unknown Source) at java.lang.Thread.run(Thread.java:818)

### Environment

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 206.86 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 16, 19, 21, 23, 24, 25, 26, 27
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3
        System Images: android-19 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-24 | Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.7 => 0.57.7
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

### Steps to Reproduce

Capture it through Google analytics

**Comment by Darkhorse-Fraternity** [comment]
native:java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getCount()' on a null object reference at com.calendarevents.CalendarEvents.findEventById(Unknown Source) at com.calendarevents.CalendarEvents.addEvent(Unknown Source) at com.calendarevents.CalendarEvents.access$100(Unknown Source) at com.calendarevents.CalendarEvents$2.run(Unknown Source) at java.lang.Thread.run(Thread.java:818)

**Comment by rex-legorreta** [comment]
I had this same issue when fetching events and my solution was to remove the reminders and the attendees (I don't need them anyways) and add try catch to some cursor function executions

for example in private WritableNativeArray serializeEvents(Cursor cursor)... 
` try {
                while (cursor.moveToNext()) {
                    results.pushMap(serializeEvent(cursor));
                }
            } catch( Exception error) {
                Log.e(">>>>>>>> ERRROR ", error.toString());
            } finally {
                cursor.close();
            }`

**Comment by MoOx** [comment]
@Darkhorse-Fraternity did you handled permissions first?

**Comment by Darkhorse-Fraternity** [comment]
> @Darkhorse-Fraternity did you handled permissions first?
Yes，Now that I've switched to typescript, I've found that the previous type is wrong。
