### ISSUE TITLE
Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:react-native-calendar-events] /Users/tu/Desktop/HomePage/homepage-mobile/node_modules/react-native-calendar-events/android/build/intermediates/manifests/full/debug/AndroidManifest.xml as the library might be using APIs not available in 16

### ISSUE THREAD

**Issue by tunm1228** [wmcmahan/react-native-calendar-events#213]

**Comment by padvlad** [comment]
This issue has been introduced in https://github.com/wmcmahan/react-native-calendar-events/pull/183. One of the reviews did raise a warning about the unnecessary change of `minSdkVersion`, but this has been ignored apparently.

**Comment by FonDorn** [comment]
You also can add to **build.gradle** file next code:
```
ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 19
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}
```

**Comment by padvlad** [comment]
@FonDorn Yes you could, but this would mean only supporting devices that run on SDK 19 or newer. The whole issue in my opinion is that this library removed the support for older SDK's with no apparent reason (and that lack of a reason is the main issue). For an app that is in production and already supports older phones this would mean some users (even if they are just a few of them) would loose support for future updates.

**Comment by wmcmahan** [comment]
Apologies, this was an unintentional change. A fix will be pushed to support lower SDKs in the next release. 👍
