### ISSUE TITLE
Inserting New Calendars

### ISSUE THREAD

**Issue by tyricec** [wmcmahan/react-native-calendar-events#216]
Hello. I was wondering if adding a feature of inserting calendars would be of interest. I have a requirement at my job to insert a calendar on the device and will start working on it. Was just wondering if I should make it a separate package or fork this repository and create a PR. My concern is that it seems that the intention of this repository is to only manage events and not calendars, so it would be weird to have this feature included in the API.

**Comment by wmcmahan** [comment]
You may be in luck. A PR #214 was just created for creating calendars.

**Comment by tyricec** [comment]
Cool. I will close this issue then. Didn't notice the related issues for it. Thanks.
