### ISSUE TITLE
Unable to update single event in reccurent serie

### ISSUE THREAD

**Issue by davidbonan** [wmcmahan/react-native-calendar-events#218]
### Environment
System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 22.73 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 25, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.8.1 
      react-native: 0.58.4 => 0.58.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

### Steps to Reproduce
Try to edit one event in serie but not the first one. When i update the first event of serie, that work.

### Actual Behavior
An error appear : the date start must before the date end

**Comment by wmcmahan** [comment]
You will need to specify an [exceptionDate](https://github.com/wmcmahan/react-native-calendar-events#options) that is not before your "endDate"
