### ISSUE TITLE
Can we get event id's in fetchAllEvents

### ISSUE THREAD

**Issue by chakrihacker** [wmcmahan/react-native-calendar-events#219]
fetchAllEvents returns events in a time range, but event id is not associated with it. It's good to return event id

I can help you if there is a way of getting the event id's

**Comment by wmcmahan** [comment]
@chakrihacker There should be an event id associated with the event. The event id is created and returned from the devices store.

**Comment by chakrihacker** [comment]
Hey sorry for that question, I was confused with calendar id and event id. When I was testing I used calendar id to get event data. Solved it, forgot to close. Thanks for making this library
