### ISSUE TITLE
Has calendarEventsChanged event been removed on 1.0.0 or later?

### ISSUE THREAD

**Issue by miyabi** [wmcmahan/react-native-calendar-events#22]
We need it.

**Comment by wmcmahan** [comment]
@miyabi, yes from 1.0.0 and up, we are using promises instead of event listeners.

**Comment by miyabi** [comment]
@wmcmahan I understand it, however, how do I receive the changes of calendar from outside of my app?
Now on 0.1.6, I use calendarEventsChanged to synchronize calendar events when my app becomes foreground like this:

```jsx
  componentDidMount() {
    this.calendarEventsChangedEvent = NativeAppEventEmitter.addListener(
      'calendarEventsChanged', 
      this.onCalendarEventsChanged.bind(this)
    )
  }

  onCalendarEventsChanged() {
    const { myEvent, calendarIdsForMyEvent } = this.props

    const myEventId = myEvent.id
    const calendarId = calendarIdsForMyEvent[myEventId]
    const startDate = myEvent.start
    const endDate = myEvent.end

    RNCalendarEvents.fetchAllEvents(startDate, endDate, (calendarEvents) => {
      if (!calendarEvents.find(item => item.id == calendarId)) {
        delete calendarIdsForMyEvent[myEventId]
      }
    })
  }
```

**Comment by wmcmahan** [comment]
Thanks @miyabi, I understand now.

If you are wanting to create a module to handle notifications when the EventStore changes, there is an fairly simple way to create a module for it. Here is a [gist](https://gist.github.com/wmcmahan/91bef2d1961e5349167d46b19fa174f8) which might help.

If this would be helpful to have in this project, I can definitely include it. I just thought that it might be better to separate out the notification business from the calendar api.

**Comment by miyabi** [comment]
Thank you @wmcmahan , the gist code works fine!

Including notification functionality into this project is convenient for me, but I understand the advantage of the separation you said.
