### ISSUE TITLE
Removing calendar event disappears and then returns

### ISSUE THREAD

**Issue by jeveloper** [wmcmahan/react-native-calendar-events#224]
Simple

Google Pixel 1 device, removing event , calendar appears empty, 10 seconds later the same event is back.

No idea. It's not happening on ios or Samsung S7 8.0

**Comment by MoOx** [comment]
This might be a sync problem (see https://github.com/wmcmahan/react-native-calendar-events#troubleshooting). Without more information or an easy way to reproduce 100% of the time, we cannot help that much.
