### ISSUE TITLE
Build Error: verifyReleaseResources FAILED (with solution)

### ISSUE THREAD

**Issue by gunnartorfis** [wmcmahan/react-native-calendar-events#226]
When trying to build a release artifact on Android, using ./gradlew assembleRelease, I get the error linked under "Actual Behavior". 

### Environment
`
 React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
      Memory: 564.40 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-27 | Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.3 => 0.58.3
    npmGlobalPackages:
      eslint-plugin-react-native: 3.6.0
      react-native-git-upgrade: 0.2.7
`

### Steps to Reproduce
From the project root:
```
cd android
./gradlew assembleRelease
```

### Expected Behavior
Build is supposed to be successful.

### Actual Behavior
```
> Task :react-native-calendar-events:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-calendar-events:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output: myProject/node_modules/react-native-calendar-events/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
 myProject/node_modules/react-native-calendar-events/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  myProject/node_modules/react-native-calendar-events/android/build/intermediates/res/merged/release/values/values.xml:957: error: resource android:attr/fontVariationSettings not found.
  myProject/node_modules/react-native-calendar-events/android/build/intermediates/res/merged/release/values/values.xml:958: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

### Solution
The following build.gradle for react-native-calendar-events solves this problem:
```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

    }
    lintOptions {
       warning 'InvalidPackage'
    }
}

dependencies {
    api 'com.facebook.react:react-native:+'
}

```

**Comment by jpaas** [comment]
Also hitting this issue with RN 0.58. Looks like the `build.gradle` needs to be updated again.

**Comment by kentapolis** [comment]
Running into a similar issue,

```
> Task :react-native-restart:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-restart:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/kentkawahara/Documents/irvine-company/apartment/node_modules/react-native-restart/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/kentkawahara/Documents/irvine-company/apartment/node_modules/react-native-restart/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/kentkawahara/Documents/irvine-company/apartment/node_modules/react-native-restart/android/build/intermediates/res/merged/release/values/values.xml:2714: error: resource android:attr/fontVariationSettings not found.
  /Users/kentkawahara/Documents/irvine-company/apartment/node_modules/react-native-restart/android/build/intermediates/res/merged/release/values/values.xml:2715: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

Any pointers would be greatly appreciated

**Comment by gunnartorfis** [comment]
@kentapolis For now, you can manually edit the build.gradle (for the react-native-calendar-events package) file to match the solution I provided in the original post. 

This does of course not work if you're using some CI/CD tool like AppCenter, but then you'd have to manually build the APK from Android Studio and upload it.
