### ISSUE TITLE
NullPointerException (@CalendarEvents:createRemindersForEvent:-1)

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [wmcmahan/react-native-calendar-events#227]
NullPointerException (@CalendarEvents:createRemindersForEvent:-1) {Thread-2483}
### Environment

eact Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 60.42 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 16, 19, 21, 23, 24, 25, 26, 27
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3
        System Images: android-19 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-24 | Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.7 => 0.57.7
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
### Actual Behavior

"react-native-calendar-events": "^1.7.0",

**Comment by lakhman** [comment]
I have a similar environment to Darkhorse-Fraternity and I am also getting this error (using version 1.6.4 of this library on android.

Here's my crashlytics report.

```
Fatal Exception: android.database.sqlite.SQLiteException
--
  | android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:179)
  | android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:135)
  | android.content.ContentProviderProxy.insert (ContentProviderNative.java:476)
  | android.content.ContentResolver.insert (ContentResolver.java:1539)
  | com.calendarevents.CalendarEvents.createRemindersForEvent (CalendarEvents.java:702)
  | com.calendarevents.CalendarEvents.addEvent (CalendarEvents.java:551)
  | com.calendarevents.CalendarEvents.access$100 (CalendarEvents.java:39)
  | com.calendarevents.CalendarEvents$2.run (CalendarEvents.java:1052)
  | java.lang.Thread.run (Thread.java:764)
```

I think one of the parameters for the call to `createRemindersForEvent` is sometimes being passed as null, possibly the eventId.

https://github.com/wmcmahan/react-native-calendar-events/blob/master/android/src/main/java/com/calendarevents/CalendarEvents.java#L622

https://github.com/wmcmahan/react-native-calendar-events/blob/master/android/src/main/java/com/calendarevents/CalendarEvents.java#L662

I can't seem to replicate why it's null using the library but it seems to be effecting a number of our users (I can see through crashlytics).

@wmcmahan Do you think a `details.hasKey("id")` check would fix this? (assuming it's coming from line 622) or any other ideas for a fix or to help debug?

**Comment by star-heng** [comment]
me to

**Comment by stereodenis** [comment]
![image](https://user-images.githubusercontent.com/1406461/75230949-acf2f980-57c5-11ea-894f-d26cbd62c9cc.png)

**Comment by MoOx** [comment]
Please reopen with a proper way to reproduce the issue (code to reproduce).
