### ISSUE TITLE
timezone problems

### ISSUE THREAD

**Issue by apppro123** [wmcmahan/react-native-calendar-events#229]
I have still problems with timezone. When i set an string with Moment().toISOString() it does not use the timezone and so set it false in the google calendar.
I have the same problems with .utc() and .values() but i dont know why?
Google calendar and Moment does use the same timezone, but somehow it converts the timezone while saving the event at google calendar and google calendar takes the "false" (iso) timezone as its timezone and thinks it is the right.

If you have further questions on the issue pls write it!

Thank you for any help!

**Comment by jake41** [comment]
same issue!!
