### ISSUE TITLE
Date format failing on android. 

### ISSUE THREAD

**Issue by jake41** [wmcmahan/react-native-calendar-events#232]
AppointmentStartDate: 2019-03-23T13:52:03.033+05:30 
AppointmentEndDate: 2019-03-23T14:12:03.033+05:30

The above date works in ios, but not in android. Getting the below error in android: 

Error : Error: Unparseable date: "2019-03-23T14:02:15.1515+05:30"

**Comment by jake41** [comment]
This is working after I changed format to "YYYY-MM-DDTHH:mm:ss.sss[Z]" from "YYYY-MM-DDTHH:mm:ss.sssZ"

**Comment by jake41** [comment]
I am unable to get correct time after removing timezone, Can some one tell what is the correct date format to use in android and ios for react-native-calendar-events ?

Thanks

**Comment by wmcmahan** [comment]
You can send a date string or timestamp. Ex: "2019-04-07T10:00:00.500Z"
