### ISSUE TITLE
Unable to see event in GoogleCalendar

### ISSUE THREAD

**Issue by jake41** [wmcmahan/react-native-calendar-events#233]
On saveEvent . I am getting success back with calendarid as follows: 

Added appointment to Calendar. 
CalendarEventID: 270  

But I am unable to view the event in Google Calendar .

**Comment by ahtesham-shah** [comment]
Firstly its showing event but after some time its automatically getting disappear. Please help to solve this problem. This problem is happening only on google calendar working properly on other calendars.

**Comment by pangCP** [comment]
Hey was getting the same Google Calendar issues, and pretty sure the reason is this: https://stackoverflow.com/a/45499411

I tried passing in a calendar ID like this:
``` 
RNCalendarEvents.saveEvent(title, {
          calendarId: Platform.OS === 'android' ? "3" : undefined
        })
```
which kept the event from disappearing.

Ideally CalendarEvents.java adds a version check and defaults to 3 instead of 1.

**Comment by pangCP** [comment]
Actually, that still wasn't working for me. The comment here where you find the primary calendar and use it's ID finally fixed it: https://github.com/wmcmahan/react-native-calendar-events/issues/265

**Comment by MoOx** [comment]
Please have a look to https://github.com/wmcmahan/react-native-calendar-events#troubleshooting
