### ISSUE TITLE
App crashes on ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by eladgel** [wmcmahan/react-native-calendar-events#236]
Line pointing towards crashing line
![image](https://user-images.githubusercontent.com/412137/55288779-44d54100-53c5-11e9-8c27-53077ce569ad.png)

### Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 58.88 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      npm: 6.8.0 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.7.0-alpha.2 => 16.7.0-alpha.2 
      react-native: ^0.57.7 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

### Steps to Reproduce
`RNCalendarEvents.fetchAllEvents(startDate,endDate,[])`

### Expected Behavior
No crash

### Actual Behavior
java code crashed on the following reason in Android

> Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
> length=1; index=1

Android version 9
Android device SM-G965U

**Comment by MoOx** [comment]
Closed by https://github.com/wmcmahan/react-native-calendar-events/commit/d4191005591738f47513b524fd7131b57bd256a0
