### ISSUE TITLE
fetchAllEvents is very slow

### ISSUE THREAD

**Issue by qmegas** [wmcmahan/react-native-calendar-events#237]
Hi,

Why `fetchAllEvents` function is so slow?
I'm trying to fetch all events in my calendar from current day to one year ahead, and it takes on my Samsung Galaxy S6 about **25-32 seconds**! I understand that it can be about 300-400 records to fetch, but still it shouldn't take so much time. Is there place for optimization?

**Comment by MoOx** [comment]
Does the improvement discussed in #251 will help you?

**Comment by MoOx** [comment]
See #351 for incoming solutions. Meanwhile, you can edit .m & .java file of this module to comment things you don't want to have to benefit of a performance boost. You can use `patch-package` (lib on npm) to commit your change to the lib in your project to keep this versioned until we ship our solution.
