### ISSUE TITLE
Unable to save a calendar using example in #214

### ISSUE THREAD

**Issue by sa2812** [wmcmahan/react-native-calendar-events#239]
Following the instructions laid out in #214, I am encountering an error when attempting to create a calendar.

I have adapted the code to create a new event like so:

```javascript
let existingCalendars = await RNCalendarEvents.findCalendars()

const calendar = {
  title: 'My Calendar',
  color: '#424242',
  entityType: 'event',
  source: {
      name: result[0].source,
      type: result[0].type,
  },
  name: 'My Name',
  accessLevel: 'owner',
  ownerAccount: result[0].source,
};

let myCal = await RNCalendarEvents.saveCalendar(calendar)
```

I then receive the following error message when running this code:

```
Error: no source found to create the calendar (local & icloud)
```

I'm not sure how sources work, but is there any additional configuration I need in my code for this to work?

Edit: The above code works on Android, but not on iOS

**Comment by yfuks** [comment]
Hello @sa2812 

make sure that `RNCalendarEvents.findCalendars()` return something.
You can also check that there is a calendar configured on your iOS.

**Comment by sa2812** [comment]
Thanks @yfuks - turns out it was an issue with the phone on my iOS simulator. I had no issues with a real device
