### ISSUE TITLE
Alert to notify user that the event has been added

### ISSUE THREAD

**Issue by IronTony** [wmcmahan/react-native-calendar-events#24]
Hi, thank you for the component.
Is there a way to show the user an alert modal confirming that the event has been added successfully to the calendar? And also a modal to say to the user, "Do you want to see the event added in the the caledar?" Yes/No

Thank you in advance

**Comment by wmcmahan** [comment]
@IronTony, you can render a [modal](https://facebook.github.io/react-native/docs/modal.html) when `saveEvent`'s promise resolves.

**Comment by IronTony** [comment]
Ahhh me noob. You are right.
Thank you very much to have opened my eyes +1

**Comment by wmcmahan** [comment]
Great! Glad that helped.
