### ISSUE TITLE
Compile RNCalendarEvents.m fatal error: 'YGValue.h' file not found

### ISSUE THREAD

**Issue by Hanums** [wmcmahan/react-native-calendar-events#240]
Showing Recent Errors Only

Build target react-native-calendar-events of project Pods with configuration Debug

In file included from /Users/<user>/Test/reactnative/node_modules/react-native-calendar-events/RNCalendarEvents.m:2:

In file included from /Users/<user>/Test/reactnative/ios/Pods/Headers/Public/React/React/RCTConvert.h:17:
/Users/<user>/Test/reactnative/ios/Pods/Headers/Private/yoga/Yoga.h:22:10: fatal error: 'YGValue.h' file not found
#include "YGValue.h"
         ^~~~~~~~~~~
1 error generated.

### Environment

info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (24) x64 Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
      Memory: 47.81 GB / 64.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.0
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.3.1 => 16.3.1 
      react-native: ^0.59.3 => 0.59.3 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-input-mask: 1.0.0
      react-native-windows: 0.57.0-rc.0
      react-native: 0.57.8

### Steps to Reproduce

Run - XCode  Build

### Expected Behavior

Compile, Build and open app in iPhone simulator

### Actual Behavior

Error as shown in description

**Comment by wmcmahan** [comment]
YGValue.h is not a header file in the library. Looks to be coming from another file
