### ISSUE TITLE
[ANDROID] Unable to provide response for "authorizeEventStore" method.

### ISSUE THREAD

**Issue by gourav-singhal** [wmcmahan/react-native-calendar-events#241]
Unable to provide response for "authorizeEventStore" method.

As soon as I call this method a popup for user permission is displayed and the app crashes as soon as the user provides the response (either deny / allow).

Please suggest any solution or any other information required to track this issue. 

### Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 38.06 MB / 12.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 27
        Build Tools: 27.0.3, 28.0.3
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-fetch-blob: 0.10.8
      react-native-mail: 3.0.6

### Actual Behavior
App crashes everytime on user response but only when a fresh copy of app is installed i.e for the first time from next time it works as expected.

**Comment by gourav-singhal** [comment]
I have tested the crash is there on Android 8.0 as well as android 9.0

**Comment by tobikars** [comment]
We are having the same issue, authorizeEventStore method does not return a promise (result or error), app just crashes.

**Comment by jake41** [comment]
```addToCalendar = async () => {
    console.log("Invoking addToCalendar function");
    try {
      //check for authorization status
      let getStatus = await RNCalendarEvents.authorizationStatus();
      let authorizeStatus = "";
      if (getStatus === "authorized") {
        console.log("Authorized to make the calendar call");
        authorizeStatus = "authorized";
      } else {
        //request for calendar access
        console.log("Not authorized to make the calendar call");
        authorizeStatus = await RNCalendarEvents.authorizeEventStore();
      }
      //if permission granted enter
      if (authorizeStatus == "authorized") {
        sDate = moment().toISOString();
        eDate = moment(sDate)
          .add(20, "minutes")
          .toISOString();
        try {
          //add event to calendar
          let addCalendar = await RNCalendarEvents.saveEvent(
            "Store Appointment",
            {
              startDate: `${sDate}`,
              endDate: `${eDate}`
            }
          );
          await this.setState({
            message: "Event added to calendar!"
          });
          console.log("Event added to calendar");
        } catch (err) {
          console.log(`Error in CalendarSaveEvent: ${err}`);
        }
      }
    } catch (err) {
      console.log(`Error in CalendarAuthorizationStatus : ${err}`);
    }```

Once RNCalendarEvents.authorizeEventStore(); is called the control is not going to the next line. I am not observing the app crash. But control is going out of the app I would say. 

Impact: 
When add to calendar is invoked for the very first time, permission popup comes up and if I click allow save event should invoke, but now since control is going out saveEvent is not being called. 

From the second time onwards since calendar authorisation is done, RNCalendarEvents.authorizeEventStore();  is not called and save event is getting invoked. 

Please help!

**Comment by jake41** [comment]
@wmcmahan  can you have a look

**Comment by jake41** [comment]
@gourav-singhal  @tobikars  any workarounds found ?

**Comment by gourav-singhal** [comment]
@jake41 I got the workaround for now.

Instead of using the 'authorizeEventStatus' and 'authorizeEventStore' from the library for android I am using the below code:-

checkForCalendarPermissionAndroid = async (date) => {
    try {
      const hasWritePermission = await PermissionsAndroid.check(
        PermissionsAndroid.PERMISSIONS.WRITE_CALENDAR,
      );

      const hasReadPermission = await PermissionsAndroid.check(
        PermissionsAndroid.PERMISSIONS.READ_CALENDAR,
      );

      if (hasWritePermission && hasReadPermission) {
        this.saveEventToCalendar(date);
      } else {
        this.requestCalendarPermission(date);
      }
    } catch(error) {
    }
  }

And again in 'requestCalendarPermission' instead of 'authorizeEventStore' use inbuilt RN PermissionsAndroid API.

**Comment by jake41** [comment]
@gourav-singhal thankyou, will try and let you know :)

**Comment by 57912130** [comment]
I have the same problem.

**Comment by gourav-singhal** [comment]
@57912130 you can try the above workaround.

**Comment by gourav-singhal** [comment]
@jake41 I hope the workaround worked for you

**Comment by simonfranzen** [comment]
Oh I have commented on this issue here https://github.com/wmcmahan/react-native-calendar-events/issues/107 but I think this is the the same?

I will try the workaround for Android

**Comment by MoOx** [comment]
Could you try 2.0.0 & check if situation is better? Please reopen an issue if necessary. Thanks!
