### ISSUE TITLE
Not working as per recurrenceRule rule

### ISSUE THREAD

**Issue by mohbasheer** [wmcmahan/react-native-calendar-events#242]
### Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 26.00 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-26 | Android TV Intel x86 Atom, android-26 | China version of Android Wear Intel x86 Atom, android-26 | Android Wear Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.7 => 0.57.7
    npmGlobalPackages:
      react-native-cli: 2.0.1

### IOS Stimulator info
Version 10.1 (SimulatorApp-877 CoreSimulator-581.2)

### Steps to Reproduce

import RNCalendarEvents, { RecurrenceRule } from "react-native-calendar-events";

RNCalendarEvents.saveEvent("Weekly gap 2", {
			startDate: "2019-04-26T19:26:00.000Z",
			endDate: "2019-07-26T19:26:00.000Z",
			recurrenceRule: {
				frequency: "weekly",
				occurrence: 3,
				interval: 0,
				endDate: "2019-07-26T19:26:00.000Z",
			},
		});

### Expected Behavior
Should add below Events
1) 2019-04-26
2) 2019-05-03
3) 2019-05-10

### Actual Behavior
It's added the event daily. From 2019-04-26 to 2019-10-27

![Screenshot 2019-04-26 at 11 47 49 AM](https://user-images.githubusercontent.com/4498791/56782312-283bf580-6819-11e9-8d42-7a44900e1740.png)

**Comment by wmcmahan** [comment]
Hi @mohbasheer, don't give the endDate for the recurrence rule and only use the occurrence property. Ex:
```
RNCalendarEvents.saveEvent("Weekly gap 2", {
  startDate: "2019-04-26T19:26:00.000Z",
  recurrenceRule: {
    frequency: "weekly",
    occurrence: 3
  }
});
```

**Comment by mohbasheer** [comment]
Hi,

End date is not optional, I am using latest version of react-native-calendar-events. Please check the attached errors.

RNCalendarEvents.saveEvent("Weekly gap 2", {
			startDate: "2019-04-28T19:26:00.000Z",
			recurrenceRule: {
				frequency: "weekly",
				occurrence: 3,
			},
		});


<img width="1440" alt="Screenshot 2019-04-28 at 12 15 54 PM" src="https://user-images.githubusercontent.com/4498791/56858614-99151600-69af-11e9-9e36-4262f91b627c.png">

**Comment by MoOx** [comment]
Your example that doesn't work have no endDate for the event itself. event endDate != reccurenceRule endDate.
