### ISSUE TITLE
Violation of Personal and Sensitive Information policy

### ISSUE THREAD

**Issue by humarkx** [wmcmahan/react-native-calendar-events#244]
When we submitted our app with this library it got rejected on playstore. How do you guys recommend us to avoid this problem? Any suggestions are welcome.
Thanks

![image](https://user-images.githubusercontent.com/13049940/57088679-b709b000-6cfa-11e9-9ee1-d368fb155ff6.png)

**Comment by MoOx** [comment]
I didn't used yet this lib on android, but from what I know from iOS, it should have something similar, like a permission flag to check or something like that?

**Comment by wmcmahan** [comment]
This is a general message Google Play will send and could be various things outside this package. There are a lot of threads around this especially with RN and Expo apps. When using this package, requesting calendar access permission is required. Beyond that, the only other thing I could think would be requesting or adding `attendees`, which should probably be removed .

**Comment by MoOx** [comment]
I guess from the code of this lib, it just cannot be responsible for such issue.
Closing, please comment or reopen with more info, including ALL LIBS used by your project.
