### ISSUE TITLE
How can I get the details of the event organizer

### ISSUE THREAD

**Issue by elan00** [wmcmahan/react-native-calendar-events#246]
How can I get the details of the event organizer

Environment
IOS/Android 

Steps to Reproduce
Get an event.

Expected Behavior
An object detailing event Organizer name and email

Actual Behavior
Organizer information is not available, just buried in the list of attendees

**Comment by wmcmahan** [comment]
The event organizer is not specified, but I agree, it would be a good addition. A feature or pull request can be opened for addition to the package. Thanks!
