### ISSUE TITLE
saveCalendar is not working properly

### ISSUE THREAD

**Issue by dophlin** [wmcmahan/react-native-calendar-events#247]
I'm using the following code in order to create a calendar, while it works on Android, it does not work on iOS.

```
try {
            let calendars = await RNCalendarEvents.findCalendars();
            if(calendars.length > 0) {
                let cdcCalendar = calendars.find(calendar => {
                    console.warn(calendar.title, calendar.id);
                    return calendar.title == "CDC:" + customerId && calendar.allowsModifications;
                });
                if(cdcCalendar) return cdcCalendar;
            }
            let source = {
                name: "CDC:" + customerId,
                type: "LOCAL"
            };
            if(calendars[0] && calendars[0].source && calendars[0].type) {
                source.name = calendars[0].source;
                source.type = calendars[0].type;
            }
            let newCalendar = {
                title: "CDC:" + customerId,
                color: "#4CB5DE",
                entityType: 'reminder',
                name: "CDC:" + customerId,
                accessLevel: 'owner',
                source,
                ownerAccount: source.name
            };
            let theCalendarId = await RNCalendarEvents.saveCalendar(newCalendar);
            return {...newCalendar, id: theCalendarId};
        } catch(err) {
            console.warn(err);
            return null;
        }
```

The weird thing is that the saveCalendar returns a new UUID for the created calendar, but the Calendars app inside the iOS does not show any created calendar.

### Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 21.58 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.1 AI-173.4670197
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.7 => 0.57.7
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-push-notification: 3.1.2

### Expected Behavior
The saveCalendar function creates a new calendar on iOS

### Actual Behavior
The saveCalendar function only creates a new calendar on Android.

**Comment by wmcmahan** [comment]
Hi @dophlin, do you see the created calendar in the `RNCalendarEvents.findCalendars` results? Also, `entityType` is set as `reminder`. You may want to use `event`.

**Comment by dophlin** [comment]
Hi @wmcmahan, the created calendar is not listed in the `RNCalendarEvents.findCalendars`.
However, setting the `entityType` as `event` resolved the problem. Thanks for your hint.
