### ISSUE TITLE
Breaking change released as semver patch 1.7.2

### ISSUE THREAD

**Issue by mikehardy** [wmcmahan/react-native-calendar-events#248]
### Steps to Reproduce
1. Use the API CalendarEventspackage.onRequestPermissionsResult
1. Use version 1.7.1 of this module as a `^1.7.1` style version range
1. Run `npm update`
1. Build java

### Expected Behavior

Build should not fail

### Actual Behavior

```java
        CalendarEventsPackage.onRequestPermissionsResult(requestCode, permissions, grantResults);
                             ^
  symbol:   method onRequestPermissionsResult(int,String[],int[])
  location: class CalendarEventsPackage
1 error
```

I understand APIs need to change (I manage react-native-device-info, help on react-native-share and react-native-firebase), but semver should be respected as a best practice

Suggest npm unpublish this release, re-release as 2.0.0 with a suggested upgrade path in the docs

Additionally, you're not pushing your tags / releases to github, so I had to double-check on npmjs.com's version page to make sure I wasn't imagining the release happened

But I want to say I do use this package and I really appreciate the work, it helps my project :-)

**Comment by wmcmahan** [comment]
Thanks @mikehardy, looks like it was an unexpected breaking change. I'm not sure it warrants a major version change, but will publish a fix soon. In the meantime, I would suggest pinning your version to 1.7.1.

**Comment by mikehardy** [comment]
semver is unemotional -> API breaks, it's a major version bump :-). It's only us humans that attach meaning to the first digit. But if the API was maintained for backwards-compability then sure

Completely unrelated - all my family is in Austin, all my close family is there - if you get a chance have some Micklethwaite brisket for me ;-), I moved to a place that hasn't learned how to do it right

**Comment by wmcmahan** [comment]
Yeah, unfortunately the API wasn't intended to be breaking ;) That was one is on me. I've reverted the change and published. Will republish that with better notice.

Good brisket is a must. Your family picked a great place to live!
