### ISSUE TITLE
Error on Android after call to saveDate

### ISSUE THREAD

**Issue by gilesvangruisen** [wmcmahan/react-native-calendar-events#25]
I commented on #23, but I'm seeing a native error when trying to make a call to `RNCalendarEvents.saveEvent` on Android. cc @lilach 

Here's the stack trace, although it probably isn't very insightful.
```
Error: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getLastPathSegment()' on a null object reference
    at createErrorFromErrorData (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7099:11)
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7062:35
    at MessageQueue.__invokeCallback (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7442:10)
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7294:8
    at guard (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7213:1)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7293:1)
    at onmessage (http://localhost:8081/debuggerWorker.js:44:56)

```

**Comment by Almouro** [comment]
Got the same error, when looking at logs from android studio or `adb`, it comes from a parsing error:
```Unparseable date: "2016-10-01T09:45:00.000Z"```

Could it be the same for you?

**Comment by gilesvangruisen** [comment]
Interesting! It might well be. iOS version seems to be able to parse it fine, so we should look into why Android is not, and perhaps add a check there to provide some better error message.

Nice catch!

**Comment by alexprodev** [comment]
I changed the startDate and endDate string format and I passed that error but finally I got the loading screen and it is not disappearing after a while.

**Comment by lilach** [comment]
Thank you for reporting and investigating it further.
It's a bit strange to me that the date is unparseable, since the expected date format is exactly the same: `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'`.
What I understand from the stacktrace is that an event was not created, thus when trying to get the event ID (using `Uri.getLastPathSegment`) it throws an exception. It is possible it couldn't be created because the date was not parsed.
Unfortunately, i can't reproduce this issue, but I'll add protection.

**Comment by alexprodev** [comment]
I passed that issue by changing the date format on javascript side like below.
if (Platform.OS !== 'android') {
  return makeUppercase(moment(startDate).utc().format("YYYY-MM-DTHH:mm:ss.SSS") + "UTC");	
} else {
  return makeUppercase(moment(startDate).utc().format("YYYY-MM-DTHH:mm:ss.SSS") + 'Z');	
}

**Comment by jsuhangita** [comment]
is this format correct? "2020-12-05T03:00:00.000+07:00". this format works on ios, but in android it says [Error: Unparseable date: "2020-12-05T03:00:00.000+07:00"]

**Comment by MoOx** [comment]
It seems only dates in UTC are accepted. I got this issue myself yesterday.
Another option is to send timestamp as float.
