### ISSUE TITLE
List possible calendars to export too

### ISSUE THREAD

**Issue by sdb1228** [wmcmahan/react-native-calendar-events#26]
I think this is more of a feature request, but I would love the ability to select the calendar to save my calendar events to.   I hope to have more time to possibly contribute to this repo, but something I would like to see in the next version or so!  You guys rock though and thanks for the library!

**Comment by wmcmahan** [comment]
Hey @sdb1228, thanks! This is definitely something I've been trying to get around to, but somehow always slips though. Definitely a needed update.

**Comment by pierre-moire** [comment]
That would be great, I added a $5 bounty on this :) https://www.bountysource.com/issues/39014115-list-possible-calendars-to-export-too

**Comment by Zamponotiropita** [comment]
That would be really great: to be able to choose to which calendar to export to and also to be able to see in which calendar the event is coming from when fetching all events

**Comment by wmcmahan** [comment]
Ok, I found some time this morning to add this in. To find a list of available calendars, use:

```javascript
 RNCalendarEvents.findCalendars()
```

This method will get the Calendar IDs available, as well as name and source. With the specific ID, you can then add it to the options when saving an event. If no `calendarId` property is defined, it will save to the default calendar.

```javascript
RNCalendarEvents.saveEvent('Event Name', {
      calendarId: "7A32CE4C-1C64-4ED3-8E9A-77D3DAFDE462",
      startDate: '2017-10-01T09:45:00.000Z',
      endDate: '2017-10-01T09:46:00.000Z'
})
```

I hope this helps!

**Comment by pierre-moire** [comment]
Great!

**Comment by pierre-moire** [comment]
Don't hesitate to claim https://www.bountysource.com/issues/39014115-list-possible-calendars-to-export-too , I will add other ones for points that matter to me. That will pay some beers to support your work :)

**Comment by wmcmahan** [comment]
@pierre-moire Thanks, I think I will 🍺
