### ISSUE TITLE
Alarm is not working 

### ISSUE THREAD

**Issue by dexbytes** [wmcmahan/react-native-calendar-events#261]

**Comment by dexbytes** [comment]
Now it's Solved, 

In the dates variable we need to send times (in Minutes) Not in a date formats.
Thank you

**Comment by Fashad-Ahmed** [comment]
@dexbytes can you provide a sample of that

**Comment by Fashad-Ahmed** [comment]
> @dexbytes can you provide a sample of that

` const eventDetails = {
        startDate: taskStartDate.toISOString(),
        endDate: taskStartDate.toISOString(),
        alarms: [{date: 1}],
      };`
      
 where 1 refers to 1 minute after the event has occured, if you want to show alarm before x minutes you can use -x as value for data key in alarms array of object.
