### ISSUE TITLE
RNCalendarEvents.saveEvent() creates unexpected attendees and 30mins reminder

### ISSUE THREAD

**Issue by Elabar** [wmcmahan/react-native-calendar-events#262]
Whenever I try to save a new event with or without alarms, it will save a guest as well. After a few seconds, the guest will disappear and a 30mins reminder is set, which it is not set on my code. If the saved event was saved with alarm, the guest will appear and disappear as well, but the alarm will remain as the one I set instead of the unexpected 30mins.

### Environment

```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
      Memory: 2.76 GB / 7.90 GB
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
```
### Steps to Reproduce

My code:
```
        if(this.state.alarm){
            await RNCalendarEvents.saveEvent(values.name, {
                calendarId: calendar[0].id,
                startDate: (new Date(values.startDate)).toISOString(),
                endDate: (new Date(values.endDate)).toISOString(),
                alarms: [{
                    date: Number(values.alarmOffset) * 60
                }]
            }).then(id => {values.calendarEventID = id;});
        }else{
            await RNCalendarEvents.saveEvent(values.name, {
                calendarId: calendar[0].id,
                startDate: (new Date(values.startDate)).toISOString(),
                endDate: (new Date(values.endDate)).toISOString(),
                alarms: []
            }).then(id => {values.calendarEventID = id;});
        }        
```
### Expected Behavior

Unexpected guest should not appear, and nor the unexpected alarm.

### Actual Behavior

If I set it without alarm, the guest is created and it will be deleted after a short while and a 30min reminder come out. Same goes to set with alarm, but it will not disturb the alarm I set.
<img src="https://user-images.githubusercontent.com/15872787/61869276-d422d900-af0d-11e9-84de-732e9056f2a3.png" width="216">
<img src="https://user-images.githubusercontent.com/15872787/61869425-2c59db00-af0e-11e9-974f-127530678cf2.png" width="216">

**Comment by Elabar** [comment]
Primary calendar is Google Calendar.

**Comment by wmcmahan** [comment]
Make sure that the calendar you are saving to has `allowsModifications`.
