### ISSUE TITLE
calendarId did'nt working

### ISSUE THREAD

**Issue by longb1997** [wmcmahan/react-native-calendar-events#275]
### Environment
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
    Memory: 1.14 GB / 7.93 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1
### Steps to Reproduce
    _createEvent = async () => {
        try {
            let addEvent = await RNCalendarEvents.saveEvent('Go home', {
                calendarId: "12345",
                startDate: moment("2019-10-09T23:09:00.123Z"),
                endDate: moment("2019-10-09T23:34:00.456Z"),
                description: '[4567] Go to home and cooking',
                alarms:[{
                    date: 0
                  }],
            });
            Alert.alert('Added', JSON.stringify({ addEvent }))
            console.log(utcDateToString("2019-10-08T22:34:00.000Z"))
        } catch (e) {
            Alert.alert("Failed to add event")
        }
    }

### Expected Behavior
When i was adding an event with calendarId to handle, but it only receive default id, not calendarId.
Pls help, thanks!

**Comment by wmcmahan** [comment]
To properly save and event to a calendar:

- First you must grant access calendar permission: `authorizeEventStore()`
- Then you must also have write permission to that specific calendar account, which you find view with `findCalendars()`
- And finally you must use the actual calendar ID on event creation. This will not create a custom calendar id.
