### ISSUE TITLE
RNCalendarEvents.removeEvent not working in ios

### ISSUE THREAD

**Issue by harrisgeorge202** [wmcmahan/react-native-calendar-events#277]
I want to remove single instance event from calender by passing calenderId to it. It is working fine in android but when it comes to ios it always returns false

This is an example Id I'm getting "5896A719-DE32-4686-A9BB-8EBEFD501421"
        let removeEvent = await RNCalendarEvents.removeEvent(Id)

**Comment by MoOx** [comment]
Please provide more information and code.
