### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by dylansteck** [wmcmahan/react-native-calendar-events#28]
Hi, 
I have been trying for a while to get this module to work in React Native and every time I run
`RNCalendarEvents.authorizationStatus()
  .then(status => {
    // handle status
  })
  .catch(error => {
   // handle error
  });`

I get the error that 'undefined is not an object'

**Comment by wmcmahan** [comment]
Hey @dylansteck, is this error from iOS or Android? Ensure that this package has been properly setup for [iOS](https://github.com/wmcmahan/react-native-calendar-events#ios) and/or [Android](https://github.com/wmcmahan/react-native-calendar-events#android), then import the library.

```import RNCalendarEvents from 'react-native-calendar-events';```

**Comment by dylansteck** [comment]
Hey @wmcmahan this is an error in iOS and yes I have it set up properly

**Comment by wmcmahan** [comment]
OK, if this package has been properly linked this to the project libraries then you should be able to reference it in your JS module. Double check its listed as a library under "build phases".

**Comment by dylansteck** [comment]
Where would I find Build Phases in XCode or in React Native @wmcmahan

**Comment by wmcmahan** [comment]
If you click the main project file in XCode, you will see "Build Phases" in the top bar. The docs give some images to help easily find it > https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by dylansteck** [comment]
Yep it's in there

**Comment by wmcmahan** [comment]
Hmm, other than restarting the React Packager and Simulator, could you post the full error message as well as the JS code?

**Comment by dylansteck** [comment]
Sure: 
The error is
`undefined is not an object(evaluating '_reactNativeCalendarEvents2.default.authorizeEventStore')`

and the code is 
     `  class WDReactNative extends Component{componentDidMount(){RNCalendarEvents.authorizeEventStore() .then(status=>{// handle status}) .catch(error=>{// handle error});}return (`


and then I have a <View> and some <Text> etc... but right now I'm just trying to authorize then from there fetch events @wmcmahan 

btw. sorry the code is minified, I was having some problems with that

**Comment by jatsrt** [comment]
Same issue as far as I can tell, everything seems linked right, android is working without a problem, 

> TypeError: undefined is not an object (evaluating 'react_native_calendar_events_1.default.authorizeEventStore'

If I check out RNCalendarEvents it is undefined in iOS, it is defined in Android

**Comment by jatsrt** [comment]
OK, figured it out.   Using commonJS or other package systems may cause this.

It's the difference on how you define the package in index.android and index.ios

Example to make it work in index.ios.js 
```
'use strict';

import { NativeModules } from 'react-native';

var RNCalendarEvents = NativeModules.RNCalendarEvents;

export default {
    authorizationStatus() {
        return RNCalendarEvents.authorizationStatus()
    },

    async authorizeEventStore() {
        return RNCalendarEvents.authorizeEventStore()
    },

    async saveEvent(title, details) {
        return RNCalendarEvents.saveEvent(title, details)
    },
}
```

Just need to make it consistent between the two either export default or module.exports

**Comment by jatsrt** [comment]
Come to think of it, this change is easier:

```
'use strict';

import { NativeModules } from 'react-native';

var RNCalendarEvents = NativeModules.RNCalendarEvents;

export default RNCalendarEvents;
```

**Comment by dylansteck** [comment]
Ok thanks, which one of the two would make it easier for me to get calendar events authorized @jatsrt

**Comment by jatsrt** [comment]
So the pull request is merged, you can check it out.  
index.ios.js was changed.  
If you have that change locally, you should be able to follow the readme and you will not get the "undefined" error.

**Comment by dylansteck** [comment]
Ok so the index.ios.js in this case is the prerequesite to work the module then I can authorize etc? @jatsrt

**Comment by wmcmahan** [comment]
@dylansteck, I've published a patch to NPM. You can pull that patched version now.

**Comment by dylansteck** [comment]
Ok it seems like the module is showing but it keeps showing undefined function when I try to run ` componentDidMount(){
    RNCalendarEvents.authorizeEventStore()
  .then(status => {
    // handle status
  })
  .catch(error => {
   // handle error
  });
   }`

**Comment by geldarhb** [comment]
@dylansteck @jatsrt @wmcmahan I had the same problem when calling the _authorizationStatus_ method. I fixed it by changing the import statement I had in my code from:
`var RNCalendarEvents = require('react-native-calendar-events');` 
To:
`var {
    RNCalendarEvents
    } = require('NativeModules');
`

**Comment by wmcmahan** [comment]
@geldarhb You can also use the module import syntax, instead.

```javascript
import RNCalendarEvents from 'react-native-calendar-events'
```
