### ISSUE TITLE
RNCalendarEvents.findEventByID return ambiguous results depending on Platform.OS

### ISSUE THREAD

**Issue by khkwan0** [wmcmahan/react-native-calendar-events#280]
The method findEventByID returns null on android if event is not found.  However, the call throws an Error on ios.  This is inconsistent.  It seems ios and android should both return null if the call cannot find an id.

Verified that calendars are authorized on both ios and android.

This was only found during testing in simulators for both platforms.

### Environment
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 16.99 GB / 31.95 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.10.1 - C:\Users\vr\AppData\Roaming\npm\yarn.CMD
    npm: 6.11.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

### Steps to Reproduce
`try {`
`  let id = await RNCalendarEvents.findEventById('0')`
`  console.log(id)`
`} catch(e) {`
`  console.log(e)`
`}`

### Expected Behavior
According to docs:  the call should return: Object | null
or Error: on error

### Actual Behavior
if no event is found...
android:  returns null

however:
ios: throws Error

**Comment by khkwan0** [comment]
https://github.com/wmcmahan/react-native-calendar-events/blob/master/android/src/main/java/com/calendarevents/CalendarEvents.java

Starting at Line 383

vs

https://github.com/wmcmahan/react-native-calendar-events/blob/master/RNCalendarEvents.m

Starting at Line 867

**Comment by MoOx** [comment]
Could you check if that's still the case with v2?

**Comment by MoOx** [comment]
Closed by #337
