### ISSUE TITLE
Error: No start date has been set.

### ISSUE THREAD

**Issue by MartinSandstrom** [wmcmahan/react-native-calendar-events#282]
**Version:** 

React-native-calendar-events: 1.7.3

React-native: 0.59.9

Running on iOS 13.1.3

**Example code used:** 

```javascript
RNCalendarEvents.authorizeEventStore().then(() => {
            const notes = `This is the notes`;
            const calendareObject = {
              startDate: new Date(slotDateTimeInUnix),
              endDate: new Date(slotEndDateTimeInUnix),
              alarms: [{ date: -60 }]
            }
            if(Platform.OS === 'ios') {
              calendareObject.notes = notes;
            } else {
              calendareObject.description = notes;
            }
            RNCalendarEvents.saveEvent(`AppointmentName`, calendareObject)
            .then(response => {
              Alert.alert(`Saved to calendar with response: ${response}`)
            }).catch(error => {
              Alert.alert(error) // line catching the error
            });
}).catch(error => ErrorHandler.handleError(error));
```

**The issue:**

Saving events have worked in all environments for the longest, but lately it has mysteriously stopped working on iOS devices. When saving an event on iOS simulator, everything is saved as expected. 

The error presented in the app installed on a device via TestFlight is:

_Error: No start date has been set.._ 

When alerting the startDate before trying to save the event it's there and in the correct format, the same format as on the simulator. Seemingly the object being saved is the same on both the simulator and in TestFlight, but with the error being returned from the TestFlight version.

I have NSCalendarsUsageDescription set in info.plist.

Any suggestions or ideas?

**Comment by kam89** [comment]
Please set the Date to ISO Format.

**Comment by bramski** [comment]
Doesn't work for me trying on simulator with:
```
{
  "calendarId": "42D3C3A7-469F-44BA-A97C-CC581AE742AE",
  "endDate": "2020-11-01T20:00:00-08:00",
  "location": "123 location address",
  "notes": "Room 1001",
  "startDate": "2020-11-01T19:00:00-08:00"
}
```

**Comment by bramski** [comment]
Figured it out. The start date must include microseconds:
`2020-11-01T19:00:00.000Z`
That's not ISO. Sorry @wmcmahan you should check what ISO format is actually defined as.

**Comment by bramski** [comment]
a fully formatted ISO date looks like:
```2020-10-15T21:13:48+00:00
2020-10-15T21:13:48Z
20201015T211348Z```

**Comment by wmcmahan** [comment]
LOL ok... checking. Feel free to submit a PR with changes if you feel like its needed. This is open source homie.
