### ISSUE TITLE
How can you create a read-only calendar on iOS?

### ISSUE THREAD

**Issue by sa2812** [wmcmahan/react-native-calendar-events#284]
I'm having some issues creating a calendar on iOS. It appears to be working correctly on Android, but I'm not sure if I'm setting up source correctly

```js
const calendar = {
  title: 'CalendarName',
  entityType: 'event',
  name: 'CalendarName',
  accessLevel: 'freebusy',
  color: '#FF0000',
  ownerAccount: user.username,
  source: {name: 'CalendarName', type: 'CalendarName'},
  isPrimary: false,
  allowsModifications: false,
  allowedAvailabilities: ['busy', 'free', 'tentative']
}
    
newCalendar = await RNCalendarEvents.saveCalendar(calendar)
```

On iOS it's being created as the following:

```js
{
  allowedAvailabilities: (4) ["busy", "free", "tentative", "unavailable"]
  allowsModifications: true
  color: "#FF0000"
  id: "9E0C0339-71FC-4B0A-9C07-BEE601A8B484"
  isPrimary: false
  source: "iCloud"
  title: "CalendarName"
  __proto__: Object
}
```

I just want `allowsModifications` to be false on iOS. How can I achieve this?

**Comment by MoOx** [comment]
I think this is not a thing we can control. This flag is probably for subscribed calendar only, don't you think? So we should add a subscription, not a real calendar.

**Comment by MoOx** [comment]
Not possible AFAIK.

**Comment by claudeaparecio** [comment]
@MoOx Is this still impossible? I have a project that requires a read-only access to the Event, I would appreciate your response.
