### ISSUE TITLE
How to save event id?Error:Possible Unhandled Promise Rejection (id: 0):

### ISSUE THREAD

**Issue by MKoalaX** [wmcmahan/react-native-calendar-events#286]
onPress={() => {
            // AsyncStorage.setItem('@TaskUpdateTime:key', 'I like to sav1e it.');
            // const value = AsyncStorage.getItem('@TaskUpdateTime:key');
            // console.log(value);
            RNCalendarEvents.authorizeEventStore().then(status => {
              console.log(status);
              RNCalendarEvents.authorizationStatus().then(status => {
                console.log(status);
                RNCalendarEvents.saveEvent('ddd3332222d', {
                  id: 'FE6B128F-C0D8-4FB8-8FC6-D1D6BA015CDE',
                  startDate: '2019-11-24T12:22:22.000Z',
                  endDate: '2019-11-26T03:33:22.000Z',
                  notes: '33323234',
                  description: 'sdfadfwef',
                }).then();
                // RNCalendarEvents.findEventById('sdfsdf').then(r => {
                //   console.log(r);
                // });
              });
            });
          }}

**Comment by kam89** [comment]
Hi, If your event is a new event, id is not required.

>  id: 'FE6B128F-C0D8-4FB8-8FC6-D1D6BA015CDE'

If you need to update the event after you have saved, then id is required.

**Comment by MoOx** [comment]
Not enough information. Please open a new issue with more info to reproduce if necessary.
