### ISSUE TITLE
Update documentation for auto link

### ISSUE THREAD

**Issue by mbrucher** [wmcmahan/react-native-calendar-events#288]
The documentation is not clear about what should be still be done with react 0.60 and above.
For instance on Android, the packaging is not with autolink, but we seem to still have to change the activity package.

What about the gradle files (and which build.gradle file? app is not clear enough)? What about iOS?

**Comment by mbrucher** [comment]
To be more exact, this is related to https://stackoverflow.com/questions/58695437/how-do-i-get-react-native-calendar-events-working-on-android-platform-react-nati and an odd iOS working, Android isn't with something as simple as:
```
 return RNCalendarEvents.saveEvent(event.name, {
    description: event.description,
    startDate: new Date(event.date),
    endDate: new Date(event.end_date),
    location: location,
  });
```
On Android, I can't see the event in the calendar, neither does `fetchAllEvents` for the days around this, when it works flawlessly for iOS. Probably because there is something missing in the config and the doc.

**Comment by MoOx** [comment]
The linking part is ok in the doc. Be sure to have the right permissions before using any API.
