### ISSUE TITLE
RNCalendarEvents.removeEvent()  desn't working 

### ISSUE THREAD

**Issue by xiangjiayu** [wmcmahan/react-native-calendar-events#289]
await RNCalendarEvents.removeEvent(calendarInfo.calendarId, {
			exceptionDate: calendarInfo.startTime,
			futureEvents: false,
		})
			.then(event => {
				console.log('deleted event', event);
			})
			.catch(error => {
				console.log(error);
			});

I get  'deleted event false' .  why? why? who can tell me ?

**Comment by kam89** [comment]
You should provide the **eventId** instead of **calendarId**.
You can get the eventId by using **fetchAllEvents** or **findEventById**.
