### ISSUE TITLE
Removal of a reccurent event remove all events

### ISSUE THREAD

**Issue by rrraymonde** [wmcmahan/react-native-calendar-events#291]
I've created a reccurent event (eventA) with the following reccurency rule:
```
recurrenceRule: {
          frequency: 'daily,
          endDate: endDate.toISOString(),
},
```

But when I try to delete eventA using RNCalendarEvents.removeEvent(idOfEventA), it removes all the events of my calendar (eventB), not just that one.
If I try to find eventB using RNCalendarEvents.findEventById(idOfEventB), I get a result, even if it really seems to be deleted from my calendar because I don't see it anymore and I don't receive the notifications before the event.

I've only tested on Android.

**Comment by rlazom** [comment]
I got the same problem also...

**Comment by bndby** [comment]
same problem too

**Comment by MoOx** [comment]
The removeEvent method probably need an option to choose if we want to remove all or just one.
PR appreciated.

**Comment by wmcmahan** [comment]
There is a second argument for `removeEvent` that allows for the following [options](https://github.com/wmcmahan/react-native-calendar-events#options). You should be able to specify an `exceptionDate` for removing that single event date only.

**Comment by MoOx** [comment]
Indeed. I guess this issue can be closed if we can already handle this!
