### ISSUE TITLE
SaveCalendar Android 9

### ISSUE THREAD

**Issue by tik27** [wmcmahan/react-native-calendar-events#292]
When trying to create a new calendar.  The save command completes and i am able to add an event.
`{"allowedAvailabilities": ["busy", "free"], "allowsModifications": true, "color": "#4CB5DE", "id": "4", "isPrimary": true, "source": "rxxx@centeraxis.com", "title": "Kick 2020", "type": "com.google"}`

I can keep adding events to this calendar.
But when i open the google Calendar App,I see the events for a couple of seconds, then it disappears. 

Odd thing that i notice, is for the few seconds i see the calendar in the hamburger menu, its does not show my title, it shows as a second unchecked Events under my google account.

Seems that no matter what i make the title/name it always shows as events and gCal is deleting it as a dupe.

When i go back to my app, the calendar is no longer in the list of calendars(RNCalendarEvents.findCalendars())

If i create a local calendar it works as expected

### Environment
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 434.73 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.8.0 - ~/.nvm/versions/node/v9.8.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v9.8.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 27.0.2, 27.0.3, 28.0.3, 29.0.1
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.0 => 0.61.0
### Steps to Reproduce
Create Calendar w/
 {"title":"Kick 2020","name":"Kick2020","color":"#4CB5DE","entityType":"reminder","accessLevel":"owner","isPrimary":false,"ownerAccount":"rxxx@centeraxis.com","source":{"name":"rxxx@centeraxis.com","type":"com.google"},"id":"4"}

### Expected Behavior
Calendar added to my google account

### Actual Behavior
Calendar is removed as soon as user opens the Google Calendar Application

**Comment by tik27** [comment]
Seems to be an Android problem, cannot create calendars on sync accounts

**Comment by GuillaumeHembert** [comment]
Hello @tik27,

I have the same problem. To fix this, what do you do ? you just change type to "local" ?

**Comment by tik27** [comment]
Yes only way i could find.
