### ISSUE TITLE
FetchAll crash

### ISSUE THREAD

**Issue by tik27** [wmcmahan/react-native-calendar-events#293]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'

Error is on Line 660
` if (event.structuredLocation) {
        NSMutableDictionary *structuredLocation = [[NSMutableDictionary alloc] initWithCapacity:3];
        [structuredLocation addEntriesFromDictionary: @{
                                                        @"title": event.structuredLocation.title,
                                                        @"radius": @(event.structuredLocation.radius)
                                                        }];`

**Comment by MoOx** [comment]
Do you have more detail on this bug? f would help to have a way to make a reproduction

**Comment by tik27** [comment]
It has been a while so my memory is not fuzzy.  We were using the fetch all, and the tester that was getting this error seems to have some kind of location alarm that was failing during serialization.   Seemed to be a unique situation since we have not had another user with the problem.

**Comment by MoOx** [comment]
Ok will close for now. Feel free to reopen with more details if this happens again.
