### ISSUE TITLE
Simple saveEvent() fails

### ISSUE THREAD

**Issue by uttampawar** [wmcmahan/react-native-calendar-events#294]
I''m using this library as part of my assignment to learn react-native. But simple  test fails to save event on a calendar on iOS simulator, do I need actual device?

### Environment

$ react-native info
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
    Memory: 45.25 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.17.0 - ~/tools/node-v10.17.0-darwin-x64/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/tools/node-v10.17.0-darwin-x64/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

### Steps to Reproduce

Following is the relevant snippet of the code...

```
componentDidMount() {
  RNCalendarEvents.authorizationStatus()
 .then( () => {
	RNCalendarEvents.authorizeEventStore()
	.then( () => {
  	  if ( this._isMounted ) {
		this.setState( {
		  allowedNativeCalendarAccess: true
		} )
	 }
    } )
  .catch( ( error ) => {
    alert( 'Native calendar can not be used since, access is restricated by the system.' );
   } )
} )
}

function save() {
  const taskStartDate = new Date();
  
if ( this.state.allowedNativeCalendarAccess ) {
  RNCalendarEvents.saveEvent( 'Title of event', {
    id: Math.floor( Date.now() / 1000 ).toString(),
    title: "Test Event,
    startDate: taskStartDate.toISOString(),
    endDate: taskStartDate.toISOString(),
    notes: "Event detail description",
    location: "Event Location"
 } )
 .catch( ( error ) => {
   console.log( `Saving to Calendar: ${JSON.stringify( error )}` )
 } )
}
}

## Added new entry to Info.plist 

<key>NSCalendarsUsageDescription</key>
<string>This app requires access to the calendar</string>
```

### Expected Behavior
I'm expecting this event to be saved on the native devices calendar.

### Actual Behavior
saveEvent() method fails with following error,

{"framesToPop":1,"code":"error","message":"Unknown error from a native module","domain":"RCTErrorDomain","userInfo":null,"nativeStackIOS":["0   MyApp                           0x000000010ae0bd97 RCTJSErrorFromCodeMessageAndNSError + 135","1   MyApp                           0x000000010ad7d3a3 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.218 + 179","2   MyApp                           0x000000010b433f15 __65-[RNCalendarEvents saveEvent:settings:options:resolver:rejecter:]_block_invoke + 421","3   libdispatch.dylib                   0x00000001124daccf _dispatch_call_block_and_release + 12","4   libdispatch.dylib                   0x00000001124dbd02 _dispatch_client_callout + 8","5   libdispatch.dylib                   0x00000001124e2720 _dispatch_lane_serial_drain + 705","6   libdispatch.dylib                   0x00000001124e3261 _dispatch_lane_invoke + 398","7   libdispatch.dylib                   0x00000001124ebfcb _dispatch_workloop_worker_thread + 645","8   libsystem_pthread.dylib             0x00000001128b86fc _pthread_wqthread + 290","9   libsystem_pthread.dylib             0x00000001128b7827 start_wqthread + 15"],"line":2179,"column":45,"sourceURL":"http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false"}

Any help is appreciated.

**Comment by Fashad-Ahmed** [comment]
@uttampawar  how do you fixed that?

**Comment by uttampawar** [comment]
Sorry, I don't remember exact steps but I remember sanitizing the environment (cleaning up the build space). It was such a long time ago.
