### ISSUE TITLE
App crashing when user has an event with structured location

### ISSUE THREAD

**Issue by pie6k** [wmcmahan/react-native-calendar-events#296]
Sometimes I'm getting crash reports from my app

```
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]`

-[RNCalendarEvents serializeCalendarEvent:]
```

and stack

```
6  App                        0x1010e7e1c -[RNCalendarEvents serializeCalendarEvent:] + 660 (RNCalendarEvents.m:660)
7  App                        0x1010e60c4 -[RNCalendarEvents serializeCalendarEvents:] + 453 (RNCalendarEvents.m:453)
```

Seems it's happening when the user has a recurring rule with an end as stack points to this:

```obj-c
        if ([[rule recurrenceEnd] occurrenceCount]) {
            [recurrenceRule setValue:@([[rule recurrenceEnd] occurrenceCount]) forKey:@"occurrence"];
        }
```

TBH I have no idea what exactly is happening, I'll try to inspect it, but I'm not Obj-C developer.

I was trying to replicate:
* by creating daily/weekly recurring events in the calendar with an end date
* by creating recurring events that have already ended

but I was not able to replicate it

When it happens, however - the end-user is not able to open the app ever again as it always tries to fetch the event which sucks.

Maybe serializer could be wrapped inside some `try-catch` so at worst - it'll just skip some event instead of crashing?

**Comment by MoOx** [comment]
@pie6k you looked the wrong place. Latest version on npm L 660 lead to structured location code.
See https://github.com/wmcmahan/react-native-calendar-events/blob/2179c84d68a980e1a6b27d98d7f19e4d91300733/RNCalendarEvents.m#L660

**Comment by MoOx** [comment]
I reproduced the issue successfully by creating an event with this own module that have a structuredLocation alarm without a date.
I will find a way to fix this specific issue someone & will add a security layer (a bunch of try catch) to cover the ass of this lib to avoid brutal crash & instead have promise that fail
