### ISSUE TITLE
how can I delete a local calendar?

### ISSUE THREAD

**Issue by rlazom** [wmcmahan/react-native-calendar-events#298]
I am currently using your plugin. 
But when I started using it, I was making several tests trying to create events and calendars. 
That's my current problem, now, I have like 5 calendar from when I was testing.
So my question is: 
- How can I delete those, or can you add a new method for that?
and by the way, also for update them...

Thanks in advance

**Comment by i3po** [comment]
Had the same problem. I did use not closed PR from this repo with my fork and temporary using it.
`yarn add https://github.com/i3po/react-native-calendar-events
`

**Comment by MoOx** [comment]
We just added a removeCalendar method in #269. Please check if that's enough.
