### ISSUE TITLE
Fetch event by ID

### ISSUE THREAD

**Issue by Prudwell** [wmcmahan/react-native-calendar-events#30]
Hello I was wondering if there are any plans to add a method to fetch an event by its ID. I have a use case where I want to be able to query an event to see if it exists by the ID as I won't know if the current date stored on my device is correct and can't use it in the fetch-all-in-date-range method. My app will have support for multiple devices, offline mode, and synching via webserver, so I'm interested in being able to check if a single event is already set up on the device, and if so, does the date in iOS calendar match what is stored in my App's databse.

I see that there is a method in the Calendar API for this

[https://developer.apple.com/reference/eventkit/ekeventstore/1507490-event](https://developer.apple.com/reference/eventkit/ekeventstore/1507490-event)

I'd take a whack at it myself but I zero experience in that language.

For now I can do a fetchAll using a huge daterange and then loop through every event to see if the iOS event that I'm looking for exists and then whether it's set for the correct date. 

Cheers and thanks for putting this package together

**Comment by wmcmahan** [comment]
Hey @Prudwell - Yes, i agree that being able to find an event by ID from storage is needed. I will try and add this to the next release. Cheers!

**Comment by wmcmahan** [comment]
Now included in version 1.2.0
