### ISSUE TITLE
Add IOS Permission request

### ISSUE THREAD

**Issue by abdallaemadeldin** [wmcmahan/react-native-calendar-events#300]

**Comment by wmcmahan** [comment]
This is available with `authorizeEventStore()`

**Comment by MoOx** [comment]
For React Native developer, the name might not be explicit enough. Maybe in v2 we could rename this to Permissions.request/check (to match APIs like react-native-permissions)

**Comment by wmcmahan** [comment]
Yes, I agree. The naming conventions can be better.
