### ISSUE TITLE
Can't create event on release app

### ISSUE THREAD

**Issue by mezalejandro** [wmcmahan/react-native-calendar-events#301]
In android app release i can't create a event not working

### Environment

System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 257.76 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.1, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
### Steps to Reproduce

`await RNCalendarEvents.authorizeEventStore();
    await RNCalendarEvents.saveEvent(title, {
        id: id,
        startDate: new Date(startDate).toISOString(),
        endDate: new Date(endDate).toISOString(),
        description: description,
        allDay:false,
        alarms: [{
            date: 1
        }]
      }) .then( (e) => {
                        Toast.show('Evento agendado')
                        return e
                    }).catch((error) => {
                        alert(error)
                        console.error(error)
                    })`

**Comment by margaridaDinis** [comment]
Try removing the `id`.
If you check the documentation, it mentions that id is read-only

**Comment by MoOx** [comment]
The comment above seems to explain the issue. If that's still a problem, feel free to post a comment or reopen a new issue.
