### ISSUE TITLE
method remove calandar isn't available ?

### ISSUE THREAD

**Issue by 1bastien1** [wmcmahan/react-native-calendar-events#303]
### Environment
System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1.66 GB / 7.69 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
    Yarn: Not Found
    npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
### Steps to Reproduce

```
export async function removeAllCalendar() {
  let calendars = await RNCalendarEvents.findCalendars();
  calendars.forEach((c) => {
    if ((c.source = "plant OClock's feed")) {
      RNCalendarEvents.removeCalendar(c.id);
    }
  });
}
```
### Expected Behavior

be able to use removaCalendar() because for testing my phone has around 10 times the ame calendar

### Actual Behavior
my debug console tell me that removeCalendar is not found and my ide didn't regonize too.
So i made a 
npm update, nope
remove node_modules and npm i, nope
npm update react-native-calendar-events, nope
So my my package is not up to date?

~thanks for the job already did and the wonderful documentation

**Comment by MoOx** [comment]
This has not been released yet, you need to use version from git if you want to try it.
