### ISSUE TITLE
the purpose of a line code?

### ISSUE THREAD

**Issue by jiaozidev** [wmcmahan/react-native-calendar-events#304]
in android CalendarEvents;
in themod 'findEventCalendars()'

String IS_PRIMARY = CalendarContract.Calendars.IS_PRIMARY == null ? "0" : CalendarContract.Calendars.IS_PRIMARY;

**Comment by MoOx** [comment]
No idea, I am new to the codebase as a maintainer.

**Comment by wmcmahan** [comment]
Is a way to handle query for "is_primary" calendar column that some previous Android SDK versions don't provide. https://docs.microsoft.com/en-us/dotnet/api/android.provider.calendarcontract.calendarcolumns.isprimary?view=xamarin-android-sdk-9
