### ISSUE TITLE
[Android] Multiple "allday events"

### ISSUE THREAD

**Issue by Turboconnard** [wmcmahan/react-native-calendar-events#31]
Hey, I have a problem with the allday attributes. 
If I save an event from Monday 0:00 to Tuesday 23:59 with the "allday" attribute, the event is only registered for Monday. Tuesday is ignored -this works well on IOS-.

I don't know if it's the way android calendar works but if I remove the allday attribute on my default HTC calendar the Monday event is automatically flagged "allday" and the Tuesday is filled from 0:00 to 23:59.

Now if I create an event from Monday 0:00 to Wednesday 0:00 without "allday" attribute i've got my Monday and Tuesday flagged as "allday" event.

Anyone knows if it's the right way to save "allday" events on android ? or my htc default calendar is pretty clever and this would fail on all other android devices ?

anyway, thanks for the good work.

**Comment by wmcmahan** [comment]
@Turboconnard I'm currently able to create all-day events and have not been able to reproduce this. Also, make sure you are using the correct case for the "allDay" property name.
