### ISSUE TITLE
Calendar sources are not consistent

### ISSUE THREAD

**Issue by dasaco** [wmcmahan/react-native-calendar-events#310]
Hi. Thank you for the library, great work!!! 
Has anybody encountered an issue when you want to list subcalendars under separate emails? Whenever you use findCalendars it returns source as "Gmail", sometimes it's an email, so if you have 2 gmails connected, you don't know which gmail does the calendar belong to.

Here is an example of 2 events from 2 different Gmail accounts:

```json
[
  {
      "allowedAvailabilities":[
        "Array"
      ],
      "allowsModifications":false,
      "color":"#92E1C0",
      "id":"<id>",
      "isPrimary":false,
      "source":"email@gmail.com",
      "title":"Contacts"
  },
  {
      "allowedAvailabilities":[
        "Array"
      ],
      "allowsModifications":true,
      "color":"#FF7537",
      "id":"<id>",
      "isPrimary":false,
      "source":"Gmail",
      "title":"Company Calendar"
  }
]
```

**Comment by MoOx** [comment]
maybe it's just the name used when the account is saved on the device?

**Comment by dasaco** [comment]
@MoOx Great observation, it indeed is exactly the same as in iOs Accounts screen. I will further investigate on how to get calendar email from iOS, this has nothing to do with the library. Thanks!
