### ISSUE TITLE
saveCalendar being deleted automatically, minutes after being created.

### ISSUE THREAD

**Issue by t-heu** [wmcmahan/react-native-calendar-events#313]
i create calendar correctly it returns the id to me, in the same second that i create i manage to list it, but after a while it is automatically deleted, a matter of seconds. Any idea?

Versions:
react-native": "0.62.2"
react-native-calendar-events": "^1.7.3"

Device:
SO: Android 8

I did a test, saved calendar, and open the device log, suddenly saved calendar disappeared along with the events that were saved in that calendar that I created recently, then it appeared in the log, it seems that the system itself is deleting the saved calendar, but the Google calendar calendar remains there without changes.
Log:
```
07-03 18:57:22.003  2005  6623 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PROVIDER_CHANGED dat=content://com.android.calendar flg=0x20000014 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver
07-03 18:57:22.041 23522  9336 I IcingInternalCorpora: Received calendar change notification.
07-03 18:57:23.649 23522 25901 I IcingInternalCorpora: EventIndexer: starting incremental update
07-03 18:57:23.658 23522 25901 I IcingInternalCorpora: EventIndexer: 0 added, 1 removed, 0 changed, 60 unchanged, 0 errors.
07-03 18:57:23.711 23522 23522 I IcingInternalCorpora: EventIndexer: finished after 62 ms.
```

```
await RNCalendarEvents.saveCalendar({
    name: CALENDAR_NAME,
    title: CALENDAR_NAME,
    accessLevel: 'owner',
    color: '#EEAE0F',
    source: {
      name: 'test',
      type: 'com.memodates',
    },
    entityType: 'event',
    ownerAccount: 'xxx@gmail.com',
  })
```

**Comment by wmcmahan** [comment]
There are several things that could cause this:

- A common simple problem is that the calendar account has not been added to the device. This can be tricky with gmail, especially on the emulator.
- If you do have the calendar account on the device, ensure that permissions to that calendar account allow for write access.
- Also, check the calendar sync settings on the device

**Comment by MoOx** [comment]
This might be a sync problem (see https://github.com/wmcmahan/react-native-calendar-events#troubleshooting)
