### ISSUE TITLE
Any interest in a PR for read-only calendar access?

### ISSUE THREAD

**Issue by mikehardy** [wmcmahan/react-native-calendar-events#318]
Seems like this module is alive again! Sweet

I'd like to use this module in a read-only way. I don't want to have calendar write permission

I could submit a PR for this if it's an acceptable idea, I'm already using a patch-package patch to crudely hack out the write permission in my local environment.

I'd do my best to make it backwards-compatible, probably with an optional boolean javascript parameter ('readOnly'?) to check and request permission where you could toggle it off, but it defaulted to current behavior, and then an internal refactor to do it 

### Environment

I'm proposing a PR and a rough sketch of it vs current master, one of the few times environment data is not important ;-)

### Steps to Reproduce

Try to use the module without write permission, none of the APIs are useful

### Expected Behavior

Able to get existing calendar entries with read permission only

### Actual Behavior

No data

**Comment by MoOx** [comment]
From my iOS knowledge, this is not possible as there is only `NSCalendarsUsageDescription`.
It seems to be a thing you can do for Android only, but let's go for it. You can easily add a parameter to check/requestPermissions methods

**Comment by mikehardy** [comment]
@MoOx correct - my patch-package patch only hacks up the Java file, but it's still a tangible difference, discarding calendar write and using just read is a powerful signal to users from our app on what our intention is. I'll take a cut at it and post it for review. Thanks!

**Comment by MoOx** [comment]
It's definitely a good thing to have. I hope Apple will make the distinction someday.
