### ISSUE TITLE
Calendar Not Working Fine On MIUI 

### ISSUE THREAD

**Issue by naufalahnaf17** [wmcmahan/react-native-calendar-events#323]
### Environment
Test On MIUI 12 Android 10

OS: Linux 4.15 Linux Mint 19.2 (Tina)
  CPU: (4) x64 AMD FX-7600P Radeon R7, 12 Compute Cores 4C+8G
  Memory: 131.14 MB / 6.76 GB
  Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    npm: 3.5.2 - /usr/bin/npm
  npmPackages:
    react: 16.9 => 16.9.0 
    react-native: 0.61.5

### Expected Behavior
Calendar Working Fine On MIUI OS

### Actual Behavior
All function working fine on all os except MIUI , i dont know why this happen but i try another method to save and modify all graddle on android folder but i its not working . is this bug or something ?

This My Code Like Documentation Said

```js
RNCalendarEvents.saveEvent(this.state.title, {
                startDate: hasilStart.toString(),
                endDate: hasilStart.toString(),
                description : 'mv_' + this.makeid(16).toString() + now_utc.toString(),
            }).then(()=>{
                this.props.navigation.goBack();
            }).catch((err) => {
                console.log(err);
            })   
```

**Comment by MoOx** [comment]
Can you tell precisely what "isn't working"? Please provide all the info you can about the actual error (message, stack trace etc)

**Comment by naufalahnaf17** [comment]
CRUD Calendar isn`t working , but tbh no error log show on terminal . i still confused why this happen only on MIUI .. everything working fine on other os and android even IOS to

**Comment by MoOx** [comment]
Without error or log, I can't help as I don't have a phone with MIUI.
Also you didn't specify the version of this lib you are using

**Comment by naufalahnaf17** [comment]
well "react-native-events-calendar": "^1.0.8", i used version 1.0.8 on my package.json , i still confused why this only happen on MIUI OS Only .. maybe any developer here who use MIUI Phone For Debug Application ?

**Comment by MoOx** [comment]
Please try to upgrade to latest version & see if the issue persist. You can find release notes here https://github.com/wmcmahan/react-native-calendar-events/releases.

**Comment by naufalahnaf17** [comment]
I will close this issue and open later if the error still found on MIUI Os on release application .
