### ISSUE TITLE
RNCalendarEvents.fetchAllEvents(startDate, endDate) throws error

### ISSUE THREAD

**Issue by kmanishk1** [wmcmahan/react-native-calendar-events#324]
I am trying to fetch all the events of all available calendars using `RNCalendarEvents.fetchAllEvents()` command, but it throws error `Exception in HostFunction` on both Android and iOS

### Environment
<img width="336" alt="Screen Shot 2020-09-11 at 2 44 10 PM" src="https://user-images.githubusercontent.com/22726936/92900613-761cc200-f43d-11ea-868e-04d2609de32e.png">

manishkumar@MacBook-Pro videoCall % react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 25.58 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.1 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 23.0.2, 23.0.3, 24.0.1, 25.0.2, 25.0.3, 26.0.2, 28.0.3, 29.0.2, 29.0.3
      System Images: android-26 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /usr/bin/javac
    Python: 3.7.4 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
### Steps to Reproduce
1. Install the package `react-native-calendar-events` as instructed.
2. Calling the command `RNCalendarEvents.fetchAllEvents(startDate, endDate, [])` since I need events of all calendars in `useEffect` hook only once
3. `console.log()` what is returned in the promise.
4. Gives the above red screen on both Android and iOS devices

`
useEffect(() => {
// fetch all the events of all calendars
    let startDate = moment('2020-09-01')
    let endDate = moment('2020-09-30')
    RNCalendarEvents.fetchAllEvents(startDate, endDate)
      .then(allEvents => {
        console.log('allEvents', allEvents)
      }).catch(error => console.log('all events error', error))
}, [])
`

### Expected Behavior

It should return all the events, maybe a collection of objects
### Actual Behavior

Gives the above red screen on both Android and iOS devices

**Comment by MoOx** [comment]
Can you try passing an actual javascript date object instead of a moment?

**Comment by kmanishk1** [comment]
@MoOx thanks for the reply. 

let startDate = Date('2020-09-01')
let endDate = Date('2020-09-30')

I get this error while passing javascript date object

<img width="342" alt="Screen Shot 2020-09-11 at 3 11 41 PM" src="https://user-images.githubusercontent.com/22726936/92905343-348e1600-f441-11ea-9f94-fd49c543da92.png">

**Comment by MoOx** [comment]
The error is explicit, for now this lib expect a date as a string. See https://github.com/wmcmahan/react-native-calendar-events#fetchallevents

**Comment by kmanishk1** [comment]
![dfa](https://user-images.githubusercontent.com/22726936/92910854-1971d500-f446-11ea-9e08-1ee7d5d1c5e1.jpg)

**Comment by kmanishk1** [comment]
Passing the Date as, new Date().toISOString() solved the issue. Thank you so much @MoOx sir. was stuck on it since yesterday
