### ISSUE TITLE
Does this package provide User Interface?

### ISSUE THREAD

**Issue by joaogsousa** [wmcmahan/react-native-calendar-events#326]
I could not understand by reading the Documentation. Does this lib include some user interface in order for the user to interact and provide info about the calendar event that is being added?

**Comment by wmcmahan** [comment]
Hey @joaogsousa. No, this does not provide any calendar UI. This package is useful for managing stored calendar events via the device API. Although, there are quite a few public packages that provide calendar UI that could be paired with this package. Hopefully that helps clarify.
