### ISSUE TITLE
[ESLint] Add index.js entry point to match properly with ESLint rules

### ISSUE THREAD

**Issue by eelmoni** [wmcmahan/react-native-calendar-events#327]
In last version `index.js` file for entry point to the library was deleted, this is causing some general ESLint rules started to warn. Does make sense to add a `index.js` as the entry point? Also configure the "main" attribute in the package.json file properly.

- Set `"main": "src/index.js"` in `package.json`
- Add the following code on `index.js` file:
```
'use strict'

import { Platform } from 'react-native';

let CalendarEvents;

if (Platform.OS === 'ios') {
  CalendarEvents = require('./index.ios').default;
} else {
  CalendarEvents = require('./index.android').default;
}

export default CalendarEvents;
```

### Environment

No need for environment info for this issue.

### Steps to Reproduce

- Install react-native-calendar-events in your project.
- Make sure you have `"eslint-plugin-import": "2.11.0",` as a plugin for eslint.

### Expected Behavior

- No errors are displayed.

### Actual Behavior

Warnings for two rules:
- https://github.com/benmosher/eslint-plugin-import/blob/v2.11.0/docs/rules/no-unresolved.md
- https://github.com/benmosher/eslint-plugin-import/blob/v2.11.0/docs/rules/extensions.md

<img width="1264" alt="Screen Shot 2020-09-30 at 19 26 54" src="https://user-images.githubusercontent.com/8320438/94747988-9d88ef80-0356-11eb-99f6-95abc824b352.png">

**Comment by MoOx** [comment]
This is unecessary code to make a linter happy. They already got this kind of issue reported https://github.com/benmosher/eslint-plugin-import/issues/917
Please open a bug there instead & use our package as an example on what should work.

I am no fan of modifying some code just to make a linter happy (as it doesn't bring any value since this code actually "compile" & works as expected).

**Comment by eelmoni** [comment]
hi @MoOx , no it is not the same issue. The thing is the main property in package.json is not set properly. I was reviewing other react native modules/dependencies and it seems they set a proper main attribute in package.json file. But we need to create a file as an entry point in order to set it. Right now, I applied a patch using patch-package.

Just trying to follow a standard way but no problem if you prefer to not implement it.

**Comment by MoOx** [comment]
According to npm docs, [package.json main attribute](https://docs.npmjs.com/files/package.json#main) is a "module ID".

> This should be a module ID relative to the root of your package folder.

`react-native-calendar-events/src` is a totally valid module id from what I know from node/npm & bundlers like metro or web pack.

Again: the current situation is working and nobody had any issue with the current setup. You concern is legit but should be raised to the eslint plugin, not here.

**Comment by MoOx** [comment]
According to what I can see, this should already work... https://github.com/benmosher/eslint-plugin-import/blob/3b04d5fab6c095e7f0f99488665d90e285872271/config/react-native.js#L9
