### ISSUE TITLE
Comment docs for requestPermissions: "request" instead of "check"

### ISSUE THREAD

**Issue by donovanrichardson** [wmcmahan/react-native-calendar-events#334]
For the [requestPermissions method](https://github.com/wmcmahan/react-native-calendar-events/blob/66c47815b7bc946a390fc63788016f6206e0f9f8/src/index.d.ts#L175) in `src/index.d.ts`, shouldn't the comment doc for `@readOnly` read `use true to request calendar read only`?

**Comment by MoOx** [comment]
yeah I guess so.
