### ISSUE TITLE
ios(sim) - Application closes when executing  RNCalendarEvents.authorizeEventsStore()

### ISSUE THREAD

**Issue by JonathonJulian** [wmcmahan/react-native-calendar-events#34]
Hi
I'm using a simulator running iOS 10.2 (iPhone6). When RNCalendarEvents.authorizeEventsStore() is run the application closes and produces no errors.. when i check authorized status is shows as undetermined.
using the code from the readme

RNCalendarEvents.authorizeEventStore()
  .then(status => {
    // handle status
  })
  .catch(error => {
   // handle error
  });

**Comment by JonathonJulian** [comment]
I needed to update Info.plist :s

**Comment by irfanayazfm** [comment]
@JonathonJulian What update specifically?

**Comment by wmcmahan** [comment]
@irfanayazfm There is a short description in the [readme](https://github.com/wmcmahan/react-native-calendar-events#ios).
