### ISSUE TITLE
after few seconds event is automatically disabling from google calander. i am using react native 0.61.5

### ISSUE THREAD

**Issue by ChinnaNaikMudavathu** [wmcmahan/react-native-calendar-events#340]
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, { useEffect } from 'react';
import {
  SafeAreaView,
  StyleSheet,
  View,
  Text,
  StatusBar,
  TouchableOpacity,
} from 'react-native';
import RNCalendarEvents from "react-native-calendar-events";

const App: () => React$Node = () => {

  const calendarAccessPermission = async () => { 
    const status = await RNCalendarEvents.checkPermissions(false); 
    if (status !== "authorized") { 
      const requestStatus = await RNCalendarEvents.requestPermissions(false); 
      if (requestStatus === "authorized" || requestStatus === "undetermined") { 
        return true; 
      } else { 
        return false; 
      } 
    }else{ 
      return true; 
    } 
  };

const onPressGoogleEvent = async () => {

  const store = await calendarAccessPermission();
  if (store) {
    
    addToCalendar();
  } else {
  alert('need access');
  }
}

const addToCalendar = () => {
  RNCalendarEvents.saveEvent('Google calendar event title', {
    calendarId: '140',
    location: 'where you will get peace',
    notes: 'chill mar',
    startDate: '2021-01-13T10:30:00.000Z',
    endDate: '2021-01-13T10:35:00.000Z',
    }).then((eventInfo) => alert(eventInfo));
}
  
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView style={styles.safeAreaView}>
        <View style={styles.container}>
       <TouchableOpacity
          style={styles.touchable}
          onPress={onPressGoogleEvent}
       >
         <Text style={styles.touchableText}>google event</Text>
       </TouchableOpacity>
        </View>
      
      </SafeAreaView>
    </>
  );
};

const styles = StyleSheet.create({
  safeAreaView: {
    flex: 1
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center"
  },
  touchable: {
    width: 100,
    height: 40,
    backgroundColor: "#68CAD6",
    justifyContent: "center",
    alignItems: "center",
    borderRadius:4
  },
  touchableText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
    textAlign: "center"
  }
});

export default App;

**Comment by ChinnaNaikMudavathu** [comment]
in side render i have a button on click of it onPressGoogleEvent method will trigger

**Comment by MoOx** [comment]
You didn't respect the issue template. I guess, you didn't read the doc neither https://github.com/wmcmahan/react-native-calendar-events#troubleshooting
