### ISSUE TITLE
Android calendar permission issue

### ISSUE THREAD

**Issue by afanchamp** [wmcmahan/react-native-calendar-events#348]
React Native v0.63.4
 "react-native-calendar-events": "^2.2.0"
 
 im not even getting permission prompt instead getting this null is not an object (evaluating 'RNCalendarEvents.checkPermissions')] for both checkPermission and requestPermission. 
 
  const store = await RNCalendarEvents.checkPermissions();
      if (store === 'authorize') {
          console.log('here')
      } else {
        RNCalendarEvents.requestPermissions()
          .then((res) => {
            console.log('here', res)
            if (res === 'authorized') {
            } else {
              console.log('err', res);
            }
          })
          .catch(() => {
            alert('This app needs calendar access');
          });
      }

**Comment by wmcmahan** [comment]
@afanchamp Is the library properly linked? (https://reactnative.dev/docs/linking-libraries-ios) Also, a small typo, the string should be `authorized`.

**Comment by afanchamp** [comment]
I'm getting this error on android only. let me go through the documentation once more.

**Comment by afanchamp** [comment]
@wmcmahan getting the same error after manually linking android.

**Comment by MoOx** [comment]
Please share your AndroidManifest so we can have look to perms.

**Comment by afanchamp** [comment]
i tried both
    <uses-permission android:name="android.permission.READ_CALENDAR" />
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />
    
    and also one from the documentation 
    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
  >
  <uses-permission tools:node="remove" android:name="android.permission.WRITE_CALENDAR" />
     <uses-permission android:name="android.permission.READ_CALENDAR" />

**Comment by MoOx** [comment]
Please use ``` to share blocks of code

**Comment by afanchamp** [comment]
@MoOx

**Comment by wmcmahan** [comment]
@afanchamp The error seems to suggest that maybe `RNCalendarEvents` is null, rather than an error in the permissions calls. Maybe a setup step was accidently missed? The usual cause of this is the library not getting properly linked within the project.

**Comment by MoOx** [comment]
(@afanchamp look up your comment again (try editing to see raw code), you will learn a trick or 2).

Yeah I agree with @wmcmahan, it seems something is incorrectly linked. Do you have Android Studio? Can you check if the module is visible in many place if correctly linked (if I am correct).
Example here

<img width="674" alt="image" src="https://user-images.githubusercontent.com/157534/109060237-76580380-76e5-11eb-9412-95b912f7fcc9.png">

**Comment by afanchamp** [comment]
@wmcmahan  React Native 0.60.0+, you will probably don't need to link it manually. 
i still tried to link manually followed each step.
@MoOx  i'm checking it on android studio

**Comment by afanchamp** [comment]
![Uploading Screenshot 2021-02-25 at 01.17.44.png…]()

**Comment by MoOx** [comment]
You posted before the upload was finished xD

**Comment by afanchamp** [comment]
<img width="1187" alt="Screenshot 2021-02-25 at 01 18 51" src="https://user-images.githubusercontent.com/44059218/109060609-6ea95680-7707-11eb-85de-7bda624cfe5f.png">

**Comment by MoOx** [comment]
Did you correctly clean & rebuild the project on your device or emulator? Not only reloading JS from an already built app, that's not enough, you need to rebuild native code.

**Comment by afanchamp** [comment]
@MoOx  @wmcmahan  i deleted node_modules and cleaned the android directory deleted the .gradle folder and now it works fine. Thank you for your time.
