### ISSUE TITLE
iOS simulator alert not working

### ISSUE THREAD

**Issue by amanthegreatone** [wmcmahan/react-native-calendar-events#37]
Hi,

Got the code to write an event in the calendar and the calendar event does show an alert of 30 min before but I did not get any alert message. Am I missing something? On Android device the same code gives a nice alert notification.
My first time dabbling with iOS so don't know if this is how it is in simulator.

RN 0.40.0
iPhone6 iOS 10.1

**Comment by wmcmahan** [comment]
Hi @amanthegreatone, not sure if you resolved this yet? Make sure that you have "event alert" enabled for the calendar where the event is saved.

**Comment by amanthegreatone** [comment]
I will test it out on a real device and update if any issues. Simulator does not seem to give me an alert even when I add an event directly in the calendar. The calendar has event alert enabled and there is only 1 calendar on the sim.
