### ISSUE TITLE
Add ability to subscribe to a remote ics calendar

### ISSUE THREAD

**Issue by pierre-moire** [wmcmahan/react-native-calendar-events#38]
It would be awesome if through this library we could add a remote calendar subscription (.ics file for instance).

What do you think about it?

**Comment by wmcmahan** [comment]
Yes, i think this would be a nice feature! I think for iOS this is somewhat straightforward, but not sure about Android. I will look into though.

**Comment by wmcmahan** [comment]
Moving this to #165
