### ISSUE TITLE
you don't have permissions to add an event to the users calendar (Android)

### ISSUE THREAD

**Issue by mubashiralisiddiqui** [wmcmahan/react-native-calendar-events#382]
### Mac

 "react-native": "0.63.3",
 "react-native-calendar-events": "^2.1.2",

### Steps to Reproduce
install the Package 
try to save the events in the native calendar of android
you will get the error while saving the events

```js
import RNCalendarEvents from 'react-native-calendar-events';

saveEvent(title, details) {
    RNCalendarEvents.checkPermissions(readOnly = true)
      .then((status) => {
        const isAuthorized = status === 'authorized' ? true : false; // getting true no issue here
        // i am getting isAuthorized =true
        if (isAuthorized) {
          RNCalendarEvents.saveEvent(title, details)
            .then((result) => {
              console.log(result)
            })
            .catch((e) => {
              // gettting error here 
              console.log("reject==>", e)
              //Error: you don't have permissions to add an event to the users calendar
              reject(e);
            })
        }

      }).catch((err) => {
        console.log("reject==>", err)
      })

  },
```

**Comment by mubashiralisiddiqui** [comment]
@MoOx I have also tried removing the parameter 
can you please let me know what is the right way to do it I have read the docs working fine in IOS
I have also added in my manifest file but it didn't work
 <uses-permission android:name="android.permission.READ_CALENDAR" />
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />

**Comment by MoOx** [comment]
Please read carefully this section https://github.com/wmcmahan/react-native-calendar-events#read-only-requestpermissions-android-only
You *should not* follow this section to have write access.
In case another package is doing the opposite by removing it, try adding it.

**Comment by MoOx** [comment]
Also check at the merged `AndroidManifest.xml` during the build to find if something is reverting this WRITE_CALENDAR permission.
Also, checkPermission is not enough, you might need to use `requestPermission`

**Comment by mubashiralisiddiqui** [comment]
I have understand the section which you are talking about  and i have not added that line
`
<uses-permission tools:node="remove" android:name="android.permission.WRITE_CALENDAR" />
`

**Comment by mubashiralisiddiqui** [comment]
i have first requested 
  `RNCalendarEvents.requestPermissions()`
  then I use `RNCalendarEvents.checkPermissions()`

**Comment by MoOx** [comment]
did you `requestPermissions` with the right permission in the manifest? Please check the merged AndroidManifest.

**Comment by mubashiralisiddiqui** [comment]
can you give me an example of how to do  make the request with the right permission in manifest
and when you said merged AndroidManifest can you please explain a little about it I don't have an idea of it 
I have the Manifest file and I have an idea about that but no idea about merged Manifest
also, I am getting the status "undetermined" while checkPermission

**Comment by mubashiralisiddiqui** [comment]
here is my AndroidManifest.xml

`
manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="my packagename">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> 
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
    <uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
   <uses-permission android:name="android.permission.READ_CALENDAR" />
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />
    ..........
    .........
    ....
`

**Comment by MoOx** [comment]
Please read http://android-doc.github.io/tools/building/manifest-merge.html about merging.

Unless checkPermission return `authorized` saveEvent cannot work as expected.

Our module in theory already create the right permission  `android.permission.WRITE_CALENDAR` (that's why the readonly doc say to remove the permission if not wanted).
The only thing I see that can cause issue it something happening during manifest merging.

**Comment by mubashiralisiddiqui** [comment]
I don't know how to debug that manifest merging
when I pass the parameter for read-only then it's giving authorized else it's giving undetermined
and working without any issue in ios
if you have anything to suggest for debugging and resolving this issue please let me know

**Comment by mubashiralisiddiqui** [comment]
@MoOx I have re-implement the code delete my node_modules and clean  then I request permission and then it's working now
one thing which is having issues is the reminder/alarms  time set in android 
for ios, I am using `toISOString()` which is working fine but in android, it's not working 
I have tried with other formats like in minutes which  is working but I wanted to show the reminder in hours if the duration is in hours and in minutes if its in minutes
It saying currently like 10345 minutes before in alarms

can you tell me what is the time format for alarms in android

**Comment by MoOx** [comment]
use getTime()
