### ISSUE TITLE
[Proposals] iOS 8.2 crashes on fetchAllEvents

### ISSUE THREAD

**Issue by ethan605** [wmcmahan/react-native-calendar-events#39]
### Description

Got `BAD_ACCESS` exception on iOS 8 when invoking `fetchAllEvents`

```
#0	0x00000001006cb684 in -[RNCalendarEvents serializeCalendarEvents:] at RNCalendarEvents.m:331
```

```objc
NSDictionary *emptyCalendarEvent = @{
    _title: @"",
    _location: @"",
    _startDate: @"",
    _endDate: @"",
    _allDay: @NO,
    _notes: @"",
    _url: @"",
    _alarms: @[],                 <- Thread 1: EXC_BAD_ACCESS (code = 1, address=0x0)
    _recurrence: @""
};
```

### Solution

Change `NSArray` literal notation into `[NSArray array]` fixes this. I don't know why this happens because array literals notation is supported since Apple LLVM 4.0.

```diff
NSDictionary *emptyCalendarEvent = @{
    _title: @"",
    _location: @"",
    _startDate: @"",
    _endDate: @"",
    _allDay: @NO,
    _notes: @"",
    _url: @"",
-   _alarms: @[],
+   _alarms: [NSArray array],
    _recurrence: @""
};
```

### Additional Information

    React Native version: 0.39.0
    Platform: iOS 8.2 (12D508)
    Operating System: MacOS 10.12 (16C67)

**Comment by wmcmahan** [comment]
Thanks @ethan605, I've pushed a patch out with this fix included. Cheers!
