### ISSUE TITLE
requestCalendarAccess callback fires before user interacts with dialog

### ISSUE THREAD

**Issue by nicinabox** [wmcmahan/react-native-calendar-events#4]
Logging out `auth` and `error` from the callback when `requestCalendarAccess` is called. The callback seems to be called immediately. Not sure if that's the intended behavior, but it seems more useful to get the access state after a selection is made.

<img width="555" alt="screen shot 2016-03-06 at 5 33 41 pm" src="https://cloud.githubusercontent.com/assets/246280/13558116/b0cd41fe-e3c1-11e5-9bef-77ce478d5a9e.png">

**Comment by wmcmahan** [comment]
Ah yes, you're definitely right about that. Auth state should come back after selection is made. I will take a look at handling this asyc behavior. Thanks!

**Comment by nicinabox** [comment]
Thanks @wmcmahan!

**Comment by wmcmahan** [comment]
@nicinabox I've pushed a patch to handle the callback after authorization selection. Note, the callback status param is no longer a BOOL, but an object with status as a string, "denied" or "authorized". I've also added another method, `authorizationStatus`, to get current the auth state.

**Comment by nicinabox** [comment]
Thanks @wmcmahan all good now :+1:
