### ISSUE TITLE
Add IS_PRIMARY to "findEventCalendars" for Android

### ISSUE THREAD

**Issue by ryngds** [wmcmahan/react-native-calendar-events#41]
As an enhancement can you add IS_PRIMARY as an available field for android when fetching calendars. This would allow us to add events to the user's primary calendar.

Thanks,

**Comment by wmcmahan** [comment]
Thanks @ryngds, good idea. Yes, I can add this field for Android.

**Comment by EricCarrGH** [comment]
It would also be awesome to add the allowsModifications property to the result to match iOS's result.

Basically, read CalendarContract.Calendars.CALENDAR_ACCESS_LEVEL
and do this:

```
allowsModification = 
   accessLevel == CalendarContract.Calendars.CAL_ACCESS_OWNER ||
   accessLevel == CalendarContract.Calendars.CAL_ACCESS_EDITOR ||
   accessLevel == CalendarContract.Calendars.CAL_ACCESS_CONTRIBUTOR ||
   accessLevel == CalendarContract.Calendars.CAL_ACCESS_ROOT;
```

Psuedo code above based on this link:

http://stackoverflow.com/questions/36628556/for-calendars-content-uri-how-to-detect-if-calendar-is-read-only

**Comment by wmcmahan** [comment]
Thanks @EricCarrGH and @ryngds, I've pushed out this change and also updated an incorrect property name correctly from `calendarId` to `calendar`, per the readme. You should now find the members `isPrimary` and `allowsModifications` in the results.

**Comment by EricCarrGH** [comment]
Thanks Will!
