### ISSUE TITLE
Android 9/10 - not saving to google calendar, no errors, no crashing

### ISSUE THREAD

**Issue by jeveloper** [wmcmahan/react-native-calendar-events#412]
This happens in a production build distributed through google play.

### Environment

  Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.8.0 - ~/.asdf/installs/nodejs/17.8.0/bin/node
    Yarn: Not Found
    npm: 8.5.5 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.05.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users//.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 31.0.0, 31.0.0, 33.0.0, 33.0.0, 33.0.0
      System Images: android-29 | Google Play ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: javac 18 - /Users//.asdf/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to Reproduce

1. Save new calendar event 2. 
2. Calendar event briefly shows up (3 seconds) 3. 
3. Disappears immediately 

### Expected Behavior

Saves to calendar event ( works fine on android 11, 12, galaxy s10 and pixels)

### Actual Behavior

Calendar event does not appear in the calendar.

**Comment by jeveloper** [comment]
Update:

What seems to resolve this is 

//For those using Generators (saga)
let calendars = yield call(RNCalendarEvents.findCalendars); 


let calendars = await RNCalendarEvents.findCalendars();

      let pickedCal = calendars.find(r => r.isPrimary && r.allowsModifications);


... part of payload 

calendarId: Platform.OS === 'android' ? pickedCal.id : undefined,

**Comment by lordkhyron** [comment]
> Update:
> 
> What seems to resolve this is
> 
> //For those using Generators (saga) let calendars = yield call(RNCalendarEvents.findCalendars);
> 
> let calendars = await RNCalendarEvents.findCalendars();
> 
> ```
>   let pickedCal = calendars.find(r => r.isPrimary && r.allowsModifications);
> ```
> 
> ... part of payload
> 
> calendarId: Platform.OS === 'android' ? pickedCal.id : undefined,

I have the same problem..., May you explain better the "solution" , thanks

**Comment by jeveloper** [comment]
@lordkhyron Hi there
Ok i will try to clarify.

Android Native API call requires a calendar ID and in most cases it will use a default primary calendar.
For IOS you don't need to specify calendar, primary default one will be used.

You probably want to know the previous call, its this to pull all calendars available on the device.
let calendars = yield call(RNCalendarEvents.findCalendars);

This is just a Promise based call to get calendars with titles and Ids and has isPrimary (true/false)
