### ISSUE TITLE
Unable to use API on Android - "TypeError: null is not an object" for every API call

### ISSUE THREAD

**Issue by rosenpin** [wmcmahan/react-native-calendar-events#416]
### Environment

(node:76577) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 114.45 MB / 16.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 26, 28, 29, 30, 31, 32
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.2, 30.0.3, 33.0.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Arctic Fox 2020.3.1 Patch 3 Arctic Fox 2020.3.1 Patch 3
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.3 => 0.69.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to Reproduce

I just created a project, copied the example JS code and ran it.
I'm running on Android and I also tried the manual linking process mentioned in the README. Still didn't work.  
Missing something?

### Expected Behavior

The API calls should work

### Actual Behavior

Getting 
``` ERROR  [TypeError: null is not an object (evaluating 'RNCalendarEvents.requestPermissions')]

 ERROR  [TypeError: null is not an object (evaluating 'RNCalendarEvents.checkPermissions')]
```
for every API call

**Comment by rosenpin** [comment]
My bad.  
I was using Expo.

**Comment by Seanmclem** [comment]
I had this issue, on iOS too, because I forgot to run `pod install`. Afterwards, it worked fine.
