### ISSUE TITLE
Any alternatives or update plan?

### ISSUE THREAD

**Issue by on29-dev** [wmcmahan/react-native-calendar-events#447]
-en-
There is last update in 2 years ago. I think the libarary has not been managed any more.
Do you know the alternatives or do you have any plan about this library?

-ko-
최신 업데이트가 2년 전이네요. 더이상 관리되지 않는 느낌입니다. 혹시 대체 라이브러리에 대해 아시는 분 계실까요? 혹은 이 라이브러리 업데이트 계획같은게 있을까요?

**Comment by fendermany** [comment]
learn kotlin & swift - good alternative  ;)

**Comment by dgreasi** [comment]
It seems that for now a combination of 2 libs is solving the current issues. [This](https://medium.com/@davidapears/add-to-calendar-in-reactnative-ios-android-2479f2830666) article helped me.

**Comment by ChengBenj** [comment]
Hi, I believe the best alternative is fork this repo and create a new package, same as [react-native-fbsdk-next](https://github.com/thebergamo/react-native-fbsdk-next/) did.

**Comment by on29-dev** [comment]
-ko-
안녕하세요.
@fendermany 의 말이 맞습니다. 결국 전 직접 구현했습니다😆 생각보다 어렵진 않으니 간단한게 사용할거라면 직접 네이티브 모듈을 직접 구현하는 것을 추천드립니다.

만약 여의치않다면 가장 나이스한 대안은 https://github.com/vonovak/react-native-add-calendar-event 여기가 가장 괜찮은 것 같습니다.
(@dgreasi 의 아티클도 큰 도움이 됩니다. 감사링)

-en-
Hello,
Unfortunately, @fendermany you are right.
Native is more than the library. I ended up developing and using it myself. Making a native module is easy than I expected. So I recommend making a native module yourself.

If not, I think the best alternative is https://github.com/vonovak/react-native-add-calendar-event here.
(@dgreasi Thank you!)
