### ISSUE TITLE
Unable to save events in Android, event values must include a calendar _id error.

### ISSUE THREAD

**Issue by soorajvnair** [wmcmahan/react-native-calendar-events#45]
Hey @wmcmahan Facing this issue in Android, RN 0.40, Android 6.0, as per my understanding, if you do not specify a calendar id, the default device calendar is used, but unfortunately, i'm getting this error. Any ideas?
![screen shot 2017-02-13 at 1 37 03 pm](https://cloud.githubusercontent.com/assets/4268932/22875434/aec2e73a-f1f1-11e6-8f9c-896ef22e5eb2.png)
Worked like a charm in IOS, and btw Great work on this module. 👍

**Comment by wmcmahan** [comment]
Hey @soorajvnair, yes looks like that is a bug. I will push out a fix for that today. Thanks!

**Comment by soorajvnair** [comment]
Thanks @wmcmahan !!.

**Comment by wmcmahan** [comment]
@soorajvnair, this fix is now out on release 1.3.5. Thanks!
