### ISSUE TITLE
NativeModules.CalendarEvents return "undefined". 

### ISSUE THREAD

**Issue by AndrewMigal** [wmcmahan/react-native-calendar-events#46]
For me in Android CalendarEvents.java didn't added to Native Modules. So `var CalendarEvents = NativeModules.CalendarEvents` call in React library returns undefined. 
Set up properly.
Version: 
react-native-cli: 2.0.1
react-native: 0.41.2

**Comment by retdop** [comment]
I've got the same issue. Did you find a find?

**Comment by retdop** [comment]
Got the same issue, the "react-native link" didn't work properly, I had to do it manually
