### ISSUE TITLE
Google Cal & Exchange

### ISSUE THREAD

**Issue by rdewolff** [wmcmahan/react-native-calendar-events#47]
Hello

First, thanks for building such a react-native code and share it.

Will it find calendars and thus events of Google Calendar and MS Exchange calendar if the device has them configured?

Cheers!

**Comment by wmcmahan** [comment]
Thanks @rdewolff, yes it should be able to find those events. Using the `findCalendars` method, you can see the calendars available.

**Comment by rdewolff** [comment]
Thanks for your reply!

**Comment by hans0low** [comment]
How would you save an event to the specific Google calendar?

**Comment by wmcmahan** [comment]
@hans0low You will need to define a `calendarId` property with the identifier of a calendar.

```javscript
RNCalendarEvents.saveEvent(this.state.formData.title, {
  ...
  calendarId: 'FE6B128F-C0D8-4FB8-8FC6-D1D6BA015CDE'
})
```

**Comment by hans0low** [comment]
Thanks a ton @wmcmahan! If I were to attach a file (like a jpg) to the event as well, would that file have to be on google drive?

**Comment by wmcmahan** [comment]
No, unfortunately there is no way to attach files to the calendar event.

**Comment by hans0low** [comment]
Ahh alright, thanks again!
