### ISSUE TITLE
Error getting default calendar for new events

### ISSUE THREAD

**Issue by guilhermemello** [wmcmahan/react-native-calendar-events#49]
Hi,
I'm getting this error:

Error getting default calendar for new events: Error Domain=EKCADErrorDomain Code=1013 "(null)"
2017-03-10 17:58:17.542 [info][tid:com.facebook.react.JavaScript] errorError: No calendar has been set.

Already linked the libraries on XCode.

Can I solve this problem ?
Thanks.

**Comment by wmcmahan** [comment]
@guilhermemello, you will need to authorize access to the calendar for trying to access it. You can use the `authorizeEventStore` method to prompt authorization.

**Comment by guilhermemello** [comment]
@wmcmahan you're right man.
Thanks for the support.
