### ISSUE TITLE
Add autoformatting for dates

### ISSUE THREAD

**Issue by mienaikoe** [wmcmahan/react-native-calendar-events#50]
Hey all. Really useful library, and I've loved it so far.

One thing I've found that was a little annoying at first was having to format the start and end date strings when saving an event. I've made a decision to avoid moment.js as I really don't do a lot of work with dates in my app, and I didn't want the extra code size. I also found out the hard way that react-native-calendar-events requires strings for start and end because there was an NPE when I supplied a Date for start and end.

I ended up having to write a custom formatter for this, and it looks like you guys parse this string into a native Date object afterward anyway. I would love to supply a javascript Date object or even an epoch long to represent dates for `saveEvent`

**Comment by wmcmahan** [comment]
Hey thanks, @mienaikoe. React Native handles converting these dates values to native over the native bridge, so we lose some control over what or how things get parsed. You could use your date object's 'getTime' to get a unix timestamp or 'toISOString' method to give you an ISO formatted string. Either should work.

**Comment by misogl** [comment]
`toISOString` works on both Android and iOS. Unix timestamps returned by `getTime` are supported only on iOS.

**Comment by mienaikoe** [comment]
So I can't use ISO because I need to conserve the timezone used by the phone, hence my problem.

**Comment by xwartz** [comment]
Any update news for this issue?

**Comment by wmcmahan** [comment]
iOS and Android should now allow for timestamps as well as ISO strings in 1.4.0. Closing for now, but please reopen issues are found around this.
