### ISSUE TITLE
FindCalendars not listing calendars on iOS

### ISSUE THREAD

**Issue by nbastoWM** [wmcmahan/react-native-calendar-events#51]
Hi,

On Android I can list all my device calendars, even the "Contacts" calendar. But on iOS the FindCalendars returns an empty array. I tried on different iOS devices configured with iCloud and Google calendars but the list is always empty.

My code:

```
   RNCalendarEvents.authorizationStatus()
      .then(status => {

        RNCalendarEvents.findCalendars()
          .then(calendars => {
            console.log('CALENDARS:', calendars);
            this.setState({
              calendars,
            });
            if (calendars.length > 0){
              this._selectCalendar(calendars);
            } else {
              Alert.alert(this.props.title, 'No calendars defined.')
            } 
          })
          .catch(error => {
            console.log('ERROR!', error);
          });

      })
      .catch(error => {
        console.log('ERROR!', error);
      });
```

**Comment by wmcmahan** [comment]
Hey @nbastoWM,  the 'authorizationStatus' method returns the current authorization status. To set the authorization status you must use the 'authorizeEventStore' method.

**Comment by nbastoWM** [comment]
Thanks! 
I thought authorizationStatus would already ask for calendar permission.
