### ISSUE TITLE
Error: No calendar has been set.

### ISSUE THREAD

**Issue by mehdyMa** [wmcmahan/react-native-calendar-events#52]
Hey all,
I am trying to add events to the user calendar via my React Native app.
But I am getting an error saying No calendar has been set after calling RNCalendarEvents.saveEvent (), and when trying to request calendar authorization with RNCalendarEvents.authorizeEventStore()
my app crashes.

Regards,
Mehdi

**Comment by wmcmahan** [comment]
Hey @mehdyMa, is this on iOS? If so, make sure you update the your app's [plist](https://github.com/wmcmahan/react-native-calendar-events#ios) (referenced at the bottom of this paragraph). Then you should be able to successfully authorize and save events.

**Comment by mehdyMa** [comment]
@wmcmahan Hey,
Yeah thank you man, it worked for me 👍  :)

**Comment by ycman0307** [comment]
I also tried to update plist but still same error. did i miss any step.

in "Info.plist"
added key "Privacy -Calendars Usage Description"
added value "This app requires access to the calendar"

**Comment by ldco2016** [comment]
If you guys are referring to this:

	```
<key>NSCalendarsUsageDescription</key>
	<string>This app requires access to the calendar</string>
```

I already have that in my application and I am getting the same exact issue as @mehdyMa and its happening for me both in iOS and Android.

**Comment by sushantubale** [comment]
Error creating and saving new reminder : Error Domain=EKErrorDomain Code=14 "Calendar has no source" UserInfo={NSLocalizedDescription=Calendar has no source}

**Comment by jcexk** [comment]
> Error creating and saving new reminder : Error Domain=EKErrorDomain Code=14 "Calendar has no source" UserInfo={NSLocalizedDescription=Calendar has no source}

Did you solve this problem? I have the same problem
