### ISSUE TITLE
Unable to delete calendar in Android (with fix)

### ISSUE THREAD

**Issue by EricCarrGH** [wmcmahan/react-native-calendar-events#53]
Hi,

I was receiving an error when deleting an event in Android using the removeEvent() call.

I fixed it by passing **null** instead of **selection** in the second param to cr.delete, in CalendarEvents.java:

Old
```
        String selection = "((" + CalendarContract.Events.DELETED + " != 1))";
        int rows = cr.delete(uri, selection, null);
```

Fixed
```
        int rows = cr.delete(uri, null, null);
```

Please review to include in a later release. I found this solution by googling - I am not an expert on Android calendars.

**Comment by wmcmahan** [comment]
Hey @EricCarrGH, I believe this bug has already been fixed. Are you on v1.3.6?

**Comment by EricCarrGH** [comment]
Indeed, it is fixed in the latest. Thanks!
