### ISSUE TITLE
(Android) Calendar events appear as birthdays

### ISSUE THREAD

**Issue by tomerlevi444** [wmcmahan/react-native-calendar-events#54]
on Android Nougat, events that are added to the calendar show as birthdays

**Comment by wmcmahan** [comment]
Hey @tomerlevi444, are you specifying the calendar id when saving?

```javascript
RNCalendarEvents.saveEvent('name', {
  calendarId: 2,
  ...
});
```

**Comment by tomerlevi444** [comment]
No, is it required?

**Comment by wmcmahan** [comment]
Without specifying the calendar id, it will save to the default calendar. You can use `findCalendars` to see the available calendars on the device. Then assign the calendarId property with the desired calendar.

**Comment by tomerlevi444** [comment]
Although I specify a startDate and endDate for the event, the default calendar on Android Nougat still shows it as a full-day birthday event. Are you suggesting it's a problem with Android Nougat's default calendar?

**Comment by wmcmahan** [comment]
I would recommend explicitly defining the calendar you want to save to.

**Comment by amanthegreatone** [comment]
just want to know how would you distinguish between all the available calendars? is there any way to get a user input on their choice where they would like to save the events?

**Comment by wmcmahan** [comment]
@amanthegreatone, you can find the available calendars with the [findCalendars](https://github.com/wmcmahan/react-native-calendar-events#findcalendars) method.

**Comment by amanthegreatone** [comment]
yeah i found that, but there is no way to know the preferred calendar for the user. Default calendars might not always be the best option for an app, so wanted to know if there is a way to ask the user for their preference. Or is there a way to create a calendar named after the app as another option?

**Comment by wmcmahan** [comment]
Using the findCalendars method to present the user with calendar options and storing the choice for future use is one way to handle it. Creating a specific calendar for the app is another, although outside the scope of this lib.

**Comment by tomerlevi444** [comment]
Thank you.

**Comment by fufuninja** [comment]
hey there, I am still experiencing this bug. Let's assume I only have the Google Calender app on my Nexus phone. Even after specifying the parameter calenderID: '1',  it appears in Google Calender as birthday.

**Comment by wmcmahan** [comment]
Hey @fufuninja, try `calendarId` instead of `calenderID`.

**Comment by fufuninja** [comment]
hey @wmcmahan, thanks for responding, yes I'm using calendarId, sorry for the typo.

**Comment by wmcmahan** [comment]
When you use `findCalendars` to see what calendars are available, are there any other writable calendars? The calendar with id = 1 is the default when creating events.

**Comment by fufuninja** [comment]
Yes, default is Google Calender. But there's this bug when Google Calender is in default. It doesn't save properly into Google Calender. Instead it ends up as Birthday as shown in the images below.
[https://ibb.co/c36MB7](url)
[https://ibb.co/eVUxjS](url)
