### ISSUE TITLE
Fatal Exception on event adding

### ISSUE THREAD

**Issue by qmegas** [wmcmahan/react-native-calendar-events#56]
My application stop working when I try to add new event into calendar.

Here call example:
```js
RNCalendarEvents.saveEvent('Test', { 
	location: 'New York, United States',
	startTime: '2017-03-29T10:30:00.000Z',
	endTime: '2017-03-29T11:30:00.000Z',
	description: 'Test description' 
});
```
Here the exception description from logcat:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getLastPathSegment()' on a null object reference
    at com.calendarevents.CalendarEvents.addEvent(CalendarEvents.java:308)
    at com.calendarevents.CalendarEvents$2.run(CalendarEvents.java:510)
    at java.lang.Thread.run(Thread.java:818)
```

Library version: 1.3.6
React Native: 0.42

**Comment by wmcmahan** [comment]
Hey @qmegas, does your device have any calendars setup? My guess is that its trying to save to a nonexistent calendar.

**Comment by qmegas** [comment]
Hey @wmcmahan,
Yes, it have. For example `fetchAllEvents` function works fine.

**Comment by wmcmahan** [comment]
Oh, I see. You need to be using `startDate` and `endDate` keys. You are currently using `startTime` and `endTime`.

**Comment by qmegas** [comment]
@wmcmahan, Yes you right. That what caused the application crash.
In my opinion it should be handled in java code and return an error by promise.reject

In addition (according to ISO 8601) if I provide time in a little different format like that `2017-03-30T10:30:00-04:00`, but not `2017-03-30T10:30:00.000Z`, I receive promise reject error `Unparseable date: "2017-03-30T10:30:00-04:00"` however application still crashes 

```
java.lang.NullPointerException: Attempt to invoke interface method 'int com.facebook.react.bridge.WritableMap.getInt(java.lang.String)' on a null object reference
    at com.calendarevents.CalendarEvents$2.run(CalendarEvents.java:515)
    at java.lang.Thread.run(Thread.java:818)
```
It will be very nice if library will support first version of time too, because it very convenient to use when you receiving data from server written in PHP. In PHP you have simple function `date('c')` which returns date in `2017-03-30T10:30:00-04:00` format.

**Comment by wmcmahan** [comment]
@qmegas, for date formatting you can do something like this:

```javascript
(new Date('2017-03-30T10:30:00-04:00')).toISOString()
``` 

Not very clean, though. I will try to develop a better way to handle various date formats.

**Comment by nwaughachukwuma** [comment]
Hi @wmcmahan please am battling with the date format. Please what's acceptable. My server pushes yyyy-mm-dd hh:mm:ss. What's the best way to convert this to an acceptable format. I have used moment(start_date) and (new Date(start_date)).toISOString(), yet the App crashes. I think this should be simplified. Thanks

**Comment by wmcmahan** [comment]
Hi @nwaughachukwuma converting it to ISO format `YYYY-MM-DDT00:00:00.000Z` should work. What is the error log you get with the crash?

**Comment by nwaughachukwuma** [comment]
I guess it's not the date format afterall, cause I saw this:
`java.lang.ClassCastException: V alue for id cannot be cast from Double to String`

I was passing uuid and it didn't recognize it, now am passing the id and it gives the error above.

**Comment by wmcmahan** [comment]
The id value must be a string (for old reasons). Also, by using the id property it will try and update an existing event, not create a new event with the id. Hope this helps.
