### ISSUE TITLE
[iOS] Working in debug but error when deployed (hockey app)

### ISSUE THREAD

**Issue by xavierlefevre** [wmcmahan/react-native-calendar-events#57]
Hello,

I'm having a little issue hard to debug.

React native calendar events works quite well on my dev env but once the app deployed through hockey app, the add to calendar does not work on iOS and leaves me with an error.

Find below a screenshot of the error:
![img_8311](https://cloud.githubusercontent.com/assets/14938214/24451246/4de4c0b4-147e-11e7-8335-a7953392e4b9.PNG)

Like that for the moment I did not find a way to be able to reproduce this error and access it on my dev env, so I'm looking for your help.

Would you have any idea why this happens ?

Thanks,

Xavier

**Comment by wmcmahan** [comment]
Hi @xavierlefevre 

What iOS version are you running in your dev environment and what iOS version is the device in the screenshot? Most of the crashes that I've seen when saving an event on iOS have been due to iOS 10 requiring a Info.plist value for the calendars usage permission.

**Comment by wmcmahan** [comment]
@xavierlefevre, it seems you have the usage permission set if its running of iOS 10.3 in the simulator. I've not been able to reproduce a crash from my phone, although I'm installing directly from XCode. Unfortunately, It's difficult to identify the source of the crash with symbolicated logs.

**Comment by shakyShane** [comment]
@xavierlefevre make sure you're encoding the date correctly 

I noticed in debug mode (when your JS is being executed by V8) the date is serialised differently, this will be why it crashes in prod, but not in debug.

I fixed our issue by doing `new Date(someTimestamp).toISOString()` on the date property
