### ISSUE TITLE
Create event with alert/travel time set

### ISSUE THREAD

**Issue by tonatiuh** [wmcmahan/react-native-calendar-events#58]
I checked the documentation, but I didn't see a way to save and event (https://github.com/wmcmahan/react-native-calendar-events#saveevent) with an alert set (for ex. "2 hours before the event") and/or travel time (ex. "5 minutes"). 

Does this package support passing parameters for that?

**Comment by wmcmahan** [comment]
@tonatiuh is this what you're looking for? [Create Calendar Event with Alarm](https://github.com/wmcmahan/react-native-calendar-events#create-calendar-event-with-alarms)

**Comment by tonatiuh** [comment]
Absolutely, thanks!

**Comment by tonatiuh** [comment]
Any plan to add support for the "Travel time" setting soon?
<img width="378" alt="screen shot 2017-03-31 at 10 36 20 pm" src="https://cloud.githubusercontent.com/assets/602727/24575429/8cd1bcec-1662-11e7-8a4b-da47840faf28.png">

**Comment by wmcmahan** [comment]
@tonatiuh, I believe the native iOS calendar "travel time" UI is simply adjusting the alarms relative offset based on selected amount of time (or estimated time travel time, if a location is set). This can be achieved by simply updating or saving an event with the alarm date calculation as an offset like:

```javascript
RNCalendarEvents.saveEvent('title', {
  ...
  alarms: [{
    date: -30
  }]
})
```
