### ISSUE TITLE
Is that possible to saveEvent not as a birthday in Android default calendar?

### ISSUE THREAD

**Issue by zalesky** [wmcmahan/react-native-calendar-events#62]
"react-native-calendar-events": "1.3.6"
"react-native": "0.41.2"

I'm using Android 6.0.1 device and this code
```
 RNCalendarEvents.findCalendars().then(calendars => {// handle calendars});
```
returns Array with Objects structured:
```
[{
  allowsModifications:false,
  id:"1",
  isPrimary:false,
  source:"emailSettedInCalendar@gmail.com",
  title:"Contacts",
},{
  allowsModifications:false,
  id:"2",
  isPrimary:false,
  source:"emailSettedInCalendar@gmail.com",
  title:"Holidays in Ukraine"
},...]
``` 
If I write calendarId (I tried all id's) when save event my app shutting down and not save event.
If I not write it, the event appears as birthday (like in https://github.com/wmcmahan/react-native-calendar-events/issues/54)
Code that saves events:
```
RNCalendarEvents.saveEvent(`title`, {
  location: `location`,
  notes: `location`,
  startDate: ISOFormattedDate,
  endDate: ISOFormattedDate
}).then(res=>console.log(res)).catch(error => {
  console.log(error);
});
```

in IOS works well. Any suggestions about how to save event not as birthday in default calendar?
Also this events dissapears from default calendar after some time.

**Comment by wmcmahan** [comment]
Hi @zalesky, when you save the event like this, it crashes? Note, calendarId is a string. 

```javascript
RNCalendarEvents.saveEvent(`title`, {
  calendarId: '3',
  location: `location`,
  notes: `location`,
  startDate: ISOFormattedDate,
  endDate: ISOFormattedDate
})

**Comment by zalesky** [comment]
@wmcmahan 10q a lot for answer. Specifying calendarId as a string solves problems with birthday looking and at first sight whith disappearing events 😃  great👏
