### ISSUE TITLE
How to save multiple events?

### ISSUE THREAD

**Issue by kenvandemar** [wmcmahan/react-native-calendar-events#63]
For single event, I save to device without any problems.
But when I try to save many events in the array, it fails.
console complains: TypeError: Cannot read property 'alert' of undefined
Here is my Code: 
 
 ```
saveCalendar() {
        console.log('RAC', this.props.eventops);
        const myCalendar = this.props.eventops;
        myCalendar.forEach(cal => {
            //console.log('THE CAL', cal);
         let evtDate = new Date(cal.EventDate);
             evtDate = evtDate.toISOString();
              console.log('THE CAL', evtDate);
 
        let evtEndDate = new Date(cal.EventEndDate);
        evtEndDate = evtEndDate.toISOString();
          console.log('THE CAL', evtEndDate);
           
            RNCalendarEvents.saveEvent(`Abu Dhabi - ${cal.Title}`, {
                location: `${cal.Location}`,
                notes: `${cal.Text}`,
                startDate: `${evtDate}`,
                endDate: `${evtEndDate}`
            })
            .then(id => {
                AlertIOS.alert('Announcement', 'Add the event Successfully!', console.log(id));
            })
            .catch(error => {
            console.log(error);
        }, setTimeout(() => {
            this.popupDialog.closeDialog();
        }, 50));
        });
    }

```

**Comment by wmcmahan** [comment]
From the error, it looks like `AlertIOS` is undefined in your code.

**Comment by kenvandemar** [comment]
Well, it is already defined on top. As I said, everything work well with single event, but not with multiple. Please help!

**Comment by wmcmahan** [comment]
Ok well, i'm assuming that this code is for iOS. Are there any errors logged in XCode's console? Did the application crash when trying to save multiple events?

Since this is a TypeError, I would suggest looking through your code and trying to resolve the undefined object.

**Comment by kenvandemar** [comment]
The good news is when I remove AlertIOS.alert, it saves events successfully. Tomorrow, I will try to use other method to tell user about the result. Let see how.
