### ISSUE TITLE
cannot set when recurring event ends

### ISSUE THREAD

**Issue by RyanWan** [wmcmahan/react-native-calendar-events#66]
`RNCalendarEvents.saveEvent('title', {
    location: 'location',
    notes: 'notes',
    startDate: '2017-05-20T19:26:00.000Z',
    endDate: '2017-05-20T20:26:00.000Z',
    alarms: [{
      date: -1 // or absolute date - iOS Only
    }],
    recurrence: 'daily'
  })`
This will create a recurring event from 19:26 to 20:26 daily. And it goes on forever.
In your RNCalendarEvent.m, you set the end date to be nil,
`  if ([validFrequencyTypes containsObject:frequency]) {
        rule = [[EKRecurrenceRule alloc] initRecurrenceWithFrequency:[self frequencyMatchingName:frequency]
                                                            interval:1
                                                                 end:nil];
    }`
which means the recurring event goes on forever. 
Can you update this part to allow user to set an end date.

**Comment by wmcmahan** [comment]
Thanks @RyanWan. Yes, you're correct. Its looks like it could use some parameters. The same for Android, as well. I will look into creating something like `recurrenceInterval` and `recurrenceEnd` as optional params.

**Comment by zalesky** [comment]
@wmcmahan https://tools.ietf.org/html/rfc5545#section-3.8.5.3
Need to set parameter UNTIL= here https://github.com/wmcmahan/react-native-calendar-events/blob/master/android/src/main/java/com/calendarevents/CalendarEvents.java#L410

**Comment by wmcmahan** [comment]
@zalesky, yep. In the works, along with some other updates!

**Comment by zalesky** [comment]
@wmcmahan Can you give me advice how can I fast fix this on Android? It can be not very clear solution but for now it ok.

**Comment by wmcmahan** [comment]
@zalesky I push a new [android-recurrence](https://github.com/wmcmahan/react-native-calendar-events/tree/android-recurrence) branch with WIP changes for creating and reading recurrence rules. Hopefully this can help until I can get the next release out.

**Comment by wmcmahan** [comment]
These changes are now in 1.4.0.
