### ISSUE TITLE
[iOS] Error: calendar event request error

### ISSUE THREAD

**Issue by ethan605** [wmcmahan/react-native-calendar-events#72]
Hi, I've encountered this error in iOS only, Android just works fine

![simulator screen shot aug 7 2017 4 05 05 pm](https://user-images.githubusercontent.com/1215541/29020446-3599bf30-7b8c-11e7-8c1c-dff5974f293a.png)

I've added permissions in Info.plist for `NSCalendarsUsageDescription` key and got `authorized` for `authorizationStatus()`.

Here's my code which is rejected:

```javascript
const allEvents = await CalendarEvents.fetchAllEvents('2017-08-07T12:00:00.000Z', '2017-08-07T10:00:00.000Z');
```

This is very weird because I've successfully did this before, but recently it failed.

Any idea to solve this?

P/s: This is quite similar to #57 but appear on my both debug & release mode.

**Comment by ethan605** [comment]
Hi @wmcmahan, any update for this issue?

**Comment by wmcmahan** [comment]
@ethan605, I will take a look. Looking at the dates, they are the same. Could you try a longer date span? There may be an issue with empty results.

**Comment by ethan605** [comment]
@wmcmahan wow you're right. When I extend the time range to include at least 1 event, it works just fine.

So I think there's an accepted workaround here:

```javascript
async checkEventExisted(event, startDate, endDate) {
  try {
    const allEvents = await CalendarEvents.fetchAllEvents(startDate, endDate);
    
    // Return true or false normally here
  } catch (error) {
    // Return false because there's no event in this time range
    return false;
  }
}
```

**Comment by wmcmahan** [comment]
Yes, you will need to catch the error. Its [here](https://github.com/wmcmahan/react-native-calendar-events/blob/master/RNCalendarEvents.m#L649) that is causing the false error. If no events are found, it returns `nil` rather than an empty list, unfortunately.

**Comment by ethan605** [comment]
Thanks, I think it should return an empty list, or a more verbose error message. Hope that this will be resolved in the next update.
