### ISSUE TITLE
The react native module can call Android alarm clock？

### ISSUE THREAD

**Issue by yhw601071569** [wmcmahan/react-native-calendar-events#75]
![te d8x g8skt 5 7krdy55n](https://user-images.githubusercontent.com/22049095/29487368-52b09948-852a-11e7-9766-1db44cab66f2.png)，
Does this alarms mean calling the alarm clock? If so, can you set the alarm clock for Android?

**Comment by wmcmahan** [comment]
Hi @yhw601071569, this sets an alarm for the event on the calendar for both iOS and Android. If I understand your question correctly, it does not set your default "alarm clock" app, but it schedules a notification for the time set.

**Comment by yhw601071569** [comment]
thank you ， I understand  it
