### ISSUE TITLE
 CalendarEventsPackage is not abstract and does not override abstract method createJSModules() in ReactPackage

### ISSUE THREAD

**Issue by Sunjiawei58** [wmcmahan/react-native-calendar-events#76]
![problem 8 20](https://user-images.githubusercontent.com/13588480/29497052-69f2dc16-85a6-11e7-952c-23a87b38ca2d.png)

I installed the react-native -calendar-events as the instruction on the github page and after I run react-native run-android I got this error. Could anyone tell me how to solve it? My RN version is 0.46.

**Comment by wmcmahan** [comment]
@Sunjiawei58, if you are using the latest package version, you will need to use RN 0.47+.

**Comment by derryberni** [comment]
@wmcmahan i meet same problem, my project using react-native 0.46.4 what should i do ?

**Comment by wmcmahan** [comment]
@derryberni, you can use v1.4.1 until you are ready for RN 0.47+

**Comment by bilalsyed001** [comment]
Adding this fixes the issue RN0.45.x
`    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }`

**Comment by itinance** [comment]
+1 @bilalsyed001  

Also, this import is required:

`import com.facebook.react.bridge.JavaScriptModule;`
