### ISSUE TITLE
undefined is not an object (evaluating "RNCalendarEvents.authorizationStatus")

### ISSUE THREAD

**Issue by majd-kho** [wmcmahan/react-native-calendar-events#77]
React native version 0.46

I have installed the the module and linked it, but whenever i try to run this piece of code (below) i get this error message "undefined is not an object (evaluating "RNCalendarEvents.authorizationStatus")"
```
RNCalendarEvents.authorizationStatus()
      .then(status => {
        console.log(status)
      })
      .catch(error => {
       console.log(error)
      });
```

whats interesting is that its referencing the "authorizationStatus index.ios.js:10:28" file righ under the error message as the cause, but im using a create-react-native-app project to render on the expo app.

Note: im running this piece of code from within componentDidMount  method

**Update** 
This is what i've tried based on this previous closed issue  #28  

1. import RNCalendarEvents from 'react-native-calendar-events';
2. var RNCalendarEvents = NativeModules.RNCalendarEvents; (after importing NativeModules from react-native)
3. var { RNCalendarEvents } = require('NativeModules')
4. import RNCalendarEvents from "../RNCalendarEvents";

contents of RNCalendarEvents.js from point 4 
```
use strict';

import { NativeModules } from 'react-native';

var RNCalendarEvents = NativeModules.RNCalendarEvents;

export default RNCalendarEvents;
```

and the error message i would get is "undefined is not an object (evaluating "_RNCalendarEvents2.default.authorizationStatus")"

**Comment by wmcmahan** [comment]
@majd-kho, The most common cause of the module being 'undefined' in iOS is the package is not linked properly. If running `react-native link` is not working, you can try [linking it manually](http://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking). Also, be sure to have your privacy usage description for `Privacy - Calendars Usage Description`  defined in `Info.plist`.

**Comment by majd-kho** [comment]
will take a look, thank you

**Comment by martincarrera** [comment]
Hey @majd-kho, I was having the same issue that you have.

Ensure that you have this three libs linked in Xcode, build phases.

<img width="566" alt="screen shot 2017-08-25 at 12 37 56 pm" src="https://user-images.githubusercontent.com/6719062/29721180-8bf2dfe2-8992-11e7-92fe-a60092f32bb3.png">

I hope this helps!

**Comment by reilem** [comment]
@martincarrera I just had the same issue and this fixed it, thank you very much. I had already tried `react-native link` and that didn't work.

**Comment by tymadsen** [comment]
@wmcmahan  Is this module compatible with Expo? I am trying to accomplish the same thing as @majd-kho . I have tried following the manual linking directions, but there is no libRNCalendarEvents.a (all I see are RNCalendarEvents.m and RNCalendarEvents.h files) that I can find anywhere. As for android, I have been unable to locate the settings.gradle or a MainApplication.java, unless those are files I need to create in order to use the module. As far as I can tell this module would need to be Ejected from a create-react-native-app setup. Am I wrong? I am fairly new at react-native and iOS/Android development. Any help would be appreciated.

**Comment by wmcmahan** [comment]
It appears Expo has planned to add calendar events - [feature requests](https://expo.canny.io/feature-requests/p/calendar-api). To manually link library - follow RN docs [here](https://facebook.github.io/react-native/docs/linking-libraries-ios.html).
