### ISSUE TITLE
[Error] Removing Android event

### ISSUE THREAD

**Issue by itswaze** [wmcmahan/react-native-calendar-events#78]
When I try to remove an event on Android I get this error:

`TypeError: expected dynamic type `string', but had type `int64' (constructing arguments for CalendarEvents.removeEvent at argument index 0)`

But on iOS works just fine.

**Comment by wmcmahan** [comment]
@itswaze, it looks like you might be using a number rather than a string as the argument.

**Comment by itswaze** [comment]
@wmcmahan yep, it was that. Since it worked on iOS I thought it would work on Android. 
Fixed :) thank you!

**Comment by itswaze** [comment]
Just one more question, so I won't open a new issue.

When I try to add an event with:
```

startDate: utcDateToLocalString(moment.utc(startDateUTC).subtract(1, 'hours')),
endDate: utcDateToLocalString(moment.utc(startDateUTC)),
```

on Android, the app crashes. But if I use this:

```
startDate: '2017-08-23T15:00:00.000Z',
endDate: '2017-08-23T16:00:00.000Z',
```

it works. But I need to make it work the other way.

**Comment by wmcmahan** [comment]
Your going to want an ISO date string. With moment, I believe they have an `toISOString` method -
```javascript
moment(startDateUTC).subtract(1, 'hours').toISOString()

```

**Comment by itswaze** [comment]
that was it :) thank you, keep up the good work!
