### ISSUE TITLE
saveEvent OK but cannot see the event in Android Calendar

### ISSUE THREAD

**Issue by Sunjiawei58** [wmcmahan/react-native-calendar-events#79]
I set up the react-native-calendar-events package, 
when I called code below:
 RNCalendarEvents.saveEvent('title', {
            location: 'location',
            notes: 'notes',
            startDate: '2017-08-23T21:20:00.000Z',
            endDate: '2017-08-23T21:22:00.000Z',
            calendar: ['Calendar'],
            alarms: [{
              date: -1 // or absolute date - iOS Only
            }]
          }).then(id=>{
              console.log("the calendar id is "+id)
          });

I got the calendar id displayed on the console. But I didn't find the event in the Calendar app in Android. Any idea about this?

**Comment by wmcmahan** [comment]
@Sunjiawei58, is 'Calendar' the calendar ID you want to save to? You can call `RNCalendarEvents.findCalendars()` to find available calendars on the device.

**Comment by Sunjiawei58** [comment]
@wmcmahan I called RNCalendarEvents.findCalendars() this morning, and I got a list of events that my calendar has saved. it looks like this: 
![image](https://user-images.githubusercontent.com/13588480/29678140-1314793e-88c3-11e7-9b01-4efbceb6f2f0.png)
however still after I called saveCalendars(), I can't find the events in the Calendars app on my emulator device. should I set the calendar attribute to calendar: ['4'] in my situation?

**Comment by wmcmahan** [comment]
Yes, you should add the calendar ID to this list of calendars you wish to save it to. Also, it looks like only one calendar 'allowsModifications'.

**Comment by Sunjiawei58** [comment]
@wmcmahan  Should I add the event with alarm to the calendar that allowsModification?I tried to add the event to the calenders [1,2,3,4,5], and using fetchEvent() function to get the event that just added. but I only got events which is added to the calendar with title "Contacts" and id 1. The wired thing is when I opened the Calendar application on the device, I still can't see the events that I have added...

**Comment by wmcmahan** [comment]
@Sunjiawei58, have you authorized access to the calendar? You can check the status with
```javascript
RNCalendarEvents.authorizationStatus()
```
and request authorization with
```javascript
RNCalendarEvents.authorizeEventStore()
```

**Comment by Sunjiawei58** [comment]
@wmcmahan  Yes, I have added those code, and it returned me the status of "authorized"...

**Comment by Sunjiawei58** [comment]
@wmcmahan 
![image](https://user-images.githubusercontent.com/13588480/29684280-fa2e29d8-88d6-11e7-876c-3b868e01ebfb.png)
It seems like no matter which calendar I set to save the event to, I can only add event to the calendar with id 1 and title "Contact" which unfortunately not allowModification.
below is my code:
![image](https://user-images.githubusercontent.com/13588480/29684335-34a125c0-88d7-11e7-966f-594317c62cc0.png)

**Comment by Sunjiawei58** [comment]
@wmcmahan  finally I got it worked!! 
![image](https://user-images.githubusercontent.com/13588480/29685118-1591964e-88da-11e7-9720-a151bf57f281.png)
I dig the code and found I should change calendar to calendarId , the code is in below:
![image](https://user-images.githubusercontent.com/13588480/29685156-32170d80-88da-11e7-9476-e2d3f61df959.png)

**Comment by wmcmahan** [comment]
Ah yes, that is correct. The list of IDs is for lookup. Its been a while since i've used this API myself in a project. Glad you were able to solve it!

**Comment by TungUyenDo** [comment]
![sas](https://user-images.githubusercontent.com/34643360/36586905-0695dc38-18b6-11e8-99ec-ede4d2736dee.PNG)
calendar-title:'Contacts' can to change? what other calendar-title?
