### ISSUE TITLE
Events are not visible on calendar

### ISSUE THREAD

**Issue by soniaparikh** [wmcmahan/react-native-calendar-events#8]
I am adding event with RNCalendarEvents.saveEvent, but its not setting on my calendar. I am using iOS simulator to test my code.

**Comment by wmcmahan** [comment]
Hi @soniaparikh, are you requesting authorization to the EventStore with `authorizeEventStore` first? Events will then get saved to your default calendar.

**Comment by soniaparikh** [comment]
Yes. I am checking status as well. Following is my code. 

 handleButtonPress (){
    RNCalendarEvents.authorizeEventStore(({status}) => {
      if(status == 'authorized')
      {
          RNCalendarEvents.saveEvent('title', {
          location: 'location',
          notes: 'notes',
          startDate: '2016-10-01T09:45:00.000UTC'
        });
          console.log("EVENT ADDED")
      }
    });
  }

I tried to add remainders. Its getting added. But I do not see any events.

**Comment by wmcmahan** [comment]
Are you seeing any errors? Also, try adding an end date.

**Comment by soniaparikh** [comment]
I tired with end date and it works. Thank you very much.

**Comment by wmcmahan** [comment]
Great!
