### ISSUE TITLE
Updating event does not update recurrence

### ISSUE THREAD

**Issue by itswaze** [wmcmahan/react-native-calendar-events#81]
Hi!

When I'm updating an event by it's ID I cannot update the recurrence. If previously I selected to repeat each week, when updating, if I choose to never repeat, it won't delete the future events.

Is there any way to update recurrence?

**Comment by wmcmahan** [comment]
@itswaze, which environment is this, iOS or Android? Did you try editing the "endDate" in "recurrenceRule"?

**Comment by itswaze** [comment]
Its happening on iOS, haven't tried on Android. I didn't try editing an `endDate` because it's supposed to not have one. 

Right now I'm using a workaround. Everytime I edit an event, it deletes the current one (including future events) and I save the new one. Which works perfectly fine for what I need. But I'll try with the `recurrenceRule` when I have more time.

I'm closing for now. Thank you :)
