### ISSUE TITLE
How add URL event property

### ISSUE THREAD

**Issue by jose920405** [wmcmahan/react-native-calendar-events#82]
In your table when you relate all available keys for create the event, i can't see `url` key.

![image1](https://user-images.githubusercontent.com/12536184/29881645-ca5a6ae8-8d70-11e7-9b41-f2fa7141aa48.PNG)

**Comment by wmcmahan** [comment]
@jose920405, for iOS you can define a `url` property. Looks like it was accidentally left out of the readme.
