### ISSUE TITLE
Android remove recurring events Progress?

### ISSUE THREAD

**Issue by GroupXTech** [wmcmahan/react-native-calendar-events#83]
Any idea when you'll be able to finish this?

**Comment by wmcmahan** [comment]
Hi @GroupXTech, `removeEvent` should remove recurring events on Android.

**Comment by GroupXTech** [comment]
What I meant was, IOS has the option to remove all future events belonging to a series or just remove a single event from the series. Android doesn't have this feature currently. Are you working on this feature?

**Comment by wmcmahan** [comment]
Ok thanks, I understand now. You wish to remove a single instance from recurring series. Makes sense. Yes, this is something that can be added for future release.

**Comment by wmcmahan** [comment]
Closing - this is now possible. Ex:
```javascript
RNCalendarEvents.removeEvent('142', {
  exceptionDate: new Date('2019-12-26T09:46:00.000Z'
})
```

**Comment by GroupXTech** [comment]
AWESOME thanks
