### ISSUE TITLE
Unclear or Incorrect Documentation for notes/description Property

### ISSUE THREAD

**Issue by Orion751** [wmcmahan/react-native-calendar-events#85]
The README gave me the impression that to target Android, I would use the description property when passing to the settings parameter for saveEvent().

This had no effect, so I glanced through the Java source code to find mention of a notes property, which the README stated to be exclusive to iOS.  Using notes enabled me to use saveEvent() as desired for my Android project, as shown in the code below:

```
      RNCalendarEvents.saveEvent(event.title, {
        location: event.location,
        notes: event.description,
        startDate: event.startDate,
        endDate: event.endDate,
        calendarId: destCalId
      });
```
Was there something I misunderstood, or does the README need to be updated?

Not sure if this is the right place to say it, but thank you so much for this library.  It has enabled me to make my first serious mobile app, which is now usable!

**Comment by wmcmahan** [comment]
Congrats @Orion751, I'm happy to hear that this has been useful in your project! You are correct, it appears that some naming conventions were crossed. `description` should be the correct property when setting this field in Android. This should be updated in master now.
