### ISSUE TITLE
Android Permissions are always 'denied' even when we haven't checked yet.

### ISSUE THREAD

**Issue by agrosner** [wmcmahan/react-native-calendar-events#88]
I display a ui for when user does not have access vs. when they have not requested access. 

I check for authorization status as so:
```
 RNCalendarEvents.authorizationStatus()
      .then((status) => this.setState({ calendarStatus: status }))
      .catch(() => this.setState({ calendarStatus: 'error' }));
```
and display whether we need access, have access, and denied access. 

on iOS this works great. We are given back `undetermined` and can display request access UI. 
on Android we are returned `denied` always even if we have not actually checked on the device. So the user always sees the denied access UI. 

the issue probably has to do with this check:
```
@ReactMethod
    public void getCalendarPermissions(Promise promise) {
        if (this.haveCalendarReadWritePermissions()) {
            promise.resolve("authorized");
        } else {
            promise.resolve("denied");
        }
    }
```

You resolve the promise with `denied` without noting whether we've checked for permission or not. So I would suggest a simple `SharedPreference` for determining whether permission check has executed or not and returning `undetermined` when its first time checking. This would bring it inline with iOS and expected behavior.

**Comment by wmcmahan** [comment]
Hey @agrosner, great suggestion. I will work on getting this in parity with iOS.

**Comment by agrosner** [comment]
awesome. thank you.

**Comment by wmcmahan** [comment]
Latest changes are in master 👍
