### ISSUE TITLE
Crash when calling RNCalendarEvents.authorizeEventStore()

### ISSUE THREAD

**Issue by jedrichards** [wmcmahan/react-native-calendar-events#92]
I'm using React Native `0.47.2`, and `1.4.2` of your library. iOS.

When I call `RNCalendarEvents.authorizeEventStore()` either on the iOS Simulator or a real iPhone the app immediately crashes, no red screen - it just quits.

Any ideas?

Here's the code that causes the crash:

```
RNCalendarEvents.authorizationStatus()
      .then(status => {
        console.log(status);
        RNCalendarEvents.authorizeEventStore()
          .then(status => {
            console.log(status);
          })
          .catch(err => {
            console.log(err);
          });
      })
      .catch(err => {
        console.log(err);
      });
```

(Also when I call `fetchAllEvents(date, date)` it just returns an empty array, even though I have dates in my calendar.)

**Comment by wmcmahan** [comment]
Hi @jedrichards, it sounds like you may need to set privacy description for the calendar - [iOS setup](https://github.com/wmcmahan/react-native-calendar-events#ios). Also, you won't be able to fetch event if authorization to access the calendar has not been granted.

**Comment by jedrichards** [comment]
Yes, that was it. I'm new to React Native and this stumped me for a while, so I added a PR to amend the readme to hopefully make this process a little more clear.

Thanks! 🙇
