### ISSUE TITLE
Android 8.0 saveEvent's return type

### ISSUE THREAD

**Issue by Sunakujira1** [wmcmahan/react-native-calendar-events#95]
Hi, this library has been very helpful for my project, but I noticed some issues testing with Android 8.0. Here's one of the feedback:

The return value of `saveEvent`(created event's ID) is returning number rather than String as documented.
Other methods such as `removeEvent` and `saveEvent`'s updating still expects String, and shows error when I pass the ID directly into them.
I'm currently forced to `.toString()` the ID every time, which I think isn't ideal.

**Comment by wmcmahan** [comment]
Yes, that is not ideal. I will update this. Thanks @Sunakujira1

**Comment by Sunakujira1** [comment]
Thank you too @wmcmahan

**Comment by wmcmahan** [comment]
Closing - returned value should be of type string now.
