### ISSUE TITLE
Android 8.0 Description

### ISSUE THREAD

**Issue by Sunakujira1** [wmcmahan/react-native-calendar-events#96]
Hi, this library has been very helpful for my project, but I noticed some issues testing with Android 8.0. Here's another feedback:

The `description` option seems to not set anything, but if I set it as `notes` instead, it works just fine.

**Comment by wmcmahan** [comment]
Hey @Sunakujira1, this issue should be corrected in the latest release.

**Comment by Sunakujira1** [comment]
I thought I was using the latest but turns out I was on 1.4.1. Thanks @wmcmahan!
