### ISSUE TITLE
Detach Events

### ISSUE THREAD

**Issue by paulmichalak** [wmcmahan/react-native-calendar-events#98]
I may be missing something obvious, but I don't see any way to detach calendar events. When I have a repeating event and I want to change a single instance of it, it just seem to replace all of the events even if I pass in `isDetached` as true (which I assumed was read only anyway).

**Comment by wmcmahan** [comment]
Thanks @paulmichalak, yes currently it updates all instances of a recurring event - [line in reference](https://github.com/wmcmahan/react-native-calendar-events/blob/master/RNCalendarEvents.m#L172). I agree with the need to update a single instance though. I will work on a solution for this.

**Comment by wmcmahan** [comment]
Closing - single event instances can now be edited. Ex:
```javascript
RNCalendarEvents.saveEvent('Title', {
  notes: 'Note for specific date in recurring series'
}, {
  exceptionDate: '2019-12-01T09:45:00.000Z'
  futureEvents: false
})
```
