### ISSUE TITLE
Alarm specified as a negative number crashes Android

### ISSUE THREAD

**Issue by stiang** [wmcmahan/react-native-calendar-events#99]
Just a heads-up that we experienced a hard crash (nothing in the log) on Android when we tried adding an event with an alarm, where the value for the `date` property was the number -180, which according to the docs means the number of minutes relative to the start time. Something like this:

```js
const calId = await RNCalendarEvents.saveEvent('some name', {
  location: 'some location',
  notes: 'some notes',
  startDate: moment(item.from).toISOString(),
  endDate: moment(item.to).toISOString(),
  alarms: [{
    date: -180,
  }],
});
```

The problem went away when we supplied an ISO date string as the value, ie.

```js
  alarms: [{
    date: moment(item.from).subtract(3, 'hours').toISOString(),
  }],
```

I didn’t investigate whether it was the negativeness or just using a number that caused it.

This was with RN 0.47.2 and RNCE 1.4.3.

**Comment by wmcmahan** [comment]
Thank you @stiang. I will work on resolving this and properly handling the exception.

**Comment by RafaelKr** [comment]
@wmcmahan JFYI: It also crashed if you specify `0`.

**Comment by kalyanipullela** [comment]
can anyone explain me this statement

` date: moment(item.from).subtract(3, 'hours').toISOString(),`

is this same as, the time we invoke this event, does the alarm rings after 3 hours as specified or 3 hours before?
can anyone help me out with this.

Thank you.

**Comment by nol13** [comment]
^before

this happens only on emulator for me, on device is fine
